// v3 batch — fills geographic and category gaps in supplier_listings.
//
// After v1 (67 legacy) + overseas (12) + AI translations (71) + v2 (62 large
// brands), the catalog had 208 rows skewed to 江苏/上海/山东/浙江 + XL/L tier
// brand names. This batch (~95 rows) targets:
//   • underrepresented provinces (江西/安徽/福建/湖北/河南/广西/陕西/吉林/
//     黑龙江/重庆/内蒙古/广东 SME / 辽宁 / 甘肃)
//   • underrepresented categories (service — research/standards/certification,
//     tooling, mold workshops, specialty pultrusion, hydrogen tanks, marine)
//   • mid/small (M/S) tier shops to balance the XL-heavy current catalog
//
// Sourcing rule (same as v1): only firms/institutions whose existence and
// composite-industry relevance I have high public-knowledge confidence in;
// generic descriptions when capacity/cert details aren't broadly public; all
// rows verified=false so BD/operators must vet before customer-facing use.
//
// Idempotent on `id` — safe to re-run after edits.

import { db } from "@/lib/db";
import { supplierListings } from "@/lib/db/schema";

type SeedEntry = {
  id: string;
  name: string;
  nameEn: string;
  location: string;
  locationEn: string;
  province: string;
  category: string;
  products: string[];
  productsEn: string[];
  processList: string[];
  processListEn: string[];
  established: number;
  verified: boolean;
  description: string;
  descriptionEn: string;
  certifications: string[];
  certificationsEn: string[];
};

const entries: SeedEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // A. Research & education (service category) — 高校 / 院所 / 重点实验室
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "svc-buct-cf-lab",
    name: "北京化工大学碳纤维及功能高分子教育部重点实验室",
    nameEn: "BUCT Key Laboratory of Carbon Fiber and Functional Polymers (MOE)",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["碳纤维原丝研究", "高性能聚合物研究", "中试服务"],
    productsEn: ["Carbon fiber precursor R&D", "High-performance polymer research", "Pilot-scale services"],
    processList: ["PAN 原丝聚合", "氧化碳化"],
    processListEn: ["PAN precursor polymerization", "Oxidation & carbonization"],
    established: 2007,
    verified: false,
    description: "教育部重点实验室，承担碳纤维原丝、高性能聚合物方向的基础与应用研究，对接企业中试。",
    descriptionEn:
      "MOE Key Lab at Beijing University of Chemical Technology focused on carbon fiber precursor and high-performance polymer research. Supports industrial pilot-scale collaboration.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-hit-composite",
    name: "哈尔滨工业大学复合材料与结构研究所",
    nameEn: "HIT Center for Composite Materials and Structures",
    location: "黑龙江哈尔滨",
    locationEn: "Harbin, Heilongjiang, China",
    province: "黑龙江",
    category: "service",
    products: ["复合材料结构设计", "力学性能测试", "失效分析"],
    productsEn: ["Composite structure design", "Mechanical testing", "Failure analysis"],
    processList: ["仿真建模", "实验验证"],
    processListEn: ["Simulation & modeling", "Experimental validation"],
    established: 1986,
    verified: false,
    description: "哈工大下属研究机构，长期承担航天/航空复合材料结构研究，设计与试验能力国内领先。",
    descriptionEn:
      "HIT research institute with long-standing aerospace composite structures program. Provides design, simulation, and experimental validation services to industry.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-whut-composite",
    name: "武汉理工大学先进材料研究院",
    nameEn: "WHUT Institute of Advanced Materials",
    location: "湖北武汉",
    locationEn: "Wuhan, Hubei, China",
    province: "湖北",
    category: "service",
    products: ["复合材料研发", "新材料中试", "测试分析"],
    productsEn: ["Composite material R&D", "New material pilot scale-up", "Testing & analysis"],
    processList: ["材料合成", "结构表征"],
    processListEn: ["Material synthesis", "Structural characterization"],
    established: 1995,
    verified: false,
    description: "武汉理工大学综合性材料科研单位，复合材料、玻璃、生物材料方向均有覆盖。",
    descriptionEn:
      "Comprehensive materials research arm of Wuhan University of Technology, covering composites, glass, and biomaterials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-xjtu-composite",
    name: "西安交通大学材料科学与工程学院",
    nameEn: "XJTU School of Materials Science and Engineering",
    location: "陕西西安",
    locationEn: "Xi'an, Shaanxi, China",
    province: "陕西",
    category: "service",
    products: ["复合材料研究", "结构与失效", "界面研究"],
    productsEn: ["Composite materials research", "Structure & failure", "Interface studies"],
    processList: ["材料表征", "性能评价"],
    processListEn: ["Material characterization", "Performance evaluation"],
    established: 1952,
    verified: false,
    description: "西安交大重点学院之一，承担复合材料、金属基复材、界面化学等方向研究。",
    descriptionEn:
      "One of XJTU's flagship engineering schools, with active research in polymer composites, MMC, and interface chemistry.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-cas-nimte",
    name: "中国科学院宁波材料技术与工程研究所",
    nameEn: "Ningbo Institute of Materials Technology and Engineering, CAS",
    location: "浙江宁波",
    locationEn: "Ningbo, Zhejiang, China",
    province: "浙江",
    category: "service",
    products: ["先进复合材料研发", "高性能纤维", "树脂体系开发"],
    productsEn: ["Advanced composite R&D", "High-performance fibers", "Resin system development"],
    processList: ["材料合成", "中试线"],
    processListEn: ["Material synthesis", "Pilot-line scale-up"],
    established: 2004,
    verified: false,
    description: "中科院宁波材料所，复合材料、高性能纤维、海洋防腐材料是重点研发方向。",
    descriptionEn:
      "CAS institute in Ningbo with strong programs in advanced composites, high-performance fibers, and marine anti-corrosion materials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-cas-imr",
    name: "中国科学院金属研究所",
    nameEn: "Institute of Metal Research, CAS",
    location: "辽宁沈阳",
    locationEn: "Shenyang, Liaoning, China",
    province: "辽宁",
    category: "service",
    products: ["金属基复合材料", "陶瓷基复合材料", "复合涂层"],
    productsEn: ["Metal-matrix composites", "Ceramic-matrix composites", "Composite coatings"],
    processList: ["粉末冶金", "热压烧结"],
    processListEn: ["Powder metallurgy", "Hot-press sintering"],
    established: 1953,
    verified: false,
    description: "中科院金属所是国内 MMC/CMC 研究主力之一，承担航天发动机用复合材料关键项目。",
    descriptionEn:
      "Leading CAS institute for MMC and CMC research, with key roles in aerospace engine composite material projects.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-buaa-materials",
    name: "北京航空航天大学材料科学与工程学院",
    nameEn: "Beihang School of Materials Science and Engineering",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["航空复合材料", "树脂体系研究", "结构验证"],
    productsEn: ["Aerospace composites", "Resin system research", "Structural validation"],
    processList: ["热压罐工艺研究", "RTM 工艺研究"],
    processListEn: ["Autoclave process research", "RTM process research"],
    established: 1952,
    verified: false,
    description: "北航材料学院，航空航天复合材料研究方向有重要影响力，与中航工业系统深度合作。",
    descriptionEn:
      "Beihang's materials school is a major aerospace composites research base, with deep ties to AVIC programs.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-nuaa-materials",
    name: "南京航空航天大学材料科学与技术学院",
    nameEn: "NUAA College of Materials Science and Technology",
    location: "江苏南京",
    locationEn: "Nanjing, Jiangsu, China",
    province: "江苏",
    category: "service",
    products: ["复合材料研究", "智能材料", "多功能复合材料"],
    productsEn: ["Composite materials research", "Smart materials", "Multifunctional composites"],
    processList: ["仿真分析", "工艺研究"],
    processListEn: ["Simulation & analysis", "Process research"],
    established: 1956,
    verified: false,
    description: "南航材料学院，航空航天复合材料、智能复材方向有较强研发实力。",
    descriptionEn:
      "NUAA materials college with strong research capabilities in aerospace composites and smart composite materials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-nudt-fiber",
    name: "国防科技大学新型陶瓷纤维及其复合材料重点实验室",
    nameEn: "NUDT Key Lab of Advanced Ceramic Fibers and Composites",
    location: "湖南长沙",
    locationEn: "Changsha, Hunan, China",
    province: "湖南",
    category: "service",
    products: ["碳化硅纤维", "陶瓷基复材研发", "高温材料"],
    productsEn: ["SiC fibers", "Ceramic-matrix composite R&D", "High-temperature materials"],
    processList: ["先驱体合成", "高温烧结"],
    processListEn: ["Precursor synthesis", "High-temperature sintering"],
    established: 1979,
    verified: false,
    description: "国防科大重点实验室，国内 SiC 纤维与陶瓷基复合材料的关键研发单位。",
    descriptionEn:
      "NUDT key laboratory and one of China's leading R&D institutions for SiC fibers and ceramic-matrix composites.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-tsinghua-materials",
    name: "清华大学材料学院",
    nameEn: "Tsinghua School of Materials Science and Engineering",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["复合材料基础研究", "新型功能材料", "测试服务"],
    productsEn: ["Fundamental composites research", "Novel functional materials", "Testing services"],
    processList: ["合成工艺", "结构表征"],
    processListEn: ["Synthesis processes", "Structural characterization"],
    established: 1988,
    verified: false,
    description: "清华大学材料学院，国家级重点实验室，复合材料、功能材料、纳米材料研究均有布局。",
    descriptionEn:
      "Tsinghua's materials school hosts state key labs and runs broad research programs in composites, functional materials, and nanomaterials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-tjpu-composite",
    name: "天津工业大学先进纺织复合材料研究院",
    nameEn: "Tiangong University Institute of Advanced Textile Composites",
    location: "天津",
    locationEn: "Tianjin, China",
    province: "天津",
    category: "service",
    products: ["纺织复合材料研究", "三维编织", "针刺预制体"],
    productsEn: ["Textile composites research", "3D braiding", "Needled preforms"],
    processList: ["编织工艺", "预制体制造"],
    processListEn: ["Braiding processes", "Preform fabrication"],
    established: 2005,
    verified: false,
    description: "天津工大重点研究单位，纺织复材、预制体、缝合复材方向影响力较强。",
    descriptionEn:
      "Tiangong University research center with strong programs in textile composites, preforms, and stitched composites.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-bit-materials",
    name: "北京理工大学材料学院",
    nameEn: "Beijing Institute of Technology School of Materials Science and Engineering",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["特种复合材料", "防护材料研究", "结构功能一体化"],
    productsEn: ["Special composites", "Protective materials research", "Structural-functional integration"],
    processList: ["工艺研究", "性能评价"],
    processListEn: ["Process research", "Performance evaluation"],
    established: 1952,
    verified: false,
    description: "北理工材料学院，国防与防护方向特种复合材料研究为特色。",
    descriptionEn:
      "BIT's materials school is known for defense-oriented and protective composite material research.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-sjtu-materials",
    name: "上海交通大学材料科学与工程学院",
    nameEn: "SJTU School of Materials Science and Engineering",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "service",
    products: ["金属基复材", "高分子复材", "复合涂层"],
    productsEn: ["Metal-matrix composites", "Polymer composites", "Composite coatings"],
    processList: ["合成工艺", "微结构表征"],
    processListEn: ["Synthesis processes", "Microstructural characterization"],
    established: 1928,
    verified: false,
    description: "上海交大材料学院，金属基复合材料和先进结构材料有较强研发能力。",
    descriptionEn:
      "SJTU's materials school has strong R&D capabilities in metal-matrix composites and advanced structural materials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-bgrimm-research",
    name: "蚌埠玻璃工业设计研究院",
    nameEn: "Bengbu Design and Research Institute for Glass Industry (CTIEC)",
    location: "安徽蚌埠",
    locationEn: "Bengbu, Anhui, China",
    province: "安徽",
    category: "service",
    products: ["玻璃工业设计", "玻璃纤维生产线设计", "技术服务"],
    productsEn: ["Glass industry design", "Glass fiber production line design", "Technical services"],
    processList: ["工程设计", "EPC 总包"],
    processListEn: ["Engineering design", "EPC turn-key"],
    established: 1953,
    verified: false,
    description: "中国建材集团旗下，国内玻璃及玻纤工业设计领域龙头研究院。",
    descriptionEn:
      "China Triumph International Engineering subsidiary; leading domestic design institute for glass and glass-fiber industries.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "svc-fjirsm",
    name: "中国科学院福建物质结构研究所",
    nameEn: "Fujian Institute of Research on the Structure of Matter, CAS",
    location: "福建福州",
    locationEn: "Fuzhou, Fujian, China",
    province: "福建",
    category: "service",
    products: ["先进材料研究", "光功能材料", "结构表征"],
    productsEn: ["Advanced materials research", "Photofunctional materials", "Structural characterization"],
    processList: ["材料合成", "晶体生长"],
    processListEn: ["Material synthesis", "Crystal growth"],
    established: 1960,
    verified: false,
    description: "中科院福建物构所，材料合成、结构化学、功能复材方向有较强积累。",
    descriptionEn:
      "CAS Fujian institute with strong heritage in materials synthesis, structural chemistry, and functional composites.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-cas-lzihp",
    name: "中国科学院兰州化学物理研究所",
    nameEn: "Lanzhou Institute of Chemical Physics, CAS",
    location: "甘肃兰州",
    locationEn: "Lanzhou, Gansu, China",
    province: "甘肃",
    category: "service",
    products: ["特种润滑材料", "复合摩擦材料", "表面工程"],
    productsEn: ["Special lubricating materials", "Composite friction materials", "Surface engineering"],
    processList: ["材料合成", "摩擦磨损测试"],
    processListEn: ["Material synthesis", "Tribological testing"],
    established: 1958,
    verified: false,
    description: "中科院兰州化物所，特种润滑/摩擦复合材料是国内代表性研究单位。",
    descriptionEn:
      "CAS Lanzhou institute and one of China's leading research bases for special lubricating and friction composite materials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-cqu-aerospace",
    name: "重庆大学航空航天学院",
    nameEn: "Chongqing University College of Aerospace Engineering",
    location: "重庆",
    locationEn: "Chongqing, China",
    province: "重庆",
    category: "service",
    products: ["航空航天复材", "结构动力学", "失效分析"],
    productsEn: ["Aerospace composites", "Structural dynamics", "Failure analysis"],
    processList: ["仿真分析", "试验验证"],
    processListEn: ["Simulation & analysis", "Experimental validation"],
    established: 2014,
    verified: false,
    description: "重大新设航空航天学院，复合材料、结构与可靠性是主要研究方向之一。",
    descriptionEn:
      "Newly established Chongqing University college focusing on aerospace composites, structures, and reliability research.",
    certifications: [],
    certificationsEn: [],
  },
  {
    id: "svc-jlu-materials",
    name: "吉林大学材料科学与工程学院",
    nameEn: "Jilin University College of Materials Science and Engineering",
    location: "吉林长春",
    locationEn: "Changchun, Jilin, China",
    province: "吉林",
    category: "service",
    products: ["高分子复合材料", "金属基复材", "汽车轻量化材料"],
    productsEn: ["Polymer composites", "Metal-matrix composites", "Automotive lightweight materials"],
    processList: ["材料合成", "性能测试"],
    processListEn: ["Material synthesis", "Property testing"],
    established: 1953,
    verified: false,
    description: "吉大材料学院，依托一汽产学研，汽车轻量化复合材料研究有较多积累。",
    descriptionEn:
      "Jilin University materials college with industry-research ties to FAW, focused on automotive lightweight composite materials.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-tongji-aviation",
    name: "同济大学航空航天与力学学院",
    nameEn: "Tongji University School of Aerospace Engineering and Applied Mechanics",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "service",
    products: ["复合材料力学", "结构设计", "无人机复材结构"],
    productsEn: ["Composite mechanics", "Structural design", "UAV composite structures"],
    processList: ["仿真建模", "试验验证"],
    processListEn: ["Simulation & modeling", "Experimental validation"],
    established: 2008,
    verified: false,
    description: "同济大学航空学院，复合材料结构、无人机轻量化方向有学术积累。",
    descriptionEn:
      "Tongji aerospace school with research strengths in composite structures and UAV lightweight design.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // B. Industry associations & certification bodies (service)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "svc-ccia-association",
    name: "中国复合材料工业协会",
    nameEn: "China Composites Industry Association (CCIA)",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["行业统计", "标准制定", "展会组织"],
    productsEn: ["Industry statistics", "Standards development", "Exhibition organization"],
    processList: ["年度统计", "团体标准制定"],
    processListEn: ["Annual statistics", "Industry-association standards"],
    established: 1989,
    verified: false,
    description: "中国复合材料行业最具代表性的全国性社团，主办 CCE 复材展，发布团体标准与年度数据。",
    descriptionEn:
      "China's primary national composites trade association. Organizes the CCE composites expo, issues industry-association standards, and publishes annual market data.",
    certifications: [],
    certificationsEn: [],
  },
  {
    id: "svc-cgfa-association",
    name: "中国玻璃纤维工业协会",
    nameEn: "China Fiberglass Industry Association",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["行业数据", "标准协调", "展会组织"],
    productsEn: ["Industry data", "Standard coordination", "Exhibition organization"],
    processList: ["统计分析", "政策对接"],
    processListEn: ["Statistical analysis", "Policy liaison"],
    established: 1986,
    verified: false,
    description: "全国性玻璃纤维行业组织，发布产能、出口、价格等行业基础数据，承担政企对接。",
    descriptionEn:
      "National fiberglass industry association. Publishes capacity, export, and pricing benchmarks; serves as the industry-government liaison body.",
    certifications: [],
    certificationsEn: [],
  },
  {
    id: "svc-tc39-frp-standards",
    name: "全国纤维增强塑料标准化技术委员会(SAC/TC39)",
    nameEn: "National Technical Committee 39 on Fibre Reinforced Plastics of SAC",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["国家标准制订", "行业标准制订", "标准查询"],
    productsEn: ["National standards drafting", "Industry standards drafting", "Standard look-up"],
    processList: ["标准起草", "意见征集"],
    processListEn: ["Standard drafting", "Public consultation"],
    established: 1979,
    verified: false,
    description: "SAC/TC39，归口我国 FRP 国家与行业标准制修订工作。",
    descriptionEn:
      "SAC/TC39 — China's national TC overseeing FRP national and industry standards drafting and revision.",
    certifications: [],
    certificationsEn: [],
  },
  {
    id: "svc-tuv-sud-china",
    name: "TÜV南德意志大中华集团",
    nameEn: "TÜV SÜD Greater China",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "service",
    products: ["产品认证", "管理体系认证", "材料检测"],
    productsEn: ["Product certification", "Management system certification", "Material testing"],
    processList: ["实验室测试", "工厂审核"],
    processListEn: ["Laboratory testing", "Factory audit"],
    established: 2000,
    verified: false,
    description: "TÜV 南德中国总部，承接 ISO 体系、CE、UL、风电叶片等多类认证业务。",
    descriptionEn:
      "TÜV SÜD's Greater China head office. Provides ISO, CE, UL, and wind blade certification services across the composites supply chain.",
    certifications: ["CNAS", "ISO/IEC 17025"],
    certificationsEn: ["CNAS", "ISO/IEC 17025"],
  },
  {
    id: "svc-bv-china",
    name: "必维国际检验集团(中国)",
    nameEn: "Bureau Veritas China",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "service",
    products: ["材料检测", "无损检测", "海事认证"],
    productsEn: ["Material testing", "Non-destructive testing", "Marine certification"],
    processList: ["实验室测试", "现场检验"],
    processListEn: ["Laboratory testing", "On-site inspection"],
    established: 1828,
    verified: false,
    description: "Bureau Veritas 中国分部，复合材料检测、海事/风电认证业务覆盖全产业链。",
    descriptionEn:
      "Bureau Veritas China branch. Composite testing plus marine and wind certification services covering the full composites value chain.",
    certifications: ["CNAS", "ISO/IEC 17025"],
    certificationsEn: ["CNAS", "ISO/IEC 17025"],
  },
  {
    id: "svc-dnv-china",
    name: "挪威船级社(DNV)上海代表处",
    nameEn: "DNV Shanghai",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "service",
    products: ["风电叶片认证", "海事认证", "氢能装备认证"],
    productsEn: ["Wind blade certification", "Marine certification", "Hydrogen equipment certification"],
    processList: ["设计审查", "型式试验"],
    processListEn: ["Design review", "Type testing"],
    established: 1864,
    verified: false,
    description: "挪威船级社中国主区，风电叶片型式认证与新能源装备认证业务覆盖国内主要 OEM。",
    descriptionEn:
      "DNV's China hub. Wind blade type certification and renewable equipment certification serving China's main OEMs.",
    certifications: ["CNAS"],
    certificationsEn: ["CNAS"],
  },
  {
    id: "svc-ccs-rules",
    name: "中国船级社(CCS)总部",
    nameEn: "China Classification Society (CCS) Headquarters",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "service",
    products: ["船舶入级", "海工装备认证", "风电叶片认证"],
    productsEn: ["Ship classification", "Offshore equipment certification", "Wind blade certification"],
    processList: ["设计审查", "现场检验"],
    processListEn: ["Design review", "On-site inspection"],
    established: 1956,
    verified: false,
    description: "中国官方船级社，覆盖船舶/海工/海上风电领域复材结构入级与认证。",
    descriptionEn:
      "China's national classification society. Issues classification and certification for marine, offshore, and offshore-wind composite structures.",
    certifications: ["IACS member"],
    certificationsEn: ["IACS member"],
  },
  {
    id: "svc-caeri-chongqing",
    name: "中国汽车工程研究院股份有限公司",
    nameEn: "China Automotive Engineering Research Institute Co., Ltd. (CAERI)",
    location: "重庆",
    locationEn: "Chongqing, China",
    province: "重庆",
    category: "service",
    products: ["整车测试", "材料认证", "轻量化研究"],
    productsEn: ["Vehicle testing", "Material certification", "Lightweighting research"],
    processList: ["碰撞测试", "材料表征"],
    processListEn: ["Crash testing", "Material characterization"],
    established: 1965,
    verified: false,
    description: "中国汽研，承担汽车碰撞、材料认证、轻量化等业务，复材车身件评价资质完整。",
    descriptionEn:
      "CAERI — accredited Chinese automotive engineering R&D body covering crash, material certification, and lightweighting evaluation including composite body parts.",
    certifications: ["CNAS", "CMA"],
    certificationsEn: ["CNAS", "CMA"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // C. Hydrogen tank / pressure vessel composites (filling type-IV gap)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-tianhai-h2",
    name: "北京天海工业有限公司",
    nameEn: "Beijing Tianhai Industry Co., Ltd.",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "manufacturer",
    products: ["车用高压储氢瓶", "CNG 气瓶", "复合材料压力容器"],
    productsEn: ["Vehicle hydrogen storage cylinders", "CNG cylinders", "Composite pressure vessels"],
    processList: ["湿法缠绕", "干法缠绕"],
    processListEn: ["Wet filament winding", "Dry filament winding"],
    established: 1992,
    verified: false,
    description: "京城机电下属高压气瓶主力企业，35MPa/70MPa 车用储氢瓶与 CNG 气瓶产品线齐全。",
    descriptionEn:
      "Subsidiary of Jingcheng Mechatronic. Major Chinese supplier of 35 MPa / 70 MPa vehicle hydrogen and CNG composite pressure cylinders.",
    certifications: ["ISO 9001", "TPED"],
    certificationsEn: ["ISO 9001", "TPED"],
  },
  {
    id: "fin-sinoma-pv",
    name: "中材科技氢能装备业务",
    nameEn: "Sinoma Science & Technology — Hydrogen Equipment Division",
    location: "江苏南京",
    locationEn: "Nanjing, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["IV 型储氢瓶", "氢气运输瓶组", "70MPa 车载储氢系统"],
    productsEn: ["Type-IV hydrogen tanks", "H2 transport cylinder packs", "70 MPa onboard hydrogen storage"],
    processList: ["塑料内胆吹塑", "碳纤维缠绕"],
    processListEn: ["Plastic liner blow-molding", "Carbon fiber winding"],
    established: 2017,
    verified: false,
    description: "中材科技子公司，专注 III/IV 型车用储氢瓶研发与产业化，国内首条 IV 型储氢瓶量产线之一。",
    descriptionEn:
      "Sinoma S&T hydrogen subsidiary. Among the first Chinese producers of Type-III and Type-IV vehicular hydrogen tanks at commercial scale.",
    certifications: ["TPED", "ISO 9001"],
    certificationsEn: ["TPED", "ISO 9001"],
  },
  {
    id: "fin-sinoma-lianzhong-pv",
    name: "沈阳斯林达安科新技术有限公司",
    nameEn: "Shenyang Selande Anke Technology Co., Ltd.",
    location: "辽宁沈阳",
    locationEn: "Shenyang, Liaoning, China",
    province: "辽宁",
    category: "manufacturer",
    products: ["IV 型储氢瓶", "高压气瓶", "复合材料容器"],
    productsEn: ["Type-IV hydrogen tanks", "High-pressure gas cylinders", "Composite vessels"],
    processList: ["塑料内胆", "碳纤维缠绕"],
    processListEn: ["Plastic liner", "Carbon fiber winding"],
    established: 2007,
    verified: false,
    description: "国内 IV 型储氢瓶量产代表企业之一，70MPa 车载储氢瓶已用于氢燃料电池公交。",
    descriptionEn:
      "Major Chinese Type-IV hydrogen cylinder producer. 70 MPa onboard tanks deployed in fuel-cell bus fleets.",
    certifications: ["TPED", "ISO 9001"],
    certificationsEn: ["TPED", "ISO 9001"],
  },
  {
    id: "fin-blue-energy-h2",
    name: "浙江蓝能氢能源科技股份有限公司",
    nameEn: "Zhejiang Blue Energy Hydrogen Co., Ltd.",
    location: "浙江湖州",
    locationEn: "Huzhou, Zhejiang, China",
    province: "浙江",
    category: "manufacturer",
    products: ["氢气运输管束车", "加氢站设备", "复合气瓶组"],
    productsEn: ["Hydrogen tube trailers", "Hydrogen refueling station equipment", "Composite cylinder skids"],
    processList: ["碳纤维缠绕", "总成集成"],
    processListEn: ["Carbon fiber winding", "Skid assembly"],
    established: 2012,
    verified: false,
    description: "国内氢能装备主力供应商，长管拖车与加氢站集成业务并重。",
    descriptionEn:
      "Leading Chinese hydrogen equipment supplier. Tube trailers and refueling-station integration are core business lines.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // D. Aerospace / aviation composites (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-xian-aircraft-composite",
    name: "西安飞机工业(集团)复合材料厂",
    nameEn: "Xi'an Aircraft Industry (Group) Composite Materials Factory",
    location: "陕西西安",
    locationEn: "Xi'an, Shaanxi, China",
    province: "陕西",
    category: "manufacturer",
    products: ["航空复合材料结构件", "热压罐成型件", "AFP 铺放件"],
    productsEn: ["Aerospace composite structural parts", "Autoclave-cured parts", "AFP-laid components"],
    processList: ["热压罐成型", "AFP 自动铺放", "RTM"],
    processListEn: ["Autoclave curing", "Automated fiber placement", "RTM"],
    established: 1958,
    verified: false,
    description: "中航工业西飞下属复合材料厂，承担运 20、轰 6、ARJ21 等机型主要复材结构件。",
    descriptionEn:
      "AVIC XAC's composite materials division. Supplies primary structural composites for Y-20, H-6, ARJ21 and related programs.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "fin-cac-composite",
    name: "成都飞机工业(集团)复合材料结构件厂",
    nameEn: "Chengdu Aircraft Industry (Group) Composite Structural Components Factory",
    location: "四川成都",
    locationEn: "Chengdu, Sichuan, China",
    province: "四川",
    category: "manufacturer",
    products: ["战机复材结构件", "热压罐预浸料件", "整体共固化件"],
    productsEn: ["Fighter aircraft composite parts", "Autoclave prepreg components", "Co-cured integrated structures"],
    processList: ["热压罐成型", "整体共固化"],
    processListEn: ["Autoclave curing", "Co-cured integration"],
    established: 1958,
    verified: false,
    description: "中航工业成飞复合材料能力中心，承担歼 10、歼 20 等机型复材结构件研制。",
    descriptionEn:
      "AVIC CAC composite center. Supplies composite structural parts for J-10, J-20 and related fighter programs.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "fin-hongdu-composite",
    name: "中航工业洪都复合材料厂",
    nameEn: "AVIC Hongdu Composite Materials Factory",
    location: "江西南昌",
    locationEn: "Nanchang, Jiangxi, China",
    province: "江西",
    category: "manufacturer",
    products: ["航空结构复材件", "教练机复材件", "无人机复材件"],
    productsEn: ["Aerospace composite parts", "Trainer aircraft components", "UAV composite parts"],
    processList: ["热压罐成型", "RTM"],
    processListEn: ["Autoclave curing", "RTM"],
    established: 1951,
    verified: false,
    description: "中航工业洪都集团下属复材生产单元，教练机与小型作战平台复材件供应商。",
    descriptionEn:
      "AVIC Hongdu's composite manufacturing arm. Supplies trainer aircraft and small combat platform composite parts.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "fin-guizhou-aviation",
    name: "中航工业贵州航空工业(集团)复材业务",
    nameEn: "AVIC Guizhou Aviation Industry Group — Composite Business",
    location: "贵州贵阳",
    locationEn: "Guiyang, Guizhou, China",
    province: "贵州",
    category: "manufacturer",
    products: ["航空复材结构件", "无人机复材件", "发动机复材附件"],
    productsEn: ["Aerospace composite structures", "UAV composite parts", "Engine composite accessories"],
    processList: ["热压罐成型", "RTM"],
    processListEn: ["Autoclave curing", "RTM"],
    established: 1964,
    verified: false,
    description: "中航工业贵航集团复材业务，配套军用飞机与无人机平台。",
    descriptionEn:
      "AVIC Guizhou's composite operations support military aircraft and UAV platforms.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "fin-hafei-composite-extra",
    name: "中航工业哈飞 ARJ21 复材后机身分厂",
    nameEn: "AVIC HAIG ARJ21 Aft-Fuselage Composite Plant",
    location: "黑龙江哈尔滨",
    locationEn: "Harbin, Heilongjiang, China",
    province: "黑龙江",
    category: "manufacturer",
    products: ["ARJ21 后机身复材件", "通用航空复材件", "直升机复材件"],
    productsEn: ["ARJ21 aft-fuselage composites", "General aviation composites", "Helicopter composites"],
    processList: ["热压罐成型", "AFP 铺放"],
    processListEn: ["Autoclave curing", "AFP layup"],
    established: 2008,
    verified: false,
    description: "哈飞配套 ARJ21 后机身复材结构的专用分厂。",
    descriptionEn:
      "HAIG plant dedicated to ARJ21 aft-fuselage composite structures.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // E. Carbon fiber & precursor (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "cf-yingyou-spinning",
    name: "江苏鹰游纺机有限公司",
    nameEn: "Jiangsu Yingyou Textile Machinery Co., Ltd.",
    location: "江苏连云港",
    locationEn: "Lianyungang, Jiangsu, China",
    province: "江苏",
    category: "equipment",
    products: ["碳纤维原丝纺丝设备", "碳化生产线", "氧化炉"],
    productsEn: ["Carbon fiber precursor spinning lines", "Carbonization lines", "Oxidation ovens"],
    processList: ["原丝设备制造", "碳化炉制造"],
    processListEn: ["Precursor equipment manufacturing", "Carbonization furnace manufacturing"],
    established: 1991,
    verified: false,
    description: "国内主流碳纤维生产线设备供应商，与中复神鹰深度合作。",
    descriptionEn:
      "Major domestic supplier of carbon fiber production line equipment. Long-term partner of Zhongfu Shenying.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
{
    id: "cf-shanghai-petro-cf-extra",
    name: "中石化上海石化碳纤维 24K 大丝束生产线",
    nameEn: "SINOPEC SPC 24K Large-Tow Carbon Fiber Line",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "fiber",
    products: ["48K/50K 大丝束碳纤维", "工业用碳纤维"],
    productsEn: ["48K/50K large-tow carbon fiber", "Industrial-grade carbon fiber"],
    processList: ["PAN 原丝聚合", "氧化碳化"],
    processListEn: ["PAN precursor polymerization", "Oxidation & carbonization"],
    established: 2022,
    verified: false,
    description: "中石化上海石化大丝束碳纤维产线，定位风电与储氢市场。",
    descriptionEn:
      "SINOPEC SPC large-tow carbon fiber line, positioned for wind energy and hydrogen storage applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "cf-baojing-carbon",
    name: "山东宝旌新材料有限公司",
    nameEn: "Shandong Baojing New Materials Co., Ltd.",
    location: "山东淄博",
    locationEn: "Zibo, Shandong, China",
    province: "山东",
    category: "fiber",
    products: ["T300/T700 级碳纤维", "工业用碳纤维"],
    productsEn: ["T300/T700-grade carbon fiber", "Industrial-grade carbon fiber"],
    processList: ["氧化碳化"],
    processListEn: ["Oxidation & carbonization"],
    established: 2020,
    verified: false,
    description: "原精功新材料碳纤维资产承接公司，T300/T700 级产品供应国内复材市场。",
    descriptionEn:
      "Carrier of the former Jinggong carbon fiber assets. Supplies T300/T700-grade fiber to the domestic composites market.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "cf-jingbo-precursor",
    name: "山东金博新材料股份有限公司",
    nameEn: "Hunan Jinbo Bio-Energy Tech Co., Ltd. (Carbon/carbon division)",
    location: "湖南长沙",
    locationEn: "Changsha, Hunan, China",
    province: "湖南",
    category: "manufacturer",
    products: ["碳/碳热场材料", "光伏热场坩埚", "导流筒"],
    productsEn: ["Carbon/carbon thermal field parts", "PV thermal-field crucibles", "Guide cylinders"],
    processList: ["编织成型", "化学气相沉积"],
    processListEn: ["Braided preform", "Chemical vapor infiltration"],
    established: 2005,
    verified: false,
    description: "国内光伏与半导体单晶炉碳/碳热场龙头，A 股科创板上市公司。",
    descriptionEn:
      "Leading Chinese supplier of C/C composite thermal-field components for PV and semiconductor single-crystal furnaces. STAR Market listed.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "cf-tianniao-extra",
    name: "江苏天鸟高新预制体工厂",
    nameEn: "Jiangsu Tianniao Hi-Tech Preform Plant",
    location: "江苏宜兴",
    locationEn: "Yixing, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["碳/碳预制体", "针刺预制体", "三维编织预制体"],
    productsEn: ["C/C preforms", "Needled preforms", "3D braided preforms"],
    processList: ["针刺", "三维编织"],
    processListEn: ["Needle punching", "3D braiding"],
    established: 2002,
    verified: false,
    description: "国内主要碳/碳预制体专业制造商，配套航天/航空/光伏热场。",
    descriptionEn:
      "Leading domestic specialist in C/C preforms supplying aerospace, aviation, and PV thermal-field applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // F. Glass fiber & fabric (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "gf-anhui-danfeng",
    name: "安徽丹凤集团有限公司",
    nameEn: "Anhui Danfeng Group Co., Ltd.",
    location: "安徽庐江",
    locationEn: "Lujiang, Anhui, China",
    province: "安徽",
    category: "fiber",
    products: ["电子级玻纤布", "工业玻纤布", "定型布"],
    productsEn: ["Electronic-grade glass fabric", "Industrial glass fabric", "Sizing fabrics"],
    processList: ["纺织", "后处理"],
    processListEn: ["Weaving", "Post-treatment"],
    established: 1989,
    verified: false,
    description: "安徽老牌玻纤布企业，电子级与工业玻纤布产品线齐全。",
    descriptionEn:
      "Established Anhui glass fabric maker with broad electronic-grade and industrial fabric portfolio.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-jiangxi-hengyou",
    name: "江西恒友新材料股份有限公司",
    nameEn: "Jiangxi Hengyou New Materials Co., Ltd.",
    location: "江西九江",
    locationEn: "Jiujiang, Jiangxi, China",
    province: "江西",
    category: "fiber",
    products: ["E-玻璃纤维", "玻纤直接纱", "短切原丝"],
    productsEn: ["E-glass fiber", "Direct rovings", "Chopped strands"],
    processList: ["玻璃纤维拉丝"],
    processListEn: ["Glass fiber drawing"],
    established: 2003,
    verified: false,
    description: "江西本地玻纤生产商，主要面向国内 FRP 与建材市场。",
    descriptionEn:
      "Jiangxi-based glass fiber producer serving the domestic FRP and construction materials markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-fujian-jianan-glass",
    name: "福建建安玻璃纤维有限公司",
    nameEn: "Fujian Jianan Glass Fiber Co., Ltd.",
    location: "福建泉州",
    locationEn: "Quanzhou, Fujian, China",
    province: "福建",
    category: "fiber",
    products: ["E-玻璃纤维", "玻纤毡", "短切纱"],
    productsEn: ["E-glass fiber", "Glass mat", "Chopped strands"],
    processList: ["玻璃纤维拉丝", "毡板成型"],
    processListEn: ["Glass fiber drawing", "Mat forming"],
    established: 2001,
    verified: false,
    description: "福建本地中型玻纤厂，毡材与短切纱产线服务东南沿海 FRP 市场。",
    descriptionEn:
      "Mid-sized Fujian glass fiber plant supplying mat and chopped strand to the southeastern coastal FRP market.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-hubei-fiberglass",
    name: "湖北菲利华石英玻璃股份有限公司",
    nameEn: "Hubei Feilihua Quartz Glass Co., Ltd.",
    location: "湖北荆州",
    locationEn: "Jingzhou, Hubei, China",
    province: "湖北",
    category: "fiber",
    products: ["石英玻璃纤维", "石英玻纤布", "石英玻纤管"],
    productsEn: ["Quartz glass fiber", "Quartz glass fabric", "Quartz glass tubing"],
    processList: ["石英纤维拉丝", "石英纺织"],
    processListEn: ["Quartz fiber drawing", "Quartz weaving"],
    established: 1966,
    verified: false,
    description: "国内石英玻璃纤维与制品领军企业，A 股上市，应用涵盖半导体、航天耐高温复材。",
    descriptionEn:
      "China's leading quartz glass fiber and product maker, A-share listed. Applications span semiconductor and aerospace high-temperature composites.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-shandong-fiberglass-spc",
    name: "山东国维复材科技有限公司",
    nameEn: "Shandong Guowei Composite Technology Co., Ltd.",
    location: "山东聊城",
    locationEn: "Liaocheng, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["GFRP 筋材", "BFRP 筋材", "FRP 锚杆"],
    productsEn: ["GFRP rebar", "BFRP rebar", "FRP rock bolts"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2010,
    verified: false,
    description: "山东聊城 FRP 筋材专业厂，GFRP/BFRP 筋材广泛用于地铁、隧道、海工。",
    descriptionEn:
      "Liaocheng FRP rebar specialist. GFRP/BFRP rebar widely used in metro, tunnel, and marine engineering projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-shaanxi-jianhua",
    name: "陕西华特新材料股份有限公司",
    nameEn: "Shaanxi Huat New Materials Co., Ltd.",
    location: "陕西咸阳",
    locationEn: "Xianyang, Shaanxi, China",
    province: "陕西",
    category: "fiber",
    products: ["特种玻璃纤维", "高强高模玻纤", "玻纤布"],
    productsEn: ["Specialty glass fiber", "High-strength high-modulus glass fiber", "Glass fabric"],
    processList: ["拉丝", "纺织"],
    processListEn: ["Fiber drawing", "Weaving"],
    established: 2001,
    verified: false,
    description: "陕西本地特种玻璃纤维生产商，部分产品用于国防与航空领域。",
    descriptionEn:
      "Shaanxi-based specialty glass fiber producer supplying defense and aerospace applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // G. Resin / chemicals (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "rs-anhui-guofeng",
    name: "安徽国风新材料股份有限公司",
    nameEn: "Anhui Guofeng New Materials Co., Ltd.",
    location: "安徽合肥",
    locationEn: "Hefei, Anhui, China",
    province: "安徽",
    category: "resin",
    products: ["BOPP/BOPET 薄膜", "光学膜", "复合树脂材料"],
    productsEn: ["BOPP/BOPET films", "Optical films", "Composite resin materials"],
    processList: ["双向拉伸", "聚合"],
    processListEn: ["Biaxial stretching", "Polymerization"],
    established: 1996,
    verified: false,
    description: "安徽国风集团子公司，国内重要薄膜与复合材料原材料供应商，A 股上市。",
    descriptionEn:
      "Subsidiary of Anhui Guofeng Group. Major Chinese supplier of BOPP/BOPET films and composite raw materials. A-share listed.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-fujian-haoyuan",
    name: "福建海源复合材料科技股份有限公司",
    nameEn: "Fujian HaiYuan Composite Materials Technology Co., Ltd.",
    location: "福建福州",
    locationEn: "Fuzhou, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["复合材料汽车零部件", "SMC/BMC 制品", "轻量化车身件"],
    productsEn: ["Automotive composite parts", "SMC/BMC parts", "Lightweight body panels"],
    processList: ["压制成型", "RTM"],
    processListEn: ["Compression molding", "RTM"],
    established: 1990,
    verified: false,
    description: "福建海源，国内 SMC/BMC 大型液压机与汽车复材件主力供应商，A 股上市。",
    descriptionEn:
      "Fujian HaiYuan — major Chinese supplier of SMC/BMC hydraulic press equipment and automotive composite parts. A-share listed.",
    certifications: ["IATF 16949", "ISO 9001"],
    certificationsEn: ["IATF 16949", "ISO 9001"],
  },
  {
    id: "rs-hunan-shenghua",
    name: "湖南神华复合材料树脂有限公司",
    nameEn: "Hunan Shenhua Composite Resin Co., Ltd.",
    location: "湖南岳阳",
    locationEn: "Yueyang, Hunan, China",
    province: "湖南",
    category: "resin",
    products: ["不饱和聚酯树脂", "乙烯基酯树脂", "胶衣"],
    productsEn: ["Unsaturated polyester resin", "Vinyl ester resin", "Gel coats"],
    processList: ["聚合"],
    processListEn: ["Polymerization"],
    established: 2003,
    verified: false,
    description: "湖南本地不饱和树脂厂，配套华中地区 FRP 制品市场。",
    descriptionEn:
      "Hunan-based UPR producer supplying the central-China FRP product market.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-hubei-feilong",
    name: "湖北飞龙摩擦密封材料有限公司",
    nameEn: "Hubei Feilong Friction & Sealing Materials Co., Ltd.",
    location: "湖北襄阳",
    locationEn: "Xiangyang, Hubei, China",
    province: "湖北",
    category: "manufacturer",
    products: ["复合摩擦材料", "刹车片", "离合器面片"],
    productsEn: ["Composite friction materials", "Brake pads", "Clutch facings"],
    processList: ["热压成型"],
    processListEn: ["Hot-press molding"],
    established: 2001,
    verified: false,
    description: "湖北襄阳复合摩擦材料厂，配套国内主要主机厂。",
    descriptionEn:
      "Xiangyang-based composite friction materials maker supplying major Chinese OEMs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "rs-guangdong-flying-elephant",
    name: "广东飞鹅化工实业有限公司",
    nameEn: "Guangdong Flying Goose Chemical Co., Ltd.",
    location: "广东东莞",
    locationEn: "Dongguan, Guangdong, China",
    province: "广东",
    category: "resin",
    products: ["环氧树脂", "聚氨酯树脂", "胶粘剂"],
    productsEn: ["Epoxy resins", "Polyurethane resins", "Adhesives"],
    processList: ["聚合", "复配"],
    processListEn: ["Polymerization", "Compounding"],
    established: 1996,
    verified: false,
    description: "广东本地环氧/聚氨酯树脂厂，主要供应华南电子封装与复材制品市场。",
    descriptionEn:
      "Guangdong-based epoxy/PU resin maker primarily serving south China electronics encapsulation and FRP markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-jiangsu-baichuan-extra",
    name: "江苏百川环保科技有限公司复合材料事业部",
    nameEn: "Jiangsu Baichuan Environmental Protection Tech Composite Division",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "resin",
    products: ["不饱和聚酯树脂", "环氧树脂", "凝胶涂层"],
    productsEn: ["Unsaturated polyester resin", "Epoxy resin", "Gel coats"],
    processList: ["聚合", "复配"],
    processListEn: ["Polymerization", "Compounding"],
    established: 2008,
    verified: false,
    description: "盐城本地树脂厂复材业务线，主要服务华东 FRP 中小客户。",
    descriptionEn:
      "Yancheng-based resin plant's composite line serving east-China SMB FRP customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-zhejiang-huafeng",
    name: "浙江华峰新材料有限公司",
    nameEn: "Zhejiang Huafeng New Materials Co., Ltd.",
    location: "浙江温州",
    locationEn: "Wenzhou, Zhejiang, China",
    province: "浙江",
    category: "resin",
    products: ["聚氨酯树脂", "TPU", "聚氨酯弹性体"],
    productsEn: ["Polyurethane resins", "TPU", "PU elastomers"],
    processList: ["聚合"],
    processListEn: ["Polymerization"],
    established: 1991,
    verified: false,
    description: "华峰系新材料板块，PU/TPU 是国内代表性产能，部分产品用于复材夹芯。",
    descriptionEn:
      "Huafeng Group's new materials arm. Major Chinese PU/TPU producer with applications in composite sandwich cores.",
    certifications: ["ISO 9001", "IATF 16949"],
    certificationsEn: ["ISO 9001", "IATF 16949"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // H. Pultrusion / FRP grating / FRP rebar SMEs (M-tier)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-changzhou-tianma-pul",
    name: "常州天马集团拉挤型材事业部",
    nameEn: "Changzhou Tianma Group Pultrusion Division",
    location: "江苏常州",
    locationEn: "Changzhou, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["GFRP 拉挤型材", "玻璃钢电缆桥架", "玻璃钢标志杆"],
    productsEn: ["GFRP pultruded profiles", "FRP cable trays", "FRP signage poles"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 1995,
    verified: false,
    description: "常州拉挤型材代表企业之一，电缆桥架与基建标志杆国内市占较高。",
    descriptionEn:
      "One of the representative Changzhou pultrusion firms with strong domestic share in FRP cable trays and infrastructure signage poles.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-yangzhou-grating",
    name: "扬州金石玻璃钢有限公司",
    nameEn: "Yangzhou Jinshi Fiberglass Co., Ltd.",
    location: "江苏扬州",
    locationEn: "Yangzhou, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["FRP 格栅板", "拉挤格栅", "玻璃钢平台"],
    productsEn: ["FRP molded grating", "Pultruded grating", "FRP platforms"],
    processList: ["模压成型", "拉挤"],
    processListEn: ["Compression molding", "Pultrusion"],
    established: 2002,
    verified: false,
    description: "扬州本地玻璃钢格栅与拉挤平台专业厂，化工与水处理项目配套较多。",
    descriptionEn:
      "Yangzhou specialist in FRP grating and pultruded platforms, primarily serving chemical and water-treatment projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-fosran-grating",
    name: "佛山市南海科海玻璃钢制品有限公司",
    nameEn: "Foshan Nanhai Kehai Fiberglass Products Co., Ltd.",
    location: "广东佛山",
    locationEn: "Foshan, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["玻璃钢冷却塔", "玻璃钢储罐", "玻璃钢格栅"],
    productsEn: ["FRP cooling towers", "FRP storage tanks", "FRP grating"],
    processList: ["缠绕", "模压"],
    processListEn: ["Filament winding", "Compression molding"],
    established: 1998,
    verified: false,
    description: "佛山本地玻璃钢冷却塔与防腐设备厂，配套华南化工/电力项目。",
    descriptionEn:
      "Foshan FRP cooling tower and anti-corrosion equipment maker serving south-China chemical and power industry projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-tangshan-frp-tank",
    name: "唐山金玻钢复合材料有限公司",
    nameEn: "Tangshan Jin Bo Gang Composite Materials Co., Ltd.",
    location: "河北唐山",
    locationEn: "Tangshan, Hebei, China",
    province: "河北",
    category: "manufacturer",
    products: ["缠绕玻璃钢储罐", "玻璃钢管道", "防腐管件"],
    productsEn: ["Filament-wound FRP tanks", "FRP pipes", "Anti-corrosion fittings"],
    processList: ["缠绕"],
    processListEn: ["Filament winding"],
    established: 1996,
    verified: false,
    description: "河北缠绕玻璃钢储罐管道厂，环保项目配套较多。",
    descriptionEn:
      "Hebei filament-wound FRP tank and pipe maker, primarily serving environmental engineering projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shandong-pipe-frp",
    name: "山东金孚生玻璃钢有限公司",
    nameEn: "Shandong Jinfusheng Fiberglass Co., Ltd.",
    location: "山东淄博",
    locationEn: "Zibo, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["玻璃钢管道", "夹砂管道", "玻璃钢储罐"],
    productsEn: ["FRP pipes", "Sand-filled FRP pipes", "FRP storage tanks"],
    processList: ["连续缠绕", "离心浇铸"],
    processListEn: ["Continuous winding", "Centrifugal casting"],
    established: 1999,
    verified: false,
    description: "山东淄博玻璃钢管道厂，市政供排水与化工管道是核心市场。",
    descriptionEn:
      "Zibo FRP pipe maker primarily serving municipal water/drainage and chemical pipe markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-anhui-pul-pipe",
    name: "安徽省利达玻璃钢有限公司",
    nameEn: "Anhui Lida Fiberglass Co., Ltd.",
    location: "安徽合肥",
    locationEn: "Hefei, Anhui, China",
    province: "安徽",
    category: "manufacturer",
    products: ["玻璃钢储罐", "玻璃钢管道", "玻璃钢冷却塔"],
    productsEn: ["FRP storage tanks", "FRP pipes", "FRP cooling towers"],
    processList: ["缠绕", "手糊"],
    processListEn: ["Filament winding", "Hand layup"],
    established: 2002,
    verified: false,
    description: "安徽本地中小型玻璃钢制品厂，化工/水处理项目为主要市场。",
    descriptionEn:
      "Anhui small-mid FRP products plant primarily serving chemical and water treatment markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-henan-pultrusion-bridge",
    name: "河南通达电缆股份有限公司复材桥架业务",
    nameEn: "Henan Tongda Cable — Composite Cable Tray Business",
    location: "河南许昌",
    locationEn: "Xuchang, Henan, China",
    province: "河南",
    category: "manufacturer",
    products: ["FRP 电缆桥架", "拉挤电缆支架"],
    productsEn: ["FRP cable trays", "Pultruded cable supports"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 1999,
    verified: false,
    description: "河南通达电缆复材桥架事业部，国内电力与轨道交通项目配套较多。",
    descriptionEn:
      "Composite cable tray division of Henan Tongda Cable, supplying power and rail transit projects domestically.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-henan-frp-rebar",
    name: "河南天力复合材料股份有限公司",
    nameEn: "Henan Tianli Composite Materials Co., Ltd.",
    location: "河南郑州",
    locationEn: "Zhengzhou, Henan, China",
    province: "河南",
    category: "manufacturer",
    products: ["GFRP 锚杆", "拉挤型材", "复合材料矿用支护"],
    productsEn: ["GFRP rock bolts", "Pultruded profiles", "Composite mining support"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2005,
    verified: false,
    description: "河南拉挤复材厂，矿用 GFRP 锚杆是其特色产品。",
    descriptionEn:
      "Henan pultrusion firm with a focus on GFRP rock bolts for mining support applications.",
    certifications: ["ISO 9001", "MA"],
    certificationsEn: ["ISO 9001", "MA"],
  },
  {
    id: "fin-guangxi-pul-bridge",
    name: "广西路桥复合材料工程有限公司",
    nameEn: "Guangxi Road & Bridge Composite Engineering Co., Ltd.",
    location: "广西南宁",
    locationEn: "Nanning, Guangxi, China",
    province: "广西",
    category: "manufacturer",
    products: ["FRP 桥梁加固材料", "拉挤型材", "复合材料防护"],
    productsEn: ["FRP bridge reinforcement", "Pultruded profiles", "Composite protective structures"],
    processList: ["拉挤", "缠绕"],
    processListEn: ["Pultrusion", "Filament winding"],
    established: 2007,
    verified: false,
    description: "广西本地路桥复材应用商，FRP 加固与基建配套是主要业务。",
    descriptionEn:
      "Guangxi composite firm focused on bridge/road FRP reinforcement and infrastructure applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shaanxi-pul-frp",
    name: "西安鸿运复合材料有限公司",
    nameEn: "Xi'an Hongyun Composite Materials Co., Ltd.",
    location: "陕西西安",
    locationEn: "Xi'an, Shaanxi, China",
    province: "陕西",
    category: "manufacturer",
    products: ["拉挤型材", "玻璃钢防护栏", "复合材料标志杆"],
    productsEn: ["Pultruded profiles", "FRP guard rails", "Composite signage poles"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2010,
    verified: false,
    description: "西安本地中小型拉挤厂，配套西北基建市场。",
    descriptionEn:
      "Mid-small Xi'an pultrusion shop supplying the northwest infrastructure market.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // I. Marine FRP / boats & offshore (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-yantai-cimc-raffles",
    name: "烟台中集来福士海洋工程有限公司",
    nameEn: "CIMC Raffles Offshore (Yantai) Co., Ltd.",
    location: "山东烟台",
    locationEn: "Yantai, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["海工平台复材构件", "海上风电导管架附件", "海工辅助装备"],
    productsEn: ["Offshore platform composite parts", "Offshore wind jacket accessories", "Offshore auxiliary equipment"],
    processList: ["真空导入", "缠绕"],
    processListEn: ["Vacuum infusion", "Filament winding"],
    established: 1977,
    verified: false,
    description: "中集集团旗下海工龙头，半潜式平台/海上风电基础结构具备复材附件配套能力。",
    descriptionEn:
      "CIMC Group's leading offshore yard. Capability for composite accessory components on semi-submersible platforms and offshore wind foundations.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
  {
    id: "fin-fuzhou-marine-frp",
    name: "福建福船(集团)复合材料船业",
    nameEn: "Fujian Fuchuan Group Composite Boat Business",
    location: "福建福州",
    locationEn: "Fuzhou, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["玻璃钢渔船", "玻璃钢工作艇", "海洋装备"],
    productsEn: ["FRP fishing boats", "FRP work boats", "Marine equipment"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 1958,
    verified: false,
    description: "福建船舶集团下属玻璃钢船业务，渔船与公务艇是主要产品。",
    descriptionEn:
      "Composite boat business of Fujian Shipbuilding Group. FRP fishing boats and government work boats are the main products.",
    certifications: ["CCS"],
    certificationsEn: ["CCS"],
  },
  {
    id: "fin-qingdao-hailieren-yacht",
    name: "青岛海猎人游艇有限公司",
    nameEn: "Qingdao Hailieren Yacht Co., Ltd.",
    location: "山东青岛",
    locationEn: "Qingdao, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["玻璃钢游艇", "玻璃钢钓鱼艇", "玻璃钢交通艇"],
    productsEn: ["FRP yachts", "FRP fishing boats", "FRP transportation boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2000,
    verified: false,
    description: "青岛本地玻璃钢游艇厂，钓鱼艇与小型游艇出口比例较高。",
    descriptionEn:
      "Qingdao FRP yacht maker with significant export share in fishing boats and small leisure yachts.",
    certifications: ["CCS", "CE"],
    certificationsEn: ["CCS", "CE"],
  },
  {
    id: "fin-guangdong-marine-frp",
    name: "广东中山福地船舶制造有限公司",
    nameEn: "Zhongshan Fudi Shipbuilding Co., Ltd.",
    location: "广东中山",
    locationEn: "Zhongshan, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["玻璃钢游艇", "玻璃钢工作艇", "钓鱼艇"],
    productsEn: ["FRP yachts", "FRP work boats", "Fishing boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2003,
    verified: false,
    description: "中山本地中型玻璃钢船厂，珠三角内贸与东南亚出口并重。",
    descriptionEn:
      "Mid-sized Zhongshan FRP yard balancing Pearl River Delta domestic and Southeast Asian export markets.",
    certifications: ["CCS", "CE"],
    certificationsEn: ["CCS", "CE"],
  },
  {
    id: "fin-hainan-marine-frp",
    name: "海南海骏船舶有限公司",
    nameEn: "Hainan Haijun Marine Co., Ltd.",
    location: "海南海口",
    locationEn: "Haikou, Hainan, China",
    province: "海南",
    category: "manufacturer",
    products: ["玻璃钢游艇", "渔船", "公务船"],
    productsEn: ["FRP yachts", "Fishing boats", "Government vessels"],
    processList: ["手糊"],
    processListEn: ["Hand layup"],
    established: 2008,
    verified: false,
    description: "海南本地玻璃钢船厂，配套南海渔业与海洋观光船需求。",
    descriptionEn:
      "Hainan FRP yard supplying South China Sea fishery and marine tourism boat demand.",
    certifications: ["CCS"],
    certificationsEn: ["CCS"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // J. Sporting goods carbon fiber (Xiamen / Shenzhen / Dongguan cluster)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-xiamen-sport-cf",
    name: "厦门精图复合材料有限公司",
    nameEn: "Xiamen Jingtu Composite Materials Co., Ltd.",
    location: "福建厦门",
    locationEn: "Xiamen, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["碳纤维自行车架", "碳纤维球拍", "碳纤维管材"],
    productsEn: ["Carbon fiber bicycle frames", "Carbon fiber rackets", "Carbon fiber tubes"],
    processList: ["热压成型", "缠绕"],
    processListEn: ["Hot-press molding", "Filament winding"],
    established: 2010,
    verified: false,
    description: "厦门本地体育用品碳纤维生产商，自行车架与球拍出口为主。",
    descriptionEn:
      "Xiamen sporting-goods carbon fiber manufacturer focused on export of bicycle frames and rackets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-quanzhou-fishrod",
    name: "晋江市三优体育用品有限公司",
    nameEn: "Jinjiang Sanyou Sporting Goods Co., Ltd.",
    location: "福建晋江",
    locationEn: "Jinjiang, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["碳纤维钓鱼竿", "碳纤维球拍", "羽毛球拍"],
    productsEn: ["Carbon fiber fishing rods", "Carbon fiber rackets", "Badminton rackets"],
    processList: ["卷管成型", "热压"],
    processListEn: ["Roll-wrap forming", "Hot-press"],
    established: 2005,
    verified: false,
    description: "晋江体育用品集群中型厂，钓竿/球拍出口至日韩欧美市场。",
    descriptionEn:
      "Mid-sized maker in Jinjiang's sporting goods cluster, exporting rods and rackets to Japan, Korea, EU, and the US.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-dongguan-cf-products",
    name: "东莞市鸿威复合材料有限公司",
    nameEn: "Dongguan Hongwei Composite Materials Co., Ltd.",
    location: "广东东莞",
    locationEn: "Dongguan, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["碳纤维消费品", "无人机机壳", "碳纤维管"],
    productsEn: ["Carbon fiber consumer goods", "Drone housings", "Carbon fiber tubes"],
    processList: ["热压", "卷管"],
    processListEn: ["Hot-press", "Tube winding"],
    established: 2012,
    verified: false,
    description: "东莞中小碳纤维消费品厂，配套无人机与电子消费品。",
    descriptionEn:
      "Dongguan small-mid carbon fiber consumer goods plant, supplying drone and electronics consumer markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shenzhen-drone-cf",
    name: "深圳市鼎泰盛复合材料有限公司",
    nameEn: "Shenzhen Dingtaisheng Composite Materials Co., Ltd.",
    location: "广东深圳",
    locationEn: "Shenzhen, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["无人机机臂", "碳纤维板材", "碳纤维定制件"],
    productsEn: ["Drone arms", "Carbon fiber plate", "Customized carbon fiber parts"],
    processList: ["热压", "CNC 加工"],
    processListEn: ["Hot-press", "CNC machining"],
    established: 2014,
    verified: false,
    description: "深圳本地碳纤维定制件厂，配套无人机/工业机器人客户。",
    descriptionEn:
      "Shenzhen carbon fiber custom parts shop serving drone and industrial robot customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // K. EV battery enclosure / automotive composites
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-byd-precision-composite",
    name: "比亚迪精密制造有限公司复合材料事业部",
    nameEn: "BYD Precision Manufacturing — Composite Division",
    location: "广东深圳",
    locationEn: "Shenzhen, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["新能源车复材车身件", "电池壳复材件", "BMC 结构件"],
    productsEn: ["EV body composite parts", "Battery enclosure composites", "BMC structural parts"],
    processList: ["SMC/BMC 模压", "RTM"],
    processListEn: ["SMC/BMC compression", "RTM"],
    established: 2010,
    verified: false,
    description: "比亚迪精密制造的复合材料事业部，承担新能源车体与电池壳复材件供应。",
    descriptionEn:
      "BYD Precision Manufacturing composite arm. Supplies EV body and battery enclosure composite components.",
    certifications: ["IATF 16949", "ISO 9001"],
    certificationsEn: ["IATF 16949", "ISO 9001"],
  },
  {
    id: "fin-ningbo-junhong-auto",
    name: "宁波君灵汽车零部件有限公司",
    nameEn: "Ningbo Junling Auto Parts Co., Ltd.",
    location: "浙江宁波",
    locationEn: "Ningbo, Zhejiang, China",
    province: "浙江",
    category: "manufacturer",
    products: ["SMC/BMC 汽车零部件", "前端模块", "尾门内板"],
    productsEn: ["SMC/BMC auto parts", "Front-end modules", "Tailgate inner panels"],
    processList: ["SMC 模压", "BMC 注塑"],
    processListEn: ["SMC compression molding", "BMC injection"],
    established: 2003,
    verified: false,
    description: "宁波本地 SMC/BMC 汽车件厂，配套国内主流主机厂。",
    descriptionEn:
      "Ningbo SMC/BMC automotive parts plant supplying mainstream Chinese OEMs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "fin-changchun-faw-composite",
    name: "一汽集团复合材料工程中心",
    nameEn: "FAW Group Composite Engineering Center",
    location: "吉林长春",
    locationEn: "Changchun, Jilin, China",
    province: "吉林",
    category: "manufacturer",
    products: ["汽车复材件研发", "电池壳轻量化", "结构件验证"],
    productsEn: ["Automotive composite R&D", "Battery enclosure lightweighting", "Structural part validation"],
    processList: ["RTM", "SMC 模压", "缠绕"],
    processListEn: ["RTM", "SMC compression", "Winding"],
    established: 2015,
    verified: false,
    description: "一汽内部复材研发与样件中心，对接红旗与解放品牌轻量化项目。",
    descriptionEn:
      "FAW internal composite R&D and prototyping center supporting Hongqi and Jiefang lightweight programs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "fin-hubei-dongfeng-composite",
    name: "东风汽车集团复合材料应用中心",
    nameEn: "Dongfeng Motor Composite Application Center",
    location: "湖北武汉",
    locationEn: "Wuhan, Hubei, China",
    province: "湖北",
    category: "manufacturer",
    products: ["车身复材件", "电池壳", "底盘复材件"],
    productsEn: ["Body composite parts", "Battery enclosures", "Chassis composite parts"],
    processList: ["RTM", "高压 SMC", "缠绕"],
    processListEn: ["RTM", "High-pressure SMC", "Winding"],
    established: 2017,
    verified: false,
    description: "东风汽车集团复材技术中心，集中支撑商用车与新能源乘用车轻量化项目。",
    descriptionEn:
      "Dongfeng's composite technology center supporting commercial-vehicle and NEV lightweighting programs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "fin-anhui-jianghuai-frp",
    name: "安徽江淮汽车股份有限公司复合材料部",
    nameEn: "Anhui JAC Motors — Composite Division",
    location: "安徽合肥",
    locationEn: "Hefei, Anhui, China",
    province: "安徽",
    category: "manufacturer",
    products: ["商用车复材车身件", "玻纤增强保险杠", "电池壳"],
    productsEn: ["Commercial vehicle body composites", "Glass-fiber bumpers", "Battery enclosures"],
    processList: ["SMC 模压", "RTM"],
    processListEn: ["SMC compression", "RTM"],
    established: 2012,
    verified: false,
    description: "江淮汽车复合材料部门，主要服务商用车整车与新能源轻量化项目。",
    descriptionEn:
      "JAC Motors' composite division supporting commercial-vehicle and NEV lightweighting programs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // L. Mold / tooling specialists (categories underrepresented)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "md-jiangsu-yongmao-mold",
    name: "江苏永茂复合材料模具有限公司",
    nameEn: "Jiangsu Yongmao Composite Mold Co., Ltd.",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "mold",
    products: ["风电叶片模具", "海上风电叶片模具", "结构件模具"],
    productsEn: ["Wind blade molds", "Offshore wind blade molds", "Structural part molds"],
    processList: ["数控加工", "蒸汽加热模"],
    processListEn: ["CNC machining", "Steam-heated molds"],
    established: 2008,
    verified: false,
    description: "盐城风电叶片模具厂，国内主要叶片厂供应商之一。",
    descriptionEn:
      "Yancheng wind blade mold maker, among the supplier base for major Chinese blade plants.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "md-shandong-haiyang-mold",
    name: "山东海洋装备复材模具有限公司",
    nameEn: "Shandong Marine Equipment Composite Mold Co., Ltd.",
    location: "山东青岛",
    locationEn: "Qingdao, Shandong, China",
    province: "山东",
    category: "mold",
    products: ["游艇模具", "海工模具", "工艺件模具"],
    productsEn: ["Yacht molds", "Marine engineering molds", "Process molds"],
    processList: ["数控加工", "钢模制造"],
    processListEn: ["CNC machining", "Steel mold fabrication"],
    established: 2012,
    verified: false,
    description: "青岛本地海工/游艇专用模具厂，配套北方游艇与海工市场。",
    descriptionEn:
      "Qingdao marine/yacht-specific mold shop serving northern China's yacht and offshore markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "md-changchun-rail-mold",
    name: "长春轨道交通复材模具有限公司",
    nameEn: "Changchun Rail Transit Composite Mold Co., Ltd.",
    location: "吉林长春",
    locationEn: "Changchun, Jilin, China",
    province: "吉林",
    category: "mold",
    products: ["高铁车头模具", "轨交内饰模具", "司机室模具"],
    productsEn: ["High-speed train head molds", "Rail interior molds", "Driver cab molds"],
    processList: ["数控加工", "组合钢模"],
    processListEn: ["CNC machining", "Composite steel molds"],
    established: 2010,
    verified: false,
    description: "依托中车长客的轨道交通用复材模具厂。",
    descriptionEn:
      "Composite mold shop attached to the CRRC Changchun rail vehicle ecosystem.",
    certifications: ["ISO 9001", "IRIS"],
    certificationsEn: ["ISO 9001", "IRIS"],
  },
  {
    id: "md-shenyang-aero-mold",
    name: "沈阳航空复材模具有限公司",
    nameEn: "Shenyang Aero Composite Mold Co., Ltd.",
    location: "辽宁沈阳",
    locationEn: "Shenyang, Liaoning, China",
    province: "辽宁",
    category: "mold",
    products: ["航空 INVAR 模具", "热压罐模具", "RTM 模具"],
    productsEn: ["Aerospace INVAR molds", "Autoclave molds", "RTM molds"],
    processList: ["数控加工", "INVAR 钢模"],
    processListEn: ["CNC machining", "INVAR steel molds"],
    established: 2012,
    verified: false,
    description: "沈阳航空模具厂，配套沈飞与中航工业 INVAR 模具需求。",
    descriptionEn:
      "Shenyang aerospace mold shop supplying INVAR mold requirements of SAC and AVIC programs.",
    certifications: ["AS9100"],
    certificationsEn: ["AS9100"],
  },
  {
    id: "tl-jiangsu-vacuum-bag",
    name: "江苏蓝光复合材料工艺辅材有限公司",
    nameEn: "Jiangsu Languang Composite Process Consumables Co., Ltd.",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "tooling",
    products: ["真空袋膜", "脱模布", "导流网"],
    productsEn: ["Vacuum bag films", "Peel ply", "Flow media"],
    processList: ["薄膜复合", "纺织品后整理"],
    processListEn: ["Film lamination", "Textile finishing"],
    established: 2010,
    verified: false,
    description: "苏州本地真空导入辅材专业厂，主要客户为风电叶片与游艇。",
    descriptionEn:
      "Suzhou specialist in vacuum infusion consumables, primarily serving wind blade and yacht customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "tl-tianjin-release-agent",
    name: "天津华仑威洁脱模剂有限公司",
    nameEn: "Tianjin Hualunwei Release Agents Co., Ltd.",
    location: "天津",
    locationEn: "Tianjin, China",
    province: "天津",
    category: "tooling",
    products: ["半永久脱模剂", "蜡基脱模剂", "封孔剂"],
    productsEn: ["Semi-permanent release agents", "Wax-based release agents", "Sealers"],
    processList: ["复配"],
    processListEn: ["Compounding"],
    established: 2008,
    verified: false,
    description: "天津本地脱模剂厂，配套北方风电叶片与游艇厂。",
    descriptionEn:
      "Tianjin release-agent maker, primarily serving northern China wind blade and yacht plants.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "tl-guangzhou-mold-prep",
    name: "广州嘉迪复合材料工艺辅材有限公司",
    nameEn: "Guangzhou Jiadi Composite Process Consumables Co., Ltd.",
    location: "广东广州",
    locationEn: "Guangzhou, Guangdong, China",
    province: "广东",
    category: "tooling",
    products: ["真空袋膜", "密封胶条", "脱模布"],
    productsEn: ["Vacuum bag films", "Tacky tape", "Peel ply"],
    processList: ["薄膜挤出", "胶条复合"],
    processListEn: ["Film extrusion", "Tape lamination"],
    established: 2011,
    verified: false,
    description: "广州本地真空袋辅材厂，配套华南游艇与拉挤厂。",
    descriptionEn:
      "Guangzhou vacuum bag consumables maker, supplying south-China yacht and pultrusion plants.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // M. Equipment makers (regional gaps + niches)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "eq-jiangsu-hejin-rtm",
    name: "江苏鸿景复合材料设备有限公司",
    nameEn: "Jiangsu Hongjing Composite Equipment Co., Ltd.",
    location: "江苏南通",
    locationEn: "Nantong, Jiangsu, China",
    province: "江苏",
    category: "equipment",
    products: ["RTM 注射机", "树脂混合机", "真空辅助设备"],
    productsEn: ["RTM injection machines", "Resin mixers", "Vacuum-assist equipment"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2009,
    verified: false,
    description: "南通本地 RTM 设备厂，国内中小批量复材厂主要供应商。",
    descriptionEn:
      "Nantong RTM equipment maker, primary supplier to mid-small Chinese composite plants.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-shandong-autoclave",
    name: "山东中复智联热压罐设备",
    nameEn: "Shandong Zhongfu Zhilian Autoclave Equipment",
    location: "山东青岛",
    locationEn: "Qingdao, Shandong, China",
    province: "山东",
    category: "equipment",
    products: ["热压罐", "真空泵组", "工艺控制系统"],
    productsEn: ["Autoclaves", "Vacuum pump groups", "Process control systems"],
    processList: ["压力容器制造"],
    processListEn: ["Pressure vessel manufacturing"],
    established: 2014,
    verified: false,
    description: "青岛本地中型热压罐设备厂，主要面向航空与轨道交通客户。",
    descriptionEn:
      "Qingdao mid-sized autoclave maker primarily serving aerospace and rail transit customers.",
    certifications: ["ASME U Stamp", "ISO 9001"],
    certificationsEn: ["ASME U Stamp", "ISO 9001"],
  },
  {
    id: "eq-changzhou-pul-line",
    name: "常州精拓复合材料设备有限公司",
    nameEn: "Changzhou Jingtuo Composite Equipment Co., Ltd.",
    location: "江苏常州",
    locationEn: "Changzhou, Jiangsu, China",
    province: "江苏",
    category: "equipment",
    products: ["拉挤生产线", "拉挤模具", "牵引机"],
    productsEn: ["Pultrusion lines", "Pultrusion dies", "Pulling machines"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2007,
    verified: false,
    description: "常州拉挤设备聚集地的代表厂，供应国内拉挤型材厂整线设备。",
    descriptionEn:
      "Representative pultrusion equipment maker in Changzhou's cluster, supplying full-line equipment to domestic pultrusion plants.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-shenzhen-cnc-cf",
    name: "深圳市麦科技复材数控设备有限公司",
    nameEn: "Shenzhen Maike Composite CNC Equipment Co., Ltd.",
    location: "广东深圳",
    locationEn: "Shenzhen, Guangdong, China",
    province: "广东",
    category: "equipment",
    products: ["复材专用 CNC", "超声切割机", "水切割机"],
    productsEn: ["Composite-specific CNC", "Ultrasonic cutting machines", "Waterjet machines"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2013,
    verified: false,
    description: "深圳本地复材数控加工设备厂，配套华南消费电子复材件加工。",
    descriptionEn:
      "Shenzhen composite CNC machine maker primarily supplying south-China consumer electronics composite parts processors.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-shanghai-prepreg-line",
    name: "上海舒福新材料工艺装备有限公司",
    nameEn: "Shanghai Shufu Composite Process Equipment Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "equipment",
    products: ["预浸料生产线", "热熔预浸机", "复合涂布机"],
    productsEn: ["Prepreg lines", "Hot-melt prepreg machines", "Composite coaters"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2010,
    verified: false,
    description: "上海本地预浸料生产线设备厂，碳纤维与玻璃纤维预浸客户均有覆盖。",
    descriptionEn:
      "Shanghai prepreg line maker covering both carbon and glass fiber prepreg customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // N. Niche additives & sandwich cores (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "ad-shandong-tonghui-coupling",
    name: "山东通汇粘合剂股份有限公司",
    nameEn: "Shandong Tonghui Adhesive Co., Ltd.",
    location: "山东淄博",
    locationEn: "Zibo, Shandong, China",
    province: "山东",
    category: "additive",
    products: ["硅烷偶联剂", "硬脂酸盐", "助剂复配"],
    productsEn: ["Silane coupling agents", "Stearate additives", "Additive compounding"],
    processList: ["合成", "复配"],
    processListEn: ["Synthesis", "Compounding"],
    established: 2003,
    verified: false,
    description: "山东本地硅烷偶联剂供应商，玻纤浸润剂与复材界面配方常用品牌。",
    descriptionEn:
      "Shandong silane coupling agent supplier; commonly used in glass-fiber sizing and composite interface formulations.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-jiangsu-yade-flame",
    name: "江苏雅克科技股份有限公司",
    nameEn: "Jiangsu Yoke Technology Co., Ltd.",
    location: "江苏张家港",
    locationEn: "Zhangjiagang, Jiangsu, China",
    province: "江苏",
    category: "additive",
    products: ["磷系阻燃剂", "复合阻燃剂", "电子化学品"],
    productsEn: ["Phosphorus flame retardants", "Composite flame retardants", "Electronic chemicals"],
    processList: ["合成", "复配"],
    processListEn: ["Synthesis", "Compounding"],
    established: 1997,
    verified: false,
    description: "国内磷系阻燃剂代表企业，复材与电子化学品并重，A 股上市。",
    descriptionEn:
      "Major Chinese phosphorus flame retardant supplier serving composites and electronic chemicals markets. A-share listed.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-balsa-zhejiang",
    name: "浙江欧亚轻木业有限公司",
    nameEn: "Zhejiang Ouya Balsa Wood Co., Ltd.",
    location: "浙江德清",
    locationEn: "Deqing, Zhejiang, China",
    province: "浙江",
    category: "additive",
    products: ["巴沙木夹芯", "PVC 泡沫芯材", "PET 泡沫芯材"],
    productsEn: ["Balsa wood cores", "PVC foam cores", "PET foam cores"],
    processList: ["切削加工", "拼接"],
    processListEn: ["Cutting", "Splicing"],
    established: 2011,
    verified: false,
    description: "浙江本地夹芯材料供应商，巴沙木与发泡 PET/PVC 主要面向风电叶片与游艇。",
    descriptionEn:
      "Zhejiang sandwich core supplier with balsa and foam PET/PVC products serving wind blade and yacht customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-shandong-foam-core",
    name: "山东海科创新研究院发泡 PET",
    nameEn: "Shandong Hike Innovation Institute — Foam PET Division",
    location: "山东淄博",
    locationEn: "Zibo, Shandong, China",
    province: "山东",
    category: "additive",
    products: ["PET 结构泡沫", "PMI 结构泡沫", "夹芯板"],
    productsEn: ["PET structural foam", "PMI structural foam", "Sandwich panels"],
    processList: ["发泡成型"],
    processListEn: ["Foam extrusion"],
    established: 2015,
    verified: false,
    description: "山东海科旗下结构泡沫研究机构，国内 PET 与 PMI 泡沫的主要替代供应方之一。",
    descriptionEn:
      "Shandong Hike's structural foam unit; among the alternative domestic suppliers of PET and PMI structural foams.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-jiangsu-pmi-foam",
    name: "江苏兆鋆新材料股份有限公司",
    nameEn: "Jiangsu Zhaoyun New Material Co., Ltd.",
    location: "江苏常州",
    locationEn: "Changzhou, Jiangsu, China",
    province: "江苏",
    category: "additive",
    products: ["PMI 结构泡沫", "蜂窝芯材", "夹芯板"],
    productsEn: ["PMI structural foam", "Honeycomb cores", "Sandwich panels"],
    processList: ["发泡", "复合"],
    processListEn: ["Foaming", "Lamination"],
    established: 2010,
    verified: false,
    description: "江苏 PMI 泡沫代表企业，对标 Rohacell 国产替代方案。",
    descriptionEn:
      "Major Chinese PMI foam producer, positioned as a domestic alternative to Rohacell.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // O. Aramid / specialty fibers (regional)
  // ═══════════════════════════════════════════════════════════════════════
{
    id: "af-sichuan-shenma",
    name: "四川辉腾化工有限公司",
    nameEn: "Sichuan Huiteng Chemical Co., Ltd.",
    location: "四川成都",
    locationEn: "Chengdu, Sichuan, China",
    province: "四川",
    category: "fiber",
    products: ["芳纶上浆剂", "芳纶预浸料", "芳纶布"],
    productsEn: ["Aramid sizing agents", "Aramid prepreg", "Aramid fabric"],
    processList: ["浸润", "纺织"],
    processListEn: ["Sizing", "Weaving"],
    established: 2009,
    verified: false,
    description: "成都本地芳纶下游加工厂，预浸料与布材主要面向防弹与海工市场。",
    descriptionEn:
      "Chengdu aramid downstream processor; prepreg and fabric serving ballistic and marine markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "af-uhmwpe-zhejiang",
    name: "浙江千禧龙超高分子量聚乙烯纤维有限公司",
    nameEn: "Zhejiang Qianxilong UHMWPE Fiber Co., Ltd.",
    location: "浙江绍兴",
    locationEn: "Shaoxing, Zhejiang, China",
    province: "浙江",
    category: "fiber",
    products: ["UHMWPE 纤维", "防弹布", "高强绳缆"],
    productsEn: ["UHMWPE fibers", "Ballistic fabric", "High-strength ropes"],
    processList: ["凝胶纺丝"],
    processListEn: ["Gel spinning"],
    established: 2003,
    verified: false,
    description: "浙江超高分子量聚乙烯纤维生产商，对标 Dyneema/Spectra。",
    descriptionEn:
      "Zhejiang UHMWPE fiber producer; positioned as Dyneema/Spectra-class domestic alternative.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // P. Wind blade clusters (provincial extras)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-jiangsu-windblade-yancheng",
    name: "金风科技盐城叶片工厂",
    nameEn: "Goldwind Yancheng Blade Factory",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["陆上风电叶片", "海上风电叶片"],
    productsEn: ["Onshore wind blades", "Offshore wind blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2018,
    verified: false,
    description: "金风科技盐城叶片基地，主供华东陆上与海上风电项目。",
    descriptionEn:
      "Goldwind's Yancheng blade base, supplying onshore and offshore projects in east China.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
  {
    id: "fin-fujian-windblade-fuqing",
    name: "三峡集团福清海上风电叶片配套",
    nameEn: "CTG Fuqing Offshore Wind Blade Supply",
    location: "福建福清",
    locationEn: "Fuqing, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["大兆瓦海上叶片", "海上风电模块"],
    productsEn: ["Large-MW offshore blades", "Offshore wind modules"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2019,
    verified: false,
    description: "三峡集团福清海上风电基地的叶片厂配套区，承接福建近海项目。",
    descriptionEn:
      "Blade supply zone of CTG's Fuqing offshore wind base, supporting Fujian near-shore projects.",
    certifications: ["DNV", "ISO 9001"],
    certificationsEn: ["DNV", "ISO 9001"],
  },
  {
    id: "fin-guangdong-windblade-yangjiang",
    name: "明阳智能阳江海上风电叶片基地",
    nameEn: "Mingyang Smart Energy Yangjiang Offshore Blade Base",
    location: "广东阳江",
    locationEn: "Yangjiang, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["大兆瓦海上风电叶片", "漂浮式风电叶片"],
    productsEn: ["Large-MW offshore wind blades", "Floating wind blades"],
    processList: ["真空导入", "拉挤主梁"],
    processListEn: ["Vacuum infusion", "Pultruded spar caps"],
    established: 2017,
    verified: false,
    description: "明阳智能阳江基地，海上风电叶片主力工厂之一。",
    descriptionEn:
      "Mingyang's Yangjiang base — one of the main production sites for offshore wind blades.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
];

async function main() {
  console.log(`Seeding ${entries.length} v3 supply-chain entries…`);
  let inserted = 0;
  let updated = 0;

  for (const e of entries) {
    const existing = await db.query.supplierListings?.findFirst?.({
      where: (t, { eq }) => eq(t.id, e.id),
    });
    await db
      .insert(supplierListings)
      .values(e)
      .onConflictDoUpdate({
        target: supplierListings.id,
        set: { ...e, updatedAt: new Date() },
      });
    if (existing) updated++;
    else inserted++;
    console.log(`  ✓ ${e.id}  ${e.nameEn}`);
  }

  console.log(`\nv3 seed complete. inserted=${inserted}  updated=${updated}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
