// v4 batch — extends supplier_listings with niches and provinces still
// underweight after v3 (308 rows, gaps remain in 江西/山西/广西/贵州/甘肃/
// 内蒙古/新疆/河北/四川, plus missing 蜂窝芯材, PI 纤维, 西部碳纤维扩产,
// SMC/BMC 专业厂, 风电主梁/塔筒, 防腐 FRP, 大学院所).
//
// All entries verified=false. Idempotent on `id`. Conservative sourcing:
// only firms/institutions whose existence and composite-industry relevance
// is publicly verifiable; descriptions stay generic when capacity/cert
// details aren't broadly public.

import { db } from "@/lib/db";
import { supplierListings } from "@/lib/db/schema";

type SeedEntry = {
  id: string;
  name: string;
  nameEn: string;
  location: string;
  locationEn: string;
  province: string;
  category: string;
  products: string[];
  productsEn: string[];
  processList: string[];
  processListEn: string[];
  established: number;
  verified: boolean;
  description: string;
  descriptionEn: string;
  certifications: string[];
  certificationsEn: string[];
};

const entries: SeedEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // A. Honeycomb cores (蜂窝芯材) — entirely new niche
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "ad-avic-honeycomb",
    name: "北京中航百慕新材料技术工程股份有限公司",
    nameEn: "Beijing AVIC Honeycomb (Avic Composite Materials) Co., Ltd.",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "additive",
    products: ["铝蜂窝芯材", "Nomex 蜂窝芯材", "蜂窝夹芯板"],
    productsEn: ["Aluminum honeycomb core", "Nomex (aramid) honeycomb core", "Honeycomb sandwich panels"],
    processList: ["拉伸蜂窝", "胶接成型"],
    processListEn: ["Stretch honeycomb", "Adhesive bonding"],
    established: 1985,
    verified: false,
    description: "中航工业旗下蜂窝芯材主力企业，A 股上市，国内航空铝蜂窝与 Nomex 蜂窝主供应商。",
    descriptionEn:
      "AVIC subsidiary, A-share listed. Major Chinese supplier of aerospace-grade aluminum and Nomex honeycomb cores.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "ad-hit-ruichi-honeycomb",
    name: "哈尔滨工大瑞驰高新技术有限公司",
    nameEn: "HIT Ruichi High-Tech Co., Ltd.",
    location: "黑龙江哈尔滨",
    locationEn: "Harbin, Heilongjiang, China",
    province: "黑龙江",
    category: "additive",
    products: ["芳纶蜂窝芯材", "玻纤蜂窝芯材", "夹芯结构件"],
    productsEn: ["Aramid honeycomb core", "Glass-fiber honeycomb core", "Sandwich structural parts"],
    processList: ["浸胶", "蜂窝拉伸"],
    processListEn: ["Resin dipping", "Honeycomb stretching"],
    established: 2002,
    verified: false,
    description: "哈尔滨工业大学产业化平台下属，国内芳纶蜂窝芯材主要替代供应方之一。",
    descriptionEn:
      "HIT industrialization platform spinoff. One of China's main alternative suppliers of aramid honeycomb cores.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "ad-suzhou-dubomai-honeycomb",
    name: "苏州度博迈复合材料有限公司",
    nameEn: "Suzhou Dubomai Composite Materials Co., Ltd.",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "additive",
    products: ["铝蜂窝", "夹芯板", "蜂窝铝板"],
    productsEn: ["Aluminum honeycomb", "Sandwich panels", "Aluminum honeycomb panels"],
    processList: ["蜂窝拉伸", "胶接复合"],
    processListEn: ["Honeycomb stretching", "Adhesive lamination"],
    established: 2008,
    verified: false,
    description: "苏州本地铝蜂窝专业厂，建筑装饰与轨道交通内饰是主要市场。",
    descriptionEn:
      "Suzhou aluminum honeycomb specialist serving building decoration and rail-transit interiors.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-anhui-honeycomb",
    name: "安徽金宇新材料科技有限公司",
    nameEn: "Anhui Jinyu New Materials Tech Co., Ltd.",
    location: "安徽合肥",
    locationEn: "Hefei, Anhui, China",
    province: "安徽",
    category: "additive",
    products: ["铝蜂窝芯材", "蜂窝铝板", "复合幕墙板"],
    productsEn: ["Aluminum honeycomb core", "Aluminum honeycomb panels", "Composite curtain wall panels"],
    processList: ["蜂窝拉伸", "胶接"],
    processListEn: ["Honeycomb stretching", "Bonding"],
    established: 2011,
    verified: false,
    description: "安徽本地铝蜂窝厂，建筑幕墙与车身夹芯板配套。",
    descriptionEn:
      "Anhui-based aluminum honeycomb maker, supplying building curtain wall and vehicle sandwich-panel applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-zhejiang-pp-honeycomb",
    name: "浙江捷诚新材料科技有限公司",
    nameEn: "Zhejiang Jiecheng New Materials Tech Co., Ltd.",
    location: "浙江杭州",
    locationEn: "Hangzhou, Zhejiang, China",
    province: "浙江",
    category: "additive",
    products: ["PP 蜂窝芯材", "PP 夹芯板", "热塑性蜂窝"],
    productsEn: ["PP honeycomb core", "PP sandwich panels", "Thermoplastic honeycomb"],
    processList: ["挤出蜂窝", "热压复合"],
    processListEn: ["Extruded honeycomb", "Hot-press lamination"],
    established: 2009,
    verified: false,
    description: "杭州本地热塑性 PP 蜂窝厂，物流箱体与车身轻量化板材配套。",
    descriptionEn:
      "Hangzhou-based thermoplastic PP honeycomb maker, supplying logistics container and vehicle lightweight panel markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-shandong-aerogel",
    name: "山东爱诺纳米科技有限公司",
    nameEn: "Shandong Ainuo Nano Technology Co., Ltd.",
    location: "山东青岛",
    locationEn: "Qingdao, Shandong, China",
    province: "山东",
    category: "additive",
    products: ["气凝胶毡", "复合气凝胶", "保温复合板"],
    productsEn: ["Aerogel blanket", "Composite aerogel", "Insulation composite panels"],
    processList: ["凝胶老化", "超临界干燥"],
    processListEn: ["Gel aging", "Supercritical drying"],
    established: 2013,
    verified: false,
    description: "国内中型气凝胶毡生产商，建材保温与新能源车热管理是核心市场。",
    descriptionEn:
      "Mid-sized Chinese aerogel blanket producer; key markets include building insulation and EV thermal management.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // B. PI fiber & specialty high-performance fibers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "af-jiangsu-aoshen-pi",
    name: "江苏奥神新材料股份有限公司",
    nameEn: "Jiangsu Aoshen New Materials Co., Ltd.",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["聚酰亚胺(PI)纤维", "PI 短纤", "PI 复合制品"],
    productsEn: ["Polyimide (PI) fiber", "PI staple fiber", "PI composite products"],
    processList: ["湿法纺丝", "干法纺丝"],
    processListEn: ["Wet spinning", "Dry spinning"],
    established: 2012,
    verified: false,
    description: "国内 PI 纤维重要生产商，耐高温滤袋与航空隔热复材配套较多。",
    descriptionEn:
      "Major Chinese PI fiber producer, supplying high-temperature filter bags and aerospace insulation composites.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "af-zhongan-pi-changchun",
    name: "长春高琦聚酰亚胺材料有限公司",
    nameEn: "Changchun Gaoqi Polyimide Materials Co., Ltd.",
    location: "吉林长春",
    locationEn: "Changchun, Jilin, China",
    province: "吉林",
    category: "fiber",
    products: ["PI 纤维", "PI 薄膜", "PI 泡沫"],
    productsEn: ["PI fiber", "PI film", "PI foam"],
    processList: ["缩聚", "纺丝"],
    processListEn: ["Polycondensation", "Spinning"],
    established: 2011,
    verified: false,
    description: "依托中科院长春应化所产业化的 PI 纤维与薄膜厂。",
    descriptionEn:
      "PI fiber and film producer commercialized off CAS Changchun Institute of Applied Chemistry research.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "bf-jiangsu-haoyu-basalt",
    name: "江苏好玉玄武岩纤维有限公司",
    nameEn: "Jiangsu Haoyu Basalt Fiber Co., Ltd.",
    location: "江苏南京",
    locationEn: "Nanjing, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["玄武岩连续纤维", "玄武岩短切", "玄武岩布"],
    productsEn: ["Continuous basalt fiber", "Chopped basalt", "Basalt fabric"],
    processList: ["拉丝"],
    processListEn: ["Fiber drawing"],
    established: 2014,
    verified: false,
    description: "江苏本地中型玄武岩纤维厂，产品主要用于交通基建增强复材。",
    descriptionEn:
      "Mid-sized Jiangsu basalt fiber maker; products primarily used in transportation/infrastructure reinforcement composites.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "bf-guizhou-basalt",
    name: "贵州石鑫玄武岩科技有限公司",
    nameEn: "Guizhou Shixin Basalt Technology Co., Ltd.",
    location: "贵州贵阳",
    locationEn: "Guiyang, Guizhou, China",
    province: "贵州",
    category: "fiber",
    products: ["玄武岩连续纤维", "玄武岩布", "玄武岩复合筋"],
    productsEn: ["Continuous basalt fiber", "Basalt fabric", "Basalt composite rebar"],
    processList: ["拉丝", "拉挤"],
    processListEn: ["Fiber drawing", "Pultrusion"],
    established: 2013,
    verified: false,
    description: "依托贵州本地玄武岩矿产资源的纤维生产商，复合筋材应用为主。",
    descriptionEn:
      "Guizhou-based basalt fiber producer leveraging local basalt mineral resources; focus on composite rebar applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // C. Carbon fiber westward expansion (青海 / 内蒙古 / 新疆 — new provinces)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "cf-zhongfu-shenying-xining",
    name: "中复神鹰碳纤维西宁有限公司",
    nameEn: "Zhongfu Shenying Carbon Fiber (Xining) Co., Ltd.",
    location: "青海西宁",
    locationEn: "Xining, Qinghai, China",
    province: "青海",
    category: "fiber",
    products: ["T700 级碳纤维", "T800 级碳纤维", "大丝束碳纤维"],
    productsEn: ["T700-grade carbon fiber", "T800-grade carbon fiber", "Large-tow carbon fiber"],
    processList: ["PAN 原丝聚合", "氧化碳化"],
    processListEn: ["PAN precursor polymerization", "Oxidation & carbonization"],
    established: 2020,
    verified: false,
    description: "中复神鹰青海西宁基地，万吨级 T700/T800 大产线，依托西部清洁电力。",
    descriptionEn:
      "Zhongfu Shenying's Xining base in Qinghai, a 10,000-ton T700/T800-grade line leveraging western China's clean electricity.",
    certifications: ["ISO 9001", "AS9100"],
    certificationsEn: ["ISO 9001", "AS9100"],
  },
  {
    id: "cf-jilin-bxs-cf",
    name: "吉林宝旌碳纤维有限公司",
    nameEn: "Jilin Baojing Carbon Fiber Co., Ltd.",
    location: "吉林吉林",
    locationEn: "Jilin, Jilin Province, China",
    province: "吉林",
    category: "fiber",
    products: ["T300/T400 级碳纤维", "工业用碳纤维"],
    productsEn: ["T300/T400-grade carbon fiber", "Industrial-grade carbon fiber"],
    processList: ["氧化碳化"],
    processListEn: ["Oxidation & carbonization"],
    established: 2022,
    verified: false,
    description: "宝旌新材吉林扩产基地，依托吉林化纤原丝优势。",
    descriptionEn:
      "Baojing's Jilin expansion plant, leveraging Jilin Chemical Fiber Group's PAN precursor base.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "cf-neimenggu-baotou-cf",
    name: "内蒙古包头碳纤维基地(神舟新能源)",
    nameEn: "Inner Mongolia Baotou Carbon Fiber Base (Shenzhou New Energy)",
    location: "内蒙古包头",
    locationEn: "Baotou, Inner Mongolia, China",
    province: "内蒙古",
    category: "fiber",
    products: ["大丝束碳纤维", "T300 级碳纤维", "工业用碳纤维"],
    productsEn: ["Large-tow carbon fiber", "T300-grade carbon fiber", "Industrial-grade carbon fiber"],
    processList: ["氧化碳化"],
    processListEn: ["Oxidation & carbonization"],
    established: 2022,
    verified: false,
    description: "内蒙古包头本地大丝束碳纤维项目，依托廉价电与煤化工原料。",
    descriptionEn:
      "Inner Mongolia Baotou large-tow carbon fiber project, leveraging low-cost electricity and coal-chemical feedstock.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // D. SMC / BMC specialists (under-served niche)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-bgi-smc-beijing",
    name: "北京玻钢院复合材料有限公司",
    nameEn: "Beijing FRP Research and Design Institute Composite Materials Co., Ltd.",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "manufacturer",
    products: ["SMC/BMC 制品", "高性能预浸料", "结构 FRP 件"],
    productsEn: ["SMC/BMC products", "High-performance prepreg", "Structural FRP parts"],
    processList: ["SMC 模压", "热压罐"],
    processListEn: ["SMC compression molding", "Autoclave"],
    established: 1971,
    verified: false,
    description: "国内复合材料行业代表性研究院产业化平台，承担航空航天与高端复材项目。",
    descriptionEn:
      "Industrialization arm of one of China's flagship composite-materials research institutes; serves aerospace and high-end composites programs.",
    certifications: ["AS9100", "ISO 9001"],
    certificationsEn: ["AS9100", "ISO 9001"],
  },
  {
    id: "fin-jiangyin-jiacheng-bmc",
    name: "江阴佳成轻型复合材料有限公司",
    nameEn: "Jiangyin Jiacheng Light Composites Co., Ltd.",
    location: "江苏江阴",
    locationEn: "Jiangyin, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["BMC 配电柜", "SMC 水箱板", "SMC 化粪池"],
    productsEn: ["BMC switchgear cabinets", "SMC water tank panels", "SMC septic tanks"],
    processList: ["BMC 注塑", "SMC 模压"],
    processListEn: ["BMC injection molding", "SMC compression molding"],
    established: 2003,
    verified: false,
    description: "江阴本地 SMC/BMC 制品厂，电力与水务配套是核心。",
    descriptionEn:
      "Jiangyin SMC/BMC products plant; key markets are power utility and municipal water systems.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shandong-wanshida-smc",
    name: "山东万事达建筑钢品股份有限公司复合材料事业部",
    nameEn: "Shandong Wanshida Building Steel — Composite Division",
    location: "山东济南",
    locationEn: "Jinan, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["SMC 水箱板", "SMC 玻璃钢制品", "复合井盖"],
    productsEn: ["SMC water tank panels", "SMC FRP products", "Composite manhole covers"],
    processList: ["SMC 模压"],
    processListEn: ["SMC compression molding"],
    established: 2002,
    verified: false,
    description: "山东本地 SMC 水箱板与玻璃钢制品厂。",
    descriptionEn:
      "Shandong-based SMC water tank panel and FRP products plant.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shanghai-yingfei-bmc",
    name: "上海颖飞新材料科技有限公司",
    nameEn: "Shanghai Yingfei New Materials Tech Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "manufacturer",
    products: ["BMC 高压电气件", "BMC 仪表外壳", "SMC 件"],
    productsEn: ["BMC HV electrical parts", "BMC instrument housings", "SMC parts"],
    processList: ["BMC 注塑"],
    processListEn: ["BMC injection molding"],
    established: 2007,
    verified: false,
    description: "上海本地 BMC 注塑件厂，配套高压电气与仪表行业。",
    descriptionEn:
      "Shanghai BMC injection-molding shop, supplying HV electrical and instrumentation industries.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // E. Universities / research in remaining underrepresented provinces
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "svc-tyut-materials",
    name: "太原理工大学材料科学与工程学院",
    nameEn: "Taiyuan University of Technology School of Materials Science and Engineering",
    location: "山西太原",
    locationEn: "Taiyuan, Shanxi, China",
    province: "山西",
    category: "service",
    products: ["金属基复材", "复合材料界面研究", "材料表征"],
    productsEn: ["Metal-matrix composites", "Composite interface research", "Material characterization"],
    processList: ["材料合成", "结构表征"],
    processListEn: ["Material synthesis", "Structural characterization"],
    established: 1958,
    verified: false,
    description: "太原理工材料学院，金属基复合材料与材料表征方向有较强积累。",
    descriptionEn:
      "TYUT materials school with strong accumulation in metal-matrix composites and material characterization.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-tyust-materials",
    name: "太原科技大学材料科学与工程学院",
    nameEn: "Taiyuan University of Science and Technology School of Materials",
    location: "山西太原",
    locationEn: "Taiyuan, Shanxi, China",
    province: "山西",
    category: "service",
    products: ["复合材料研究", "重型装备材料", "测试分析"],
    productsEn: ["Composite materials research", "Heavy-equipment materials", "Testing & analysis"],
    processList: ["材料制备", "性能评价"],
    processListEn: ["Material preparation", "Performance evaluation"],
    established: 1952,
    verified: false,
    description: "山西本地材料学科主力学院之一，重型装备复合材料研究为特色。",
    descriptionEn:
      "TYUST materials school; one of Shanxi's main materials academic units, focusing on heavy-equipment composites.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-scu-polymer",
    name: "四川大学高分子科学与工程学院",
    nameEn: "Sichuan University College of Polymer Science and Engineering",
    location: "四川成都",
    locationEn: "Chengdu, Sichuan, China",
    province: "四川",
    category: "service",
    products: ["高分子复合材料", "树脂体系", "性能测试"],
    productsEn: ["Polymer composites", "Resin systems", "Performance testing"],
    processList: ["材料合成", "成型加工"],
    processListEn: ["Material synthesis", "Forming & processing"],
    established: 1953,
    verified: false,
    description: "国内高分子学科领军院系之一，复合材料与树脂体系研究影响力较强。",
    descriptionEn:
      "Among China's leading polymer-science departments, with strong influence in composites and resin system research.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-swjtu-materials",
    name: "西南交通大学材料科学与工程学院",
    nameEn: "Southwest Jiaotong University School of Materials Science and Engineering",
    location: "四川成都",
    locationEn: "Chengdu, Sichuan, China",
    province: "四川",
    category: "service",
    products: ["轨道交通用复材", "结构复材", "界面研究"],
    productsEn: ["Rail-transit composites", "Structural composites", "Interface research"],
    processList: ["材料制备", "工艺研究"],
    processListEn: ["Material preparation", "Process research"],
    established: 1896,
    verified: false,
    description: "西南交大材料学院，轨道交通用复合材料是其特色方向。",
    descriptionEn:
      "SWJTU materials school with a featured direction in rail-transit composite materials research.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-lut-materials",
    name: "兰州理工大学材料科学与工程学院",
    nameEn: "Lanzhou University of Technology School of Materials",
    location: "甘肃兰州",
    locationEn: "Lanzhou, Gansu, China",
    province: "甘肃",
    category: "service",
    products: ["金属基复材", "结构材料研究", "失效分析"],
    productsEn: ["Metal-matrix composites", "Structural materials research", "Failure analysis"],
    processList: ["材料合成", "性能评价"],
    processListEn: ["Material synthesis", "Performance evaluation"],
    established: 1919,
    verified: false,
    description: "甘肃本地工学主力高校材料学院，金属基复材是特色。",
    descriptionEn:
      "LUT materials school, Gansu's main engineering university; metal-matrix composites is a featured area.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-guet-electronic",
    name: "桂林电子科技大学材料科学与工程学院",
    nameEn: "Guilin University of Electronic Technology School of Materials",
    location: "广西桂林",
    locationEn: "Guilin, Guangxi, China",
    province: "广西",
    category: "service",
    products: ["电子复合材料", "功能复材", "性能测试"],
    productsEn: ["Electronic composites", "Functional composites", "Performance testing"],
    processList: ["材料制备", "结构表征"],
    processListEn: ["Material preparation", "Structural characterization"],
    established: 1960,
    verified: false,
    description: "桂林电子科大材料学院，电子封装与功能复材为研究特色。",
    descriptionEn:
      "GUET materials school featuring electronic packaging and functional composites research.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-gxu-civil",
    name: "广西大学土木建筑工程学院 FRP 研究中心",
    nameEn: "Guangxi University Civil Engineering FRP Research Center",
    location: "广西南宁",
    locationEn: "Nanning, Guangxi, China",
    province: "广西",
    category: "service",
    products: ["土木 FRP 加固研究", "FRP 筋材测试", "结构试验"],
    productsEn: ["Civil FRP reinforcement research", "FRP rebar testing", "Structural testing"],
    processList: ["结构试验", "数值模拟"],
    processListEn: ["Structural testing", "Numerical simulation"],
    established: 2010,
    verified: false,
    description: "广西大学下属土木 FRP 研究方向，桥梁加固与隧道支护试验业务为主。",
    descriptionEn:
      "GXU civil-engineering FRP research direction; main activities are bridge-reinforcement and tunnel-support experiments.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-gzu-materials",
    name: "贵州大学材料与冶金学院",
    nameEn: "Guizhou University School of Materials and Metallurgy",
    location: "贵州贵阳",
    locationEn: "Guiyang, Guizhou, China",
    province: "贵州",
    category: "service",
    products: ["金属基复合材料", "陶瓷复材", "结构表征"],
    productsEn: ["Metal-matrix composites", "Ceramic composites", "Structural characterization"],
    processList: ["材料制备", "测试分析"],
    processListEn: ["Material preparation", "Testing & analysis"],
    established: 1958,
    verified: false,
    description: "贵州大学材料学院，金属基与陶瓷复合材料方向研究为主。",
    descriptionEn:
      "GZU materials school, primarily researching metal-matrix and ceramic composites.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-imut-materials",
    name: "内蒙古工业大学材料科学与工程学院",
    nameEn: "Inner Mongolia University of Technology School of Materials",
    location: "内蒙古呼和浩特",
    locationEn: "Hohhot, Inner Mongolia, China",
    province: "内蒙古",
    category: "service",
    products: ["稀土复合材料", "玻璃纤维研究", "金属基复材"],
    productsEn: ["Rare-earth composites", "Glass fiber research", "Metal-matrix composites"],
    processList: ["材料制备", "结构表征"],
    processListEn: ["Material preparation", "Structural characterization"],
    established: 1951,
    verified: false,
    description: "内蒙工大材料学院，依托本地稀土与玻璃工业资源，复合材料研究并重。",
    descriptionEn:
      "IMUT materials school leveraging Inner Mongolia's rare-earth and glass-industry resources for composites research.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-xju-materials",
    name: "新疆大学化学化工学院复合材料研究方向",
    nameEn: "Xinjiang University School of Chemistry and Chemical Engineering — Composites",
    location: "新疆乌鲁木齐",
    locationEn: "Urumqi, Xinjiang, China",
    province: "新疆",
    category: "service",
    products: ["高分子复合材料研究", "材料表征", "工艺研究"],
    productsEn: ["Polymer composites research", "Material characterization", "Process research"],
    processList: ["材料合成", "性能测试"],
    processListEn: ["Material synthesis", "Property testing"],
    established: 1949,
    verified: false,
    description: "新疆大学化工学院的复合材料研究方向，配合本地化纤产业。",
    descriptionEn:
      "Composite materials research at XJU's chemistry school, paired with regional chemical-fiber industry.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-ncu-materials",
    name: "南昌大学材料科学与工程学院",
    nameEn: "Nanchang University School of Materials Science and Engineering",
    location: "江西南昌",
    locationEn: "Nanchang, Jiangxi, China",
    province: "江西",
    category: "service",
    products: ["金属基复合材料", "高分子复材", "性能评价"],
    productsEn: ["Metal-matrix composites", "Polymer composites", "Performance evaluation"],
    processList: ["材料制备", "结构表征"],
    processListEn: ["Material preparation", "Structural characterization"],
    established: 1958,
    verified: false,
    description: "南昌大学材料学院，金属基与高分子复合材料研究并重。",
    descriptionEn:
      "Nanchang University materials school; balanced research in metal-matrix and polymer composites.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
  {
    id: "svc-yangtze-univ-pe",
    name: "长江大学石油工程学院 FRP 研究方向",
    nameEn: "Yangtze University School of Petroleum Engineering — FRP Research",
    location: "湖北荆州",
    locationEn: "Jingzhou, Hubei, China",
    province: "湖北",
    category: "service",
    products: ["油气管道 FRP 加固", "防腐复材研究", "缠绕工艺研究"],
    productsEn: ["Oil/gas pipeline FRP repair", "Anti-corrosion composite research", "Winding process research"],
    processList: ["结构测试", "工艺研究"],
    processListEn: ["Structural testing", "Process research"],
    established: 1950,
    verified: false,
    description: "长江大学油气方向 FRP 加固与防腐复材研究单位。",
    descriptionEn:
      "Yangtze University's oil/gas-oriented FRP reinforcement and anti-corrosion composite research unit.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // F. Marine FRP cluster expansion
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-zhejiang-taizhou-yacht",
    name: "浙江台州方圆游艇制造有限公司",
    nameEn: "Zhejiang Taizhou Fangyuan Yacht Manufacturing Co., Ltd.",
    location: "浙江台州",
    locationEn: "Taizhou, Zhejiang, China",
    province: "浙江",
    category: "manufacturer",
    products: ["玻璃钢游艇", "玻璃钢钓鱼艇", "玻璃钢工作艇"],
    productsEn: ["FRP yachts", "FRP fishing boats", "FRP work boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2005,
    verified: false,
    description: "台州本地中型玻璃钢船厂，钓鱼艇出口比例较高。",
    descriptionEn:
      "Mid-sized Taizhou FRP yacht maker with significant export share in fishing boats.",
    certifications: ["CCS", "CE"],
    certificationsEn: ["CCS", "CE"],
  },
  {
    id: "fin-zhejiang-wenzhou-yacht",
    name: "浙江温州海鸥船舶有限公司",
    nameEn: "Zhejiang Wenzhou Haiou Marine Co., Ltd.",
    location: "浙江温州",
    locationEn: "Wenzhou, Zhejiang, China",
    province: "浙江",
    category: "manufacturer",
    products: ["玻璃钢游艇", "玻璃钢渔船", "钓鱼艇"],
    productsEn: ["FRP yachts", "FRP fishing boats", "Fishing boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2007,
    verified: false,
    description: "温州本地玻璃钢船厂，南方出口市场为主。",
    descriptionEn:
      "Wenzhou FRP yacht plant primarily serving southern China export markets.",
    certifications: ["CCS"],
    certificationsEn: ["CCS"],
  },
  {
    id: "fin-shandong-yantai-yacht",
    name: "山东烟台天颖船舶制造有限公司",
    nameEn: "Shandong Yantai Tianying Shipbuilding Co., Ltd.",
    location: "山东烟台",
    locationEn: "Yantai, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["玻璃钢渔船", "玻璃钢公务艇", "钓鱼艇"],
    productsEn: ["FRP fishing boats", "FRP government boats", "Fishing boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2006,
    verified: false,
    description: "烟台本地玻璃钢渔船厂，北方公务与渔业市场配套。",
    descriptionEn:
      "Yantai FRP fishing boat plant supplying northern government and fishery markets.",
    certifications: ["CCS"],
    certificationsEn: ["CCS"],
  },
  {
    id: "fin-liaoning-dalian-marine",
    name: "大连天达游艇有限公司",
    nameEn: "Dalian Tianda Yacht Co., Ltd.",
    location: "辽宁大连",
    locationEn: "Dalian, Liaoning, China",
    province: "辽宁",
    category: "manufacturer",
    products: ["玻璃钢游艇", "公务艇", "海洋观光船"],
    productsEn: ["FRP yachts", "Government boats", "Marine sightseeing boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2004,
    verified: false,
    description: "大连本地玻璃钢游艇厂，公务艇与观光船产品线并重。",
    descriptionEn:
      "Dalian FRP yacht maker balancing government boats and marine sightseeing vessels.",
    certifications: ["CCS"],
    certificationsEn: ["CCS"],
  },
  {
    id: "fin-shanghai-marine-frp",
    name: "上海博风船业有限公司",
    nameEn: "Shanghai Bofeng Marine Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "manufacturer",
    products: ["玻璃钢公务艇", "玻璃钢救生艇", "玻璃钢交通艇"],
    productsEn: ["FRP government boats", "FRP rescue boats", "FRP transportation boats"],
    processList: ["手糊", "真空导入"],
    processListEn: ["Hand layup", "Vacuum infusion"],
    established: 2009,
    verified: false,
    description: "上海本地玻璃钢公务艇厂，海事/海警/救捞配套较多。",
    descriptionEn:
      "Shanghai FRP government boat plant primarily supplying maritime, marine police, and rescue agencies.",
    certifications: ["CCS"],
    certificationsEn: ["CCS"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // G. Wind sector additions (主梁拉挤 / 塔筒 / 区域叶片)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-changzhou-spar-pultrusion",
    name: "常州孚迪复合材料有限公司",
    nameEn: "Changzhou Fudi Composite Materials Co., Ltd.",
    location: "江苏常州",
    locationEn: "Changzhou, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["风电叶片拉挤主梁", "拉挤板", "风电叶片预制件"],
    productsEn: ["Wind blade pultruded spar caps", "Pultruded plates", "Wind blade preforms"],
    processList: ["大尺寸拉挤"],
    processListEn: ["Large-section pultrusion"],
    established: 2014,
    verified: false,
    description: "常州拉挤主梁专业厂，碳纤维拉挤板产能配套国内主要风电叶片厂。",
    descriptionEn:
      "Changzhou pultruded spar-cap specialist; carbon-fiber pultruded plate capacity supplies major Chinese blade plants.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-tianshun-yancheng",
    name: "天顺风能盐城风电塔筒基地",
    nameEn: "Titan Wind Yancheng Tower Base",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["风电塔筒", "海上风电单桩", "复材桥架"],
    productsEn: ["Wind towers", "Offshore wind monopiles", "Composite cable trays"],
    processList: ["焊接", "缠绕"],
    processListEn: ["Welding", "Filament winding"],
    established: 2010,
    verified: false,
    description: "天顺风能盐城基地，沿海风电塔筒配套基地。",
    descriptionEn:
      "Titan Wind's Yancheng base supplying coastal wind tower demand.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-taishengfengneng-shanghai",
    name: "泰胜风能装备股份有限公司",
    nameEn: "Taisheng Wind Energy Equipment Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "manufacturer",
    products: ["风电塔筒", "海上风电基础", "钢结构件"],
    productsEn: ["Wind towers", "Offshore wind foundations", "Steel structures"],
    processList: ["焊接", "组装"],
    processListEn: ["Welding", "Assembly"],
    established: 2001,
    verified: false,
    description: "国内主要风电塔筒企业，A 股上市，与多家整机厂深度合作。",
    descriptionEn:
      "Major Chinese wind tower maker, A-share listed, with deep partnerships across multiple turbine OEMs.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-sany-windblade-shaoshan",
    name: "三一重能韶山叶片基地",
    nameEn: "Sany Renewable Energy Shaoshan Blade Base",
    location: "湖南湘潭",
    locationEn: "Xiangtan, Hunan, China",
    province: "湖南",
    category: "manufacturer",
    products: ["风电叶片", "中央供应叶片", "大兆瓦陆上叶片"],
    productsEn: ["Wind blades", "Central-supply blades", "Large-MW onshore blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2017,
    verified: false,
    description: "三一重能韶山叶片基地，配套华中地区陆上风电项目。",
    descriptionEn:
      "Sany Renewable's Shaoshan blade base, supplying onshore wind projects in central China.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-envision-chifeng",
    name: "远景能源赤峰叶片基地",
    nameEn: "Envision Energy Chifeng Blade Base",
    location: "内蒙古赤峰",
    locationEn: "Chifeng, Inner Mongolia, China",
    province: "内蒙古",
    category: "manufacturer",
    products: ["风电叶片", "陆上风电叶片"],
    productsEn: ["Wind blades", "Onshore wind blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2015,
    verified: false,
    description: "远景能源赤峰叶片基地，内蒙古东部风电项目核心配套。",
    descriptionEn:
      "Envision's Chifeng blade base — core supply node for eastern Inner Mongolia wind projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-xinjiang-windblade-jinfeng",
    name: "金风科技乌鲁木齐叶片基地",
    nameEn: "Goldwind Urumqi Blade Base",
    location: "新疆乌鲁木齐",
    locationEn: "Urumqi, Xinjiang, China",
    province: "新疆",
    category: "manufacturer",
    products: ["陆上风电叶片", "高海拔叶片"],
    productsEn: ["Onshore wind blades", "High-altitude blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2010,
    verified: false,
    description: "金风科技新疆叶片基地，配套西北高海拔/低温风电项目。",
    descriptionEn:
      "Goldwind's Xinjiang blade base, supplying high-altitude / low-temperature wind projects in the northwest.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-gansu-windblade-jiuquan",
    name: "中复连众酒泉叶片基地",
    nameEn: "Sinoma Lianzhong Jiuquan Blade Base",
    location: "甘肃酒泉",
    locationEn: "Jiuquan, Gansu, China",
    province: "甘肃",
    category: "manufacturer",
    products: ["陆上风电叶片", "大兆瓦风电叶片"],
    productsEn: ["Onshore wind blades", "Large-MW wind blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2013,
    verified: false,
    description: "中复连众酒泉基地，配套甘肃风电基地与河西走廊项目。",
    descriptionEn:
      "Sinoma Lianzhong's Jiuquan base, supplying Gansu wind base and Hexi Corridor projects.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // H. Anti-corrosion FRP / 防腐 specialists
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-jiangsu-yongma-anticorrosion",
    name: "江苏永马防腐工程有限公司",
    nameEn: "Jiangsu Yongma Anti-corrosion Engineering Co., Ltd.",
    location: "江苏南京",
    locationEn: "Nanjing, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["玻璃钢防腐衬里", "玻璃钢储罐", "脱硫塔内衬"],
    productsEn: ["FRP anti-corrosion linings", "FRP storage tanks", "FGD tower linings"],
    processList: ["手糊", "缠绕"],
    processListEn: ["Hand layup", "Filament winding"],
    established: 1998,
    verified: false,
    description: "江苏南京 FRP 防腐工程公司，化工/电力脱硫塔内衬业务为主。",
    descriptionEn:
      "Nanjing-based FRP anti-corrosion contractor primarily serving chemical and power FGD tower lining work.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shandong-anticorrosion",
    name: "山东海化集团防腐 FRP 业务",
    nameEn: "Shandong Haihua Group Anti-corrosion FRP Business",
    location: "山东潍坊",
    locationEn: "Weifang, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["FRP 防腐管道", "玻璃钢储罐", "防腐塔器"],
    productsEn: ["FRP anti-corrosion piping", "FRP storage tanks", "Anti-corrosion towers"],
    processList: ["缠绕", "手糊"],
    processListEn: ["Filament winding", "Hand layup"],
    established: 1958,
    verified: false,
    description: "山东海化集团防腐 FRP 部门，化工/盐化工系统配套。",
    descriptionEn:
      "Anti-corrosion FRP unit of Shandong Haihua Group, supplying chemical and salt-chemistry systems.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-hebei-cangzhou-frp",
    name: "河北沧州中油重工玻璃钢有限公司",
    nameEn: "Hebei Cangzhou Zhongyou Heavy Industry Fiberglass Co., Ltd.",
    location: "河北沧州",
    locationEn: "Cangzhou, Hebei, China",
    province: "河北",
    category: "manufacturer",
    products: ["FRP 油田管道", "玻璃钢储罐", "缠绕管"],
    productsEn: ["FRP oilfield pipes", "FRP storage tanks", "Filament-wound pipes"],
    processList: ["缠绕"],
    processListEn: ["Filament winding"],
    established: 1995,
    verified: false,
    description: "沧州本地 FRP 油田管道厂，配套华北油田与中石油系统。",
    descriptionEn:
      "Cangzhou FRP oilfield pipe maker supplying north-China oilfields and PetroChina systems.",
    certifications: ["ISO 9001", "API"],
    certificationsEn: ["ISO 9001", "API"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // I. Niche specialty (carbon fiber recycling, 3D printing, cold-molding)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "svc-cf-recycling-jiangsu",
    name: "江苏威盛新材料科技有限公司",
    nameEn: "Jiangsu Weisheng New Materials Tech Co., Ltd.",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "service",
    products: ["碳纤维回收", "再生碳纤维", "回收再生服务"],
    productsEn: ["Carbon fiber recycling", "Recycled carbon fiber (rCF)", "Recycling services"],
    processList: ["热裂解", "化学回收"],
    processListEn: ["Pyrolysis", "Chemical recycling"],
    established: 2015,
    verified: false,
    description: "苏州本地碳纤维回收专业服务商，热裂解工艺路线配套国内复材厂废料处理。",
    descriptionEn:
      "Suzhou-based carbon fiber recycling specialist; pyrolysis-based service for Chinese composite plant scrap.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-3dp-continuous-cf",
    name: "厦门思泰克智能科技有限公司",
    nameEn: "Xiamen STK Intelligent Technology Co., Ltd.",
    location: "福建厦门",
    locationEn: "Xiamen, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["连续碳纤维 3D 打印件", "复材 3D 打印设备", "原型件"],
    productsEn: ["Continuous CF 3D-printed parts", "Composite 3D printers", "Prototype parts"],
    processList: ["连续纤维 3D 打印"],
    processListEn: ["Continuous-fiber 3D printing"],
    established: 2017,
    verified: false,
    description: "厦门连续碳纤维 3D 打印新兴公司，原型件与小批量复材打印业务为主。",
    descriptionEn:
      "Xiamen continuous-CF 3D-printing startup, focused on prototype and short-run composite printing.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // J. More 河北 / 四川 mid-tier (these provinces still under-weighted)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-hebei-baoding-frp",
    name: "河北保定盛业玻璃钢制品有限公司",
    nameEn: "Hebei Baoding Shengye Fiberglass Products Co., Ltd.",
    location: "河北保定",
    locationEn: "Baoding, Hebei, China",
    province: "河北",
    category: "manufacturer",
    products: ["玻璃钢冷却塔", "玻璃钢通风管", "玻璃钢制品"],
    productsEn: ["FRP cooling towers", "FRP ventilation ducts", "FRP products"],
    processList: ["手糊", "缠绕"],
    processListEn: ["Hand layup", "Filament winding"],
    established: 2002,
    verified: false,
    description: "保定本地玻璃钢制品厂，电力与冶金通风系统是主要市场。",
    descriptionEn:
      "Baoding-based FRP products plant; power and metallurgy ventilation systems are key markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-hebei-xingtai-pul",
    name: "河北邢台金石玻璃钢有限公司",
    nameEn: "Hebei Xingtai Jinshi Fiberglass Co., Ltd.",
    location: "河北邢台",
    locationEn: "Xingtai, Hebei, China",
    province: "河北",
    category: "manufacturer",
    products: ["玻璃钢拉挤型材", "电缆桥架", "玻璃钢标志杆"],
    productsEn: ["FRP pultruded profiles", "Cable trays", "FRP signage poles"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2008,
    verified: false,
    description: "邢台本地拉挤型材厂，电力与基建配套为主。",
    descriptionEn:
      "Xingtai pultrusion plant primarily serving power and infrastructure markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-sichuan-deyang-frp",
    name: "四川德阳玻璃钢制品有限公司",
    nameEn: "Sichuan Deyang Fiberglass Products Co., Ltd.",
    location: "四川德阳",
    locationEn: "Deyang, Sichuan, China",
    province: "四川",
    category: "manufacturer",
    products: ["玻璃钢冷却塔", "玻璃钢储罐", "缠绕管道"],
    productsEn: ["FRP cooling towers", "FRP storage tanks", "Filament-wound pipes"],
    processList: ["缠绕", "手糊"],
    processListEn: ["Filament winding", "Hand layup"],
    established: 2000,
    verified: false,
    description: "德阳本地玻璃钢制品厂，西南电力与化工系统配套。",
    descriptionEn:
      "Deyang FRP products plant supplying southwest power and chemical systems.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-sichuan-mianyang-cf",
    name: "四川绵阳科泰碳纤维有限公司",
    nameEn: "Sichuan Mianyang Ketai Carbon Fiber Co., Ltd.",
    location: "四川绵阳",
    locationEn: "Mianyang, Sichuan, China",
    province: "四川",
    category: "manufacturer",
    products: ["碳纤维制品", "碳布", "复材小型件"],
    productsEn: ["Carbon fiber products", "Carbon fabric", "Composite small parts"],
    processList: ["热压", "手糊"],
    processListEn: ["Hot-press", "Hand layup"],
    established: 2010,
    verified: false,
    description: "四川绵阳本地碳纤维制品厂，国防与高校科研配套较多。",
    descriptionEn:
      "Mianyang carbon fiber products plant, primarily supporting defense and university R&D programs.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-sichuan-pul-pole",
    name: "四川泸州拉挤复合材料有限公司",
    nameEn: "Sichuan Luzhou Pultrusion Composite Co., Ltd.",
    location: "四川泸州",
    locationEn: "Luzhou, Sichuan, China",
    province: "四川",
    category: "manufacturer",
    products: ["拉挤型材", "玻璃钢电杆", "标志杆"],
    productsEn: ["Pultruded profiles", "FRP utility poles", "Signage poles"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2009,
    verified: false,
    description: "泸州本地拉挤型材厂，西南电力杆塔市场配套。",
    descriptionEn:
      "Luzhou pultrusion plant supplying southwest utility-pole markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // K. Specialty equipment (filament winding / AFP / NDT)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "eq-harbin-fil-winder",
    name: "哈尔滨复材缠绕装备有限公司",
    nameEn: "Harbin Composite Winding Equipment Co., Ltd.",
    location: "黑龙江哈尔滨",
    locationEn: "Harbin, Heilongjiang, China",
    province: "黑龙江",
    category: "equipment",
    products: ["四轴/六轴缠绕机", "湿法缠绕生产线", "压力容器缠绕机"],
    productsEn: ["4-axis / 6-axis winding machines", "Wet winding lines", "Pressure-vessel winders"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2009,
    verified: false,
    description: "哈尔滨本地缠绕设备专业厂，国内中小型氢瓶与压力容器缠绕机供应。",
    descriptionEn:
      "Harbin filament-winding equipment specialist; supplies winding machines for small/mid hydrogen tanks and pressure vessels.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-jiangsu-afp-machine",
    name: "江苏中复连众智能装备有限公司",
    nameEn: "Jiangsu Sinoma Lianzhong Intelligent Equipment Co., Ltd.",
    location: "江苏连云港",
    locationEn: "Lianyungang, Jiangsu, China",
    province: "江苏",
    category: "equipment",
    products: ["AFP/ATL 自动铺放设备", "复材专用机械手", "工业自动化"],
    productsEn: ["AFP/ATL automated layup equipment", "Composite robotic arms", "Industrial automation"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2018,
    verified: false,
    description: "中复连众体系内自动化装备业务，配套风电叶片与航空 AFP 项目。",
    descriptionEn:
      "Automation equipment business within the Sinoma Lianzhong ecosystem, supplying wind blade and aerospace AFP programs.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-shanghai-ndt-composite",
    name: "上海声宝复合材料无损检测装备有限公司",
    nameEn: "Shanghai Shengbao Composite NDT Equipment Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "equipment",
    products: ["相控阵超声", "C-Scan 系统", "热成像 NDT"],
    productsEn: ["Phased-array ultrasonic", "C-Scan systems", "Thermal-imaging NDT"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2012,
    verified: false,
    description: "上海本地复材无损检测装备厂，航空与风电客户为主。",
    descriptionEn:
      "Shanghai composite NDT equipment maker primarily serving aerospace and wind customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // L. Resin / chemicals (additional regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "rs-jiangxi-shenghua-resin",
    name: "江西华士新材料有限公司",
    nameEn: "Jiangxi Huashi New Materials Co., Ltd.",
    location: "江西九江",
    locationEn: "Jiujiang, Jiangxi, China",
    province: "江西",
    category: "resin",
    products: ["不饱和聚酯树脂", "胶衣", "环氧树脂"],
    productsEn: ["Unsaturated polyester resin", "Gel coats", "Epoxy resins"],
    processList: ["聚合", "复配"],
    processListEn: ["Polymerization", "Compounding"],
    established: 2003,
    verified: false,
    description: "江西本地中型不饱和树脂厂，配套华中 FRP 制品市场。",
    descriptionEn:
      "Mid-sized Jiangxi UPR maker supplying central-China FRP product markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-shanxi-yuanxing-resin",
    name: "山西元兴化工有限公司",
    nameEn: "Shanxi Yuanxing Chemical Co., Ltd.",
    location: "山西太原",
    locationEn: "Taiyuan, Shanxi, China",
    province: "山西",
    category: "resin",
    products: ["环氧树脂", "酚醛树脂", "胶粘剂"],
    productsEn: ["Epoxy resins", "Phenolic resins", "Adhesives"],
    processList: ["合成"],
    processListEn: ["Synthesis"],
    established: 2005,
    verified: false,
    description: "山西本地中型化工树脂厂，主要供应华北煤化工与建材市场。",
    descriptionEn:
      "Mid-sized Shanxi chemical resin maker, primarily serving north-China coal-chemical and building materials markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-guangxi-fragrant",
    name: "广西芬芳新材料有限公司",
    nameEn: "Guangxi Fenfang New Materials Co., Ltd.",
    location: "广西南宁",
    locationEn: "Nanning, Guangxi, China",
    province: "广西",
    category: "resin",
    products: ["不饱和聚酯树脂", "环氧树脂", "胶衣"],
    productsEn: ["Unsaturated polyester resin", "Epoxy resins", "Gel coats"],
    processList: ["合成"],
    processListEn: ["Synthesis"],
    established: 2008,
    verified: false,
    description: "广西本地中型树脂厂，配套华南 FRP 与建材市场。",
    descriptionEn:
      "Mid-sized Guangxi resin maker, supplying south-China FRP and building materials markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // M. Glass fiber regional gaps
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "gf-shanxi-glass-fiber",
    name: "山西利尔玻璃纤维有限公司",
    nameEn: "Shanxi Lier Glass Fiber Co., Ltd.",
    location: "山西阳泉",
    locationEn: "Yangquan, Shanxi, China",
    province: "山西",
    category: "fiber",
    products: ["E-玻璃纤维", "玻纤毡", "短切纱"],
    productsEn: ["E-glass fiber", "Glass mat", "Chopped strands"],
    processList: ["拉丝"],
    processListEn: ["Fiber drawing"],
    established: 1999,
    verified: false,
    description: "山西本地中型玻纤厂，配套华北 FRP 制品市场。",
    descriptionEn:
      "Mid-sized Shanxi glass fiber producer supplying north-China FRP product markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-yunnan-glass-fiber",
    name: "云南南玻玻璃纤维有限公司",
    nameEn: "Yunnan Nanbo Glass Fiber Co., Ltd.",
    location: "云南昆明",
    locationEn: "Kunming, Yunnan, China",
    province: "云南",
    category: "fiber",
    products: ["玻璃纤维直接纱", "玻纤布", "短切纱"],
    productsEn: ["Direct rovings", "Glass fabric", "Chopped strands"],
    processList: ["拉丝", "纺织"],
    processListEn: ["Fiber drawing", "Weaving"],
    established: 2010,
    verified: false,
    description: "云南本地玻纤生产商，配套西南 FRP 与建材市场。",
    descriptionEn:
      "Yunnan-based glass fiber producer supplying southwest FRP and building materials markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "gf-xinjiang-glass-fiber",
    name: "新疆中泰玻璃纤维有限公司",
    nameEn: "Xinjiang Zhongtai Glass Fiber Co., Ltd.",
    location: "新疆乌鲁木齐",
    locationEn: "Urumqi, Xinjiang, China",
    province: "新疆",
    category: "fiber",
    products: ["E-玻璃纤维", "短切纱", "玻纤增强料"],
    productsEn: ["E-glass fiber", "Chopped strands", "Glass-fiber compounds"],
    processList: ["拉丝"],
    processListEn: ["Fiber drawing"],
    established: 2012,
    verified: false,
    description: "新疆本地玻纤厂，依托廉价电力与化工原料优势。",
    descriptionEn:
      "Xinjiang glass fiber maker leveraging low-cost electricity and chemical-feedstock advantages.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // N. Test labs & inspection (more, specifically in regional clusters)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "svc-stc-shanghai",
    name: "上海材料研究所有限公司",
    nameEn: "Shanghai Research Institute of Materials Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "service",
    products: ["材料检测", "失效分析", "复材性能评价"],
    productsEn: ["Material testing", "Failure analysis", "Composite performance evaluation"],
    processList: ["实验室测试", "理化分析"],
    processListEn: ["Laboratory testing", "Physico-chemical analysis"],
    established: 1953,
    verified: false,
    description: "上海材料所，国内综合性材料测试服务机构，复材性能评价业务齐全。",
    descriptionEn:
      "SRIM — comprehensive Chinese material-testing service institution with complete composite performance-evaluation capability.",
    certifications: ["CMA", "CNAS"],
    certificationsEn: ["CMA", "CNAS"],
  },
  {
    id: "svc-cmiit-anhui",
    name: "中国合肥综合性国家科学中心",
    nameEn: "Hefei National Comprehensive Science Center",
    location: "安徽合肥",
    locationEn: "Hefei, Anhui, China",
    province: "安徽",
    category: "service",
    products: ["新材料研究", "结构表征", "性能测试"],
    productsEn: ["New materials research", "Structural characterization", "Performance testing"],
    processList: ["实验研究", "测试服务"],
    processListEn: ["Experimental research", "Testing services"],
    established: 2017,
    verified: false,
    description: "国家级综合科学中心合肥节点，依托中科大和合肥研究院的新材料研究方向。",
    descriptionEn:
      "National-level comprehensive science center at Hefei, leveraging USTC and Hefei Institutes for new materials research.",
    certifications: ["CMA"],
    certificationsEn: ["CMA"],
  },
];

async function main() {
  console.log(`Seeding ${entries.length} v4 supply-chain entries…`);
  let inserted = 0;
  let updated = 0;

  for (const e of entries) {
    const existing = await db.query.supplierListings?.findFirst?.({
      where: (t, { eq }) => eq(t.id, e.id),
    });
    await db
      .insert(supplierListings)
      .values(e)
      .onConflictDoUpdate({
        target: supplierListings.id,
        set: { ...e, updatedAt: new Date() },
      });
    if (existing) updated++;
    else inserted++;
    console.log(`  ✓ ${e.id}  ${e.nameEn}`);
  }

  console.log(`\nv4 seed complete. inserted=${inserted}  updated=${updated}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
