// Bulk add ~120 mainland China composite supply-chain companies
// (foreign-invested in China + large domestic), across:
// fiber (carbon/glass/basalt/aramid/UHMWPE) · resin · equipment · mold · additive · manufacturer · tooling · service
// All inserts use ON CONFLICT (id) DO NOTHING to be idempotent.
import { db } from "@/lib/db";
import { supplierListings } from "@/lib/db/schema";
import { sql } from "drizzle-orm";

type Tier = "XL" | "L" | "M" | "S";
type Cat = "fiber" | "resin" | "equipment" | "mold" | "additive" | "manufacturer" | "tooling" | "service";

interface Row {
  id: string;
  name: string;
  nameEn: string;
  location: string;
  locationEn: string;
  province: string;
  category: Cat;
  products: string[];
  productsEn: string[];
  description?: string;
  descriptionEn?: string;
  established?: number;
  scaleTier: Tier;
  brandPriority: number;
  verified?: boolean;
}

const ROWS: Row[] = [
  // ════════════════════════════════════════════════════════════════════
  // 碳纤维 carbon fiber — foreign-in-China + missing domestics
  // ════════════════════════════════════════════════════════════════════
  { id: "cf-toray-china", name: "东丽(中国)纤维有限公司", nameEn: "Toray China Fiber Co., Ltd.", location: "上海青浦", locationEn: "Qingpu, Shanghai", province: "上海", category: "fiber",
    products: ["T700","T800","T1100碳纤维","碳纤维预浸料"], productsEn: ["T700","T800","T1100 carbon fiber","CF prepreg"],
    description: "日本东丽集团在华碳纤维及预浸料业务平台，全球高强中模碳纤维领导者。", descriptionEn: "Toray Group's China platform for carbon fiber and prepreg; global leader in high-strength intermediate-modulus CF.",
    scaleTier: "XL", brandPriority: 30 },
  { id: "cf-mitsubishi-cn", name: "三菱化学复合材料(上海)有限公司", nameEn: "Mitsubishi Chemical Composite Materials (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["MR40","MR50碳纤维","Pyrofil 预浸料"], productsEn: ["MR40","MR50 CF","Pyrofil prepreg"],
    description: "三菱化学集团在华碳纤维与预浸料业务，覆盖航空、汽车、运动器材市场。", descriptionEn: "Mitsubishi Chemical's China CF and prepreg arm — aerospace, automotive, sporting goods.",
    scaleTier: "XL", brandPriority: 28 },
  { id: "cf-teijin-cn", name: "帝人(中国)投资有限公司碳纤维事业部", nameEn: "Teijin (China) Investment — Carbon Fiber Division", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["Tenax碳纤维","Tenax 预浸料","Twaron 芳纶"], productsEn: ["Tenax CF","Tenax prepreg","Twaron aramid"],
    description: "日本帝人集团在华碳纤维和芳纶纤维（Twaron）业务平台。", descriptionEn: "Teijin Group's China arm for Tenax CF and Twaron aramid.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "cf-zoltek-cn", name: "卓尔泰克(山东)碳纤维有限公司", nameEn: "Zoltek (Shandong) Carbon Fiber Co., Ltd.", location: "山东青岛", locationEn: "Qingdao, Shandong", province: "山东", category: "fiber",
    products: ["大丝束碳纤维","风电用碳纤维","拉挤用碳纤维"], productsEn: ["Heavy-tow CF","Wind blade CF","Pultrusion CF"],
    description: "Toray 集团旗下卓尔泰克在华工厂，全球大丝束工业级碳纤维主要供应商之一。", descriptionEn: "Toray-owned Zoltek's China plant; major heavy-tow industrial CF supplier.",
    scaleTier: "L", brandPriority: 22 },
  { id: "cf-hexcel-cn", name: "赫氏(天津)复合材料有限公司", nameEn: "Hexcel (Tianjin) Composites Co., Ltd.", location: "天津", locationEn: "Tianjin", province: "天津", category: "fiber",
    products: ["HexTow 碳纤维","HexPly 预浸料","蜂窝芯材"], productsEn: ["HexTow CF","HexPly prepreg","Honeycomb core"],
    description: "美国 Hexcel 集团在华生产基地，航空航天高端预浸料与蜂窝芯材主要供应商。", descriptionEn: "Hexcel's China plant — aerospace high-performance prepreg and honeycomb.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "cf-sgl-cn", name: "西格里(上海)碳纤维有限公司", nameEn: "SGL Carbon (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["SIGRAFIL 碳纤维","碳纤维毡","碳纤维织物"], productsEn: ["SIGRAFIL CF","CF felt","CF fabric"],
    description: "德国 SGL Carbon 集团在华业务平台。", descriptionEn: "SGL Carbon Group's China business platform.",
    scaleTier: "L", brandPriority: 22 },
  { id: "cf-zhongan-xin", name: "中安信科技有限公司", nameEn: "Zhong'an Xinco Technology Co., Ltd.", location: "河北廊坊", locationEn: "Langfang, Hebei", province: "河北", category: "fiber",
    products: ["T700","T800 碳纤维","碳纤维预浸料"], productsEn: ["T700","T800 CF","CF prepreg"],
    description: "国内自主碳纤维生产厂家，T700/T800 量产能力，应用于光威等下游。", descriptionEn: "Domestic CF manufacturer with T700/T800 mass-production capacity.",
    scaleTier: "L", brandPriority: 18 },
  { id: "cf-taigang-keji", name: "山西钢科碳材料有限公司", nameEn: "Shanxi Steel Carbon Materials Co., Ltd.", location: "山西太原", locationEn: "Taiyuan, Shanxi", province: "山西", category: "fiber",
    products: ["高强碳纤维","高模量碳纤维"], productsEn: ["High-strength CF","High-modulus CF"],
    description: "太钢集团旗下碳纤维公司，国内 T800/T1000 级高性能碳纤维生产基地。", descriptionEn: "TISCO Group's carbon fiber arm — domestic T800/T1000 grade.",
    scaleTier: "L", brandPriority: 20 },
  { id: "cf-saience-cn", name: "山东赛恩斯复合材料有限公司", nameEn: "Shandong Sciences Composite Materials Co., Ltd.", location: "山东泰安", locationEn: "Tai'an, Shandong", province: "山东", category: "fiber",
    products: ["碳纤维预浸料","碳纤维织物","碳纤维制品"], productsEn: ["CF prepreg","CF fabric","CF parts"],
    description: "国内中等规模碳纤维深加工厂家。", descriptionEn: "Mid-scale domestic CF downstream processor.",
    scaleTier: "M", brandPriority: 12 },
  { id: "cf-jingye-cn", name: "浙江精业新兴材料有限公司", nameEn: "Zhejiang Jingye New Materials Co., Ltd.", location: "浙江绍兴", locationEn: "Shaoxing, Zhejiang", province: "浙江", category: "fiber",
    products: ["碳纤维预浸料","蜂窝芯","碳板"], productsEn: ["CF prepreg","Honeycomb core","CF panels"],
    description: "碳纤维深加工，主供消费电子、汽车、运动器材。", descriptionEn: "CF downstream — consumer electronics, automotive, sporting goods.",
    scaleTier: "M", brandPriority: 12 },

  // ════════════════════════════════════════════════════════════════════
  // 玻纤 glass fiber — foreign-in-China + missing domestics
  // ════════════════════════════════════════════════════════════════════
  { id: "gf-oc-china", name: "欧文斯科宁(中国)投资有限公司", nameEn: "Owens Corning (China) Investment Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["玻璃纤维纱","风电叶片增强","热塑增强"], productsEn: ["Glass fiber rovings","Wind blade reinforcement","Thermoplastic reinforcement"],
    description: "美国 Owens Corning 在华生产网络，全球前三大玻纤生产商。", descriptionEn: "Owens Corning's China network; top-3 global glass fiber producer.",
    scaleTier: "XL", brandPriority: 28 },
  { id: "gf-jm-china", name: "约翰斯曼维尔(中国)有限公司", nameEn: "Johns Manville China Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["玻璃纤维毡","玻璃纤维短切","隔热产品"], productsEn: ["GF mat","GF chopped strand","Insulation"],
    description: "Berkshire Hathaway 旗下玻璃纤维与隔热材料厂商在华业务。", descriptionEn: "Berkshire Hathaway-owned GF and insulation business in China.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "gf-vetrotex-cn", name: "圣戈班维特罗特斯(中国)有限公司", nameEn: "Saint-Gobain Vetrotex (China) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["TwinTex","直接纱","风电增强材料"], productsEn: ["TwinTex","Direct rovings","Wind reinforcement"],
    description: "圣戈班集团玻纤业务在华平台。", descriptionEn: "Saint-Gobain's glass fiber arm in China.",
    scaleTier: "XL", brandPriority: 22 },
  { id: "gf-agy-cn", name: "AGY 玻璃纤维(上海)有限公司", nameEn: "AGY Glass Fiber (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["S-2 玻璃纤维","高性能玻纤","军工玻纤"], productsEn: ["S-2 glass fiber","High-performance GF","Defense GF"],
    description: "美国 AGY 在华业务，S-2 高强玻璃纤维主要供应商。", descriptionEn: "AGY's China presence — S-2 high-strength glass fiber.",
    scaleTier: "L", brandPriority: 20 },
  { id: "gf-hengshi", name: "河北恒石玻璃纤维有限公司", nameEn: "Hebei Hengshi Glass Fiber Co., Ltd.", location: "河北邯郸", locationEn: "Handan, Hebei", province: "河北", category: "fiber",
    products: ["玻纤纱","玻纤布","风电直接纱"], productsEn: ["GF rovings","GF fabric","Wind direct rovings"],
    description: "国内主要玻璃纤维生产商之一。", descriptionEn: "Major domestic glass fiber producer.",
    scaleTier: "L", brandPriority: 20 },
  { id: "gf-jinhong", name: "内蒙古金鸿玻璃纤维有限公司", nameEn: "Inner Mongolia Jinhong Glass Fiber Co., Ltd.", location: "内蒙古乌海", locationEn: "Wuhai, Inner Mongolia", province: "内蒙古", category: "fiber",
    products: ["玻纤纱","池窑直接纱"], productsEn: ["GF rovings","Tank furnace direct rovings"],
    description: "西部地区主要玻璃纤维池窑生产基地。", descriptionEn: "Major GF tank-furnace producer in western China.",
    scaleTier: "L", brandPriority: 18 },
  { id: "gf-guangyuan", name: "河南光远新材料股份有限公司", nameEn: "Henan Guangyuan New Materials Co., Ltd.", location: "河南焦作", locationEn: "Jiaozuo, Henan", province: "河南", category: "fiber",
    products: ["电子级玻纤布","低介电玻纤","5G PCB 用玻纤"], productsEn: ["Electronic GF cloth","Low-dielectric GF","5G PCB GF"],
    description: "电子级玻纤布上市公司，5G/AI 芯片基板核心供应商。", descriptionEn: "Listed electronic-grade GF cloth maker; 5G/AI substrate supplier.",
    scaleTier: "XL", brandPriority: 25 },
  { id: "gf-hongxiang", name: "山东宏祥新材料股份有限公司", nameEn: "Shandong Hongxiang New Materials Co., Ltd.", location: "山东德州", locationEn: "Dezhou, Shandong", province: "山东", category: "fiber",
    products: ["土工布","玻纤复合材料","非织造材料"], productsEn: ["Geotextile","GF composites","Nonwoven"],
    description: "新三板挂牌玻纤复合材料企业。", descriptionEn: "Listed GF composite material manufacturer.",
    scaleTier: "L", brandPriority: 16 },
  { id: "gf-hengyuan", name: "河北恒源玻璃纤维有限公司", nameEn: "Hebei Hengyuan Glass Fiber Co., Ltd.", location: "河北雄县", locationEn: "Xiongxian, Hebei", province: "河北", category: "fiber",
    products: ["玻纤短切","玻纤毡","玻纤布"], productsEn: ["Chopped GF","GF mat","GF fabric"],
    description: "雄安产业带玻纤产品集群企业。", descriptionEn: "Xiong'an cluster GF products manufacturer.",
    scaleTier: "M", brandPriority: 12 },

  // ════════════════════════════════════════════════════════════════════
  // 玄武岩 basalt fiber — missing major brands
  // ════════════════════════════════════════════════════════════════════
  { id: "bf-hengdian-dongmag", name: "横店集团东磁玄武岩纤维有限公司", nameEn: "Hengdian Dongmag Basalt Fiber Co., Ltd.", location: "浙江东阳", locationEn: "Dongyang, Zhejiang", province: "浙江", category: "fiber",
    products: ["玄武岩连续纤维","玄武岩短切纤维","BFRP"], productsEn: ["Continuous basalt fiber","Chopped basalt","BFRP"],
    description: "横店集团旗下玄武岩纤维业务，国内连续玄武岩纤维主要厂商之一。", descriptionEn: "Hengdian Group's basalt fiber arm — major continuous basalt producer.",
    scaleTier: "L", brandPriority: 20 },
  { id: "bf-tianlong", name: "江苏天龙玄武岩纤维科技有限公司", nameEn: "Jiangsu Tianlong Basalt Fiber Tech Co., Ltd.", location: "江苏无锡", locationEn: "Wuxi, Jiangsu", province: "江苏", category: "fiber",
    products: ["玄武岩连续纤维","玄武岩复合筋","防火制品"], productsEn: ["Continuous BF","BF rebar","Fire-resistant"],
    description: "江苏专业玄武岩纤维及制品厂商。", descriptionEn: "Jiangsu basalt fiber and downstream products specialist.",
    scaleTier: "M", brandPriority: 14 },
  { id: "bf-bsotec", name: "山西巴塞奥特新材料有限公司", nameEn: "Shanxi Basaltec New Materials Co., Ltd.", location: "山西晋中", locationEn: "Jinzhong, Shanxi", province: "山西", category: "fiber",
    products: ["玄武岩纤维","玄武岩防腐板"], productsEn: ["Basalt fiber","BF anti-corrosion panel"],
    description: "玄武岩纤维细分品牌，主供建筑加固、防腐市场。", descriptionEn: "Basalt fiber niche brand for construction reinforcement and corrosion-resistance.",
    scaleTier: "M", brandPriority: 12 },
  { id: "bf-shijin-zhejiang", name: "浙江石金玄武岩纤维股份有限公司", nameEn: "Zhejiang Shijin Basalt Fiber Co., Ltd.", location: "浙江诸暨", locationEn: "Zhuji, Zhejiang", province: "浙江", category: "fiber",
    products: ["连续玄武岩纤维","玄武岩纱","玄武岩布"], productsEn: ["Continuous basalt","Basalt rovings","Basalt fabric"],
    description: "国内主要连续玄武岩纤维上市公司。", descriptionEn: "Major listed continuous basalt fiber producer.",
    scaleTier: "L", brandPriority: 20 },

  // ════════════════════════════════════════════════════════════════════
  // 芳纶 aramid — missing major brands (in addition to 泰和新材)
  // ════════════════════════════════════════════════════════════════════
  { id: "af-dupont-cn", name: "杜邦中国凯夫拉业务部", nameEn: "DuPont China — Kevlar Business", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["Kevlar 29","Kevlar 49","Kevlar 129 芳纶"], productsEn: ["Kevlar 29","Kevlar 49","Kevlar 129"],
    description: "DuPont Kevlar 全球品牌中国分销与应用开发。", descriptionEn: "DuPont Kevlar China distribution and application development.",
    scaleTier: "XL", brandPriority: 28 },
  { id: "af-zhonglan-chenguang", name: "中蓝晨光化工研究院芳纶事业部", nameEn: "Bluestar Chenguang Research Institute — Aramid Division", location: "四川成都", locationEn: "Chengdu, Sichuan", province: "四川", category: "fiber",
    products: ["F-12 芳纶","对位芳纶","芳纶纤维"], productsEn: ["F-12 aramid","Para-aramid","Aramid fiber"],
    description: "中国蓝星集团下属，国内对位芳纶研发生产基地。", descriptionEn: "Bluestar Group's domestic para-aramid R&D and production base.",
    scaleTier: "L", brandPriority: 20 },
  { id: "af-guigu", name: "河北硅谷化工有限公司", nameEn: "Hebei Silicon Valley Chemical Co., Ltd.", location: "河北邯郸", locationEn: "Handan, Hebei", province: "河北", category: "fiber",
    products: ["对位芳纶","防弹用芳纶","芳纶 1414"], productsEn: ["Para-aramid","Bulletproof aramid","Aramid 1414"],
    description: "对位芳纶细分龙头之一。", descriptionEn: "Domestic para-aramid niche leader.",
    scaleTier: "L", brandPriority: 18 },
  { id: "af-longbang", name: "河南龙邦特种纤维有限公司", nameEn: "Henan Longbang Specialty Fiber Co., Ltd.", location: "河南平顶山", locationEn: "Pingdingshan, Henan", province: "河南", category: "fiber",
    products: ["间位芳纶","对位芳纶","芳纶纸"], productsEn: ["Meta-aramid","Para-aramid","Aramid paper"],
    description: "国内芳纶纤维主要生产商。", descriptionEn: "Domestic aramid fiber major producer.",
    scaleTier: "L", brandPriority: 18 },
  { id: "af-jiangsu-shengou", name: "江苏圣欧高性能材料股份有限公司", nameEn: "Jiangsu Shengou High-Performance Materials Co., Ltd.", location: "江苏南通", locationEn: "Nantong, Jiangsu", province: "江苏", category: "fiber",
    products: ["间位芳纶","芳纶 IIIA","芳纶纸"], productsEn: ["Meta-aramid","Aramid IIIA","Aramid paper"],
    description: "间位芳纶专业生产厂家，主供安防与电气绝缘市场。", descriptionEn: "Meta-aramid specialist for safety and electrical insulation markets.",
    scaleTier: "M", brandPriority: 14 },

  // ════════════════════════════════════════════════════════════════════
  // 超高分子量聚乙烯 UHMWPE
  // ════════════════════════════════════════════════════════════════════
  { id: "fb-tongyiqiang", name: "宁波大成新材料股份有限公司", nameEn: "Ningbo Dacheng New Materials Co., Ltd.", location: "浙江宁波", locationEn: "Ningbo, Zhejiang", province: "浙江", category: "fiber",
    products: ["UHMWPE 纤维","防弹纤维","Tongyiqiang 同益强"], productsEn: ["UHMWPE fiber","Bulletproof fiber","Tongyiqiang"],
    description: "国内 UHMWPE 纤维（同益强品牌）头部厂家，防弹及绳缆市场。", descriptionEn: "Domestic UHMWPE fiber (Tongyiqiang brand) leader for ballistic and rope markets.",
    scaleTier: "L", brandPriority: 20 },
  { id: "fb-dsm-china", name: "帝斯曼(中国)有限公司高性能纤维事业部", nameEn: "DSM China — High Performance Fibers", location: "上海", locationEn: "Shanghai", province: "上海", category: "fiber",
    products: ["Dyneema UHMWPE","防弹纤维"], productsEn: ["Dyneema UHMWPE","Bulletproof fiber"],
    description: "荷兰 DSM 集团 Dyneema 品牌在华分销和技术支持。", descriptionEn: "DSM Group's Dyneema brand in China.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "fb-liuhe-uhmwpe", name: "江苏六合纤维新材料有限公司", nameEn: "Jiangsu Liuhe Fiber New Materials Co., Ltd.", location: "江苏淮安", locationEn: "Huai'an, Jiangsu", province: "江苏", category: "fiber",
    products: ["UHMWPE 纤维","渔网用纤维"], productsEn: ["UHMWPE fiber","Fishing net fiber"],
    description: "UHMWPE 纤维中等规模厂家。", descriptionEn: "Mid-scale UHMWPE fiber producer.",
    scaleTier: "M", brandPriority: 12 },

  // ════════════════════════════════════════════════════════════════════
  // 树脂 resin — major foreign + domestic missing
  // ════════════════════════════════════════════════════════════════════
  { id: "rs-basf-cn", name: "巴斯夫(中国)有限公司高性能材料部", nameEn: "BASF (China) — Performance Materials", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["环氧树脂","聚氨酯树脂","Elastoflex","风电浇注料"], productsEn: ["Epoxy","Polyurethane","Elastoflex","Wind casting resin"],
    description: "BASF 集团在华高性能材料业务，覆盖风电、汽车、工程结构件市场。", descriptionEn: "BASF's China performance materials business — wind, automotive, engineering structures.",
    scaleTier: "XL", brandPriority: 30 },
  { id: "rs-dow-cn", name: "陶氏化学(中国)投资有限公司", nameEn: "Dow Chemical (China) Investment Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["环氧树脂","聚氨酯","Voraforce","风电用环氧"], productsEn: ["Epoxy","PU","Voraforce","Wind epoxy"],
    description: "Dow 集团在华化工与树脂业务，风电叶片用环氧树脂主要供应商。", descriptionEn: "Dow Group's China chemicals/resin — major wind blade epoxy supplier.",
    scaleTier: "XL", brandPriority: 30 },
  { id: "rs-huntsman-cn", name: "亨斯迈(中国)投资有限公司", nameEn: "Huntsman (China) Investment Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["MDI","环氧树脂","Araldite","固化剂"], productsEn: ["MDI","Epoxy","Araldite","Hardeners"],
    description: "Huntsman 集团在华树脂、聚氨酯和高性能特种化学业务。", descriptionEn: "Huntsman Group's China resin, PU and specialty chemicals.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "rs-arkema-cn", name: "阿科玛(中国)投资有限公司", nameEn: "Arkema (China) Investment Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["丙烯酸树脂","Elium","氟树脂","PA12"], productsEn: ["Acrylic resin","Elium","Fluoropolymer","PA12"],
    description: "Arkema 集团在华，Elium 热塑性环氧风电叶片、PA12 等先进树脂。", descriptionEn: "Arkema's China — Elium thermoplastic wind blade resin, PA12 etc.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "rs-sika-cn", name: "西卡(中国)有限公司", nameEn: "Sika (China) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["结构胶","SikaForce","聚氨酯密封","风电叶片胶"], productsEn: ["Structural adhesive","SikaForce","PU sealant","Wind blade adhesive"],
    description: "Sika 集团在华业务，风电叶片粘接胶领导厂商之一。", descriptionEn: "Sika Group's China business — wind blade adhesive leader.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "rs-dsm-cn", name: "帝斯曼(中国)有限公司复材树脂部", nameEn: "DSM China — Composite Resins", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["乙烯基酯树脂","Atlac","DSM 风电树脂"], productsEn: ["Vinyl ester","Atlac","DSM wind resin"],
    description: "DSM 集团在华树脂业务，高性能乙烯基酯、风电用环氧。", descriptionEn: "DSM Group's China resin — high-performance vinyl ester, wind epoxy.",
    scaleTier: "L", brandPriority: 20 },
  { id: "rs-saint-gobain-resin", name: "圣戈班特种化学(上海)有限公司", nameEn: "Saint-Gobain Specialty Chemicals (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "resin",
    products: ["特种胶黏剂","树脂","硅胶"], productsEn: ["Specialty adhesives","Resins","Silicones"],
    description: "Saint-Gobain 特种化学品在华业务。", descriptionEn: "Saint-Gobain Specialty Chemicals in China.",
    scaleTier: "L", brandPriority: 20 },
  { id: "rs-shaohua", name: "韶华树脂集团有限公司", nameEn: "Shaohua Resin Group Co., Ltd.", location: "广东韶关", locationEn: "Shaoguan, Guangdong", province: "广东", category: "resin",
    products: ["不饱和聚酯","乙烯基酯","环氧","胶衣"], productsEn: ["Unsaturated polyester","Vinyl ester","Epoxy","Gel coat"],
    description: "国内不饱和聚酯树脂主要生产商之一，覆盖船舶、卫浴、风电等市场。", descriptionEn: "Major domestic UPR producer — marine, sanitary, wind markets.",
    scaleTier: "L", brandPriority: 20 },
  { id: "rs-shengquan", name: "山东圣泉新材料股份有限公司", nameEn: "Shandong Shengquan New Materials Co., Ltd.", location: "山东章丘", locationEn: "Zhangqiu, Shandong", province: "山东", category: "resin",
    products: ["酚醛树脂","环氧树脂","糠醇树脂","铸造用树脂"], productsEn: ["Phenolic","Epoxy","Furfuryl","Foundry resin"],
    description: "深交所上市公司，国内酚醛与铸造用树脂头部企业。", descriptionEn: "SZSE-listed; domestic phenolic and foundry resin leader.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "rs-yadong", name: "河北亚东化工集团有限公司", nameEn: "Hebei Yadong Chemical Group Co., Ltd.", location: "河北唐山", locationEn: "Tangshan, Hebei", province: "河北", category: "resin",
    products: ["不饱和聚酯","乙烯基酯","胶衣"], productsEn: ["UPR","Vinyl ester","Gel coat"],
    description: "国内 UPR 头部生产基地。", descriptionEn: "Domestic UPR major producer.",
    scaleTier: "L", brandPriority: 20 },
  { id: "rs-vicker", name: "江苏沃克斯特新材料有限公司", nameEn: "Jiangsu Vickert New Materials Co., Ltd.", location: "江苏南通", locationEn: "Nantong, Jiangsu", province: "江苏", category: "resin",
    products: ["环氧树脂","风电用环氧","结构胶"], productsEn: ["Epoxy","Wind epoxy","Structural adhesive"],
    description: "国内中等规模风电叶片用环氧树脂厂家。", descriptionEn: "Mid-scale wind blade epoxy producer.",
    scaleTier: "M", brandPriority: 14 },
  { id: "rs-skshu", name: "三棵树涂料股份有限公司复材事业部", nameEn: "SKSHU Paint — Composites Division", location: "福建莆田", locationEn: "Putian, Fujian", province: "福建", category: "resin",
    products: ["环氧涂层","防腐涂料","风电涂料"], productsEn: ["Epoxy coating","Anti-corrosion","Wind coatings"],
    description: "上市涂料公司复材涂层与树脂事业部。", descriptionEn: "Listed coating company's composite coating and resin division.",
    scaleTier: "L", brandPriority: 18 },
  { id: "rs-kaihua", name: "凯华树脂(浙江)有限公司", nameEn: "Kaihua Resin (Zhejiang) Co., Ltd.", location: "浙江湖州", locationEn: "Huzhou, Zhejiang", province: "浙江", category: "resin",
    products: ["不饱和聚酯","乙烯基酯","防腐树脂"], productsEn: ["UPR","Vinyl ester","Anti-corrosion resin"],
    description: "细分领域 UPR/VE 树脂厂家。", descriptionEn: "UPR/VE niche resin producer.",
    scaleTier: "M", brandPriority: 12 },
  { id: "rs-jiulisheng", name: "浙江久必胜复合材料有限公司", nameEn: "Zhejiang Jiulisheng Composite Materials Co., Ltd.", location: "浙江湖州", locationEn: "Huzhou, Zhejiang", province: "浙江", category: "resin",
    products: ["不饱和聚酯","胶衣","船用树脂"], productsEn: ["UPR","Gel coat","Marine resin"],
    description: "船用与卫浴树脂细分厂家。", descriptionEn: "Marine and sanitary resin niche.",
    scaleTier: "M", brandPriority: 10 },
  { id: "rs-juli-resin", name: "江苏巨力树脂有限公司", nameEn: "Jiangsu Juli Resin Co., Ltd.", location: "江苏宿迁", locationEn: "Suqian, Jiangsu", province: "江苏", category: "resin",
    products: ["环氧树脂","固化剂","拉挤用树脂"], productsEn: ["Epoxy","Hardeners","Pultrusion resin"],
    description: "拉挤用环氧树脂细分供应商。", descriptionEn: "Pultrusion epoxy niche supplier.",
    scaleTier: "M", brandPriority: 10 },

  // ════════════════════════════════════════════════════════════════════
  // 设备 equipment — major foreign + missing domestics
  // ════════════════════════════════════════════════════════════════════
  { id: "eq-kraussmaffei-cn", name: "克劳斯玛菲(中国)有限公司", nameEn: "KraussMaffei China Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "equipment",
    products: ["RTM 设备","HP-RTM","注塑机","拉挤机"], productsEn: ["RTM equipment","HP-RTM","Injection molding","Pultrusion lines"],
    description: "德国 KraussMaffei 集团在华业务，复材成型设备龙头。", descriptionEn: "KraussMaffei Group's China — composite molding equipment leader.",
    scaleTier: "XL", brandPriority: 28 },
  { id: "eq-dieffenbacher-cn", name: "迪芬巴赫(中国)机械制造有限公司", nameEn: "Dieffenbacher (China) Machinery Manufacturing Co., Ltd.", location: "江苏苏州", locationEn: "Suzhou, Jiangsu", province: "江苏", category: "equipment",
    products: ["复材压机","SMC/BMC 生产线","HP-RTM 系统"], productsEn: ["Composite presses","SMC/BMC lines","HP-RTM systems"],
    description: "德国 Dieffenbacher 在华工厂，重型复材压机龙头。", descriptionEn: "Dieffenbacher's China plant — heavy-press composite molding leader.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "eq-roth-cn", name: "罗斯复合材料机械(上海)有限公司", nameEn: "Roth Composite Machinery (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "equipment",
    products: ["缠绕机","拉挤机","复合材料卷绕"], productsEn: ["Filament winding","Pultrusion","CF tow winding"],
    description: "德国 Roth 在华业务，缠绕成型设备主要供应商。", descriptionEn: "Roth's China — filament winding equipment supplier.",
    scaleTier: "L", brandPriority: 20 },
  { id: "eq-kuka-cn", name: "库卡机器人(上海)有限公司", nameEn: "KUKA Robotics (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "equipment",
    products: ["铺丝机器人","AFP/ATL 系统","切割机器人"], productsEn: ["Tow placement robots","AFP/ATL systems","Cutting robots"],
    description: "KUKA 中国，复材自动化铺放与切割机器人主要供应商。", descriptionEn: "KUKA China — major composites automation, AFP/ATL and cutting robotics.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "eq-abb-cn", name: "ABB(中国)有限公司复材业务", nameEn: "ABB (China) — Composites Business", location: "上海", locationEn: "Shanghai", province: "上海", category: "equipment",
    products: ["复材自动化机器人","机器人系统集成"], productsEn: ["Composite automation robots","Robot system integration"],
    description: "ABB 在华工业机器人与复材自动化集成。", descriptionEn: "ABB China — industrial robots + composites automation integration.",
    scaleTier: "XL", brandPriority: 22 },
  { id: "eq-tuopu-shanghai", name: "上海拓璞数控科技股份有限公司", nameEn: "Shanghai Tuopu CNC Technology Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "equipment",
    products: ["AFP 铺丝机","蒙皮搅拌摩擦焊","五轴 CNC"], productsEn: ["AFP machines","FSW","5-axis CNC"],
    description: "国产 AFP 铺丝设备龙头，航空航天复材自动化先驱。", descriptionEn: "Domestic AFP equipment leader — aerospace composite automation pioneer.",
    scaleTier: "L", brandPriority: 22 },
  { id: "eq-huagong-laser", name: "华工激光工程有限责任公司", nameEn: "HGTECH Laser Engineering Co., Ltd.", location: "湖北武汉", locationEn: "Wuhan, Hubei", province: "湖北", category: "equipment",
    products: ["激光切割机","复材切边","激光打标"], productsEn: ["Laser cutting","CF edge trim","Laser marking"],
    description: "华工科技旗下，复材激光切割主要厂商。", descriptionEn: "HGTECH subsidiary — composite laser cutting major.",
    scaleTier: "L", brandPriority: 20 },
  { id: "eq-narcoda", name: "江阴市纳尔科达自动化设备有限公司", nameEn: "Jiangyin Narcoda Automation Equipment Co., Ltd.", location: "江苏江阴", locationEn: "Jiangyin, Jiangsu", province: "江苏", category: "equipment",
    products: ["复材机器人系统","自动化生产线"], productsEn: ["Composite robotic systems","Automation lines"],
    description: "国内复材自动化系统集成商。", descriptionEn: "Domestic composite automation integrator.",
    scaleTier: "M", brandPriority: 14 },
  { id: "eq-meirayda", name: "北京迈瑞达科技股份有限公司", nameEn: "Beijing Mairayda Science and Technology Co., Ltd.", location: "北京", locationEn: "Beijing", province: "北京", category: "equipment",
    products: ["复材专用 CNC","五轴铣削","切边修整"], productsEn: ["Composite CNC","5-axis milling","Trim/edge"],
    description: "国内复材专用 CNC 设备主要厂商。", descriptionEn: "Domestic composite-specific CNC supplier.",
    scaleTier: "L", brandPriority: 18 },
  { id: "eq-julihong-zhangjiagang", name: "张家港巨力机械有限公司", nameEn: "Zhangjiagang Juli Machinery Co., Ltd.", location: "江苏张家港", locationEn: "Zhangjiagang, Jiangsu", province: "江苏", category: "equipment",
    products: ["拉挤生产线","拉挤模具","纤维浸渍设备"], productsEn: ["Pultrusion lines","Pultrusion dies","Fiber wet-out"],
    description: "国内拉挤设备老牌厂家。", descriptionEn: "Veteran domestic pultrusion equipment manufacturer.",
    scaleTier: "L", brandPriority: 18 },
  { id: "eq-aorun-jiangsu", name: "江苏奥润复合材料缠绕设备有限公司", nameEn: "Jiangsu Aorun Filament Winding Equipment Co., Ltd.", location: "江苏盐城", locationEn: "Yancheng, Jiangsu", province: "江苏", category: "equipment",
    products: ["缠绕机","压力容器缠绕设备","氢气瓶设备"], productsEn: ["Filament winding","Pressure vessel winding","H2 tank equipment"],
    description: "缠绕成型设备国产主要厂家，氢气瓶用设备热门方向。", descriptionEn: "Domestic filament winding leader — H2 tank equipment trend.",
    scaleTier: "L", brandPriority: 18 },

  // ════════════════════════════════════════════════════════════════════
  // 模具 mold — major foreign + missing
  // ════════════════════════════════════════════════════════════════════
  { id: "md-suzhou-mingzhi", name: "苏州明志科技股份有限公司", nameEn: "Suzhou Mingzhi Technology Co., Ltd.", location: "江苏苏州", locationEn: "Suzhou, Jiangsu", province: "江苏", category: "mold",
    products: ["3D 打印砂芯","复材模具","汽车铸件模具"], productsEn: ["3D-printed sand core","Composite molds","Automotive casting molds"],
    description: "上市公司，3D 打印砂芯与复材模具领先厂家。", descriptionEn: "Listed company — 3D-printed sand core and composite mold leader.",
    scaleTier: "L", brandPriority: 20 },
  { id: "md-puhui-beijing", name: "北京普惠精工科技有限公司", nameEn: "Beijing Puhui Precision Engineering Co., Ltd.", location: "北京", locationEn: "Beijing", province: "北京", category: "mold",
    products: ["航空复材模具","RTM 模具","碳纤维模具"], productsEn: ["Aerospace composite molds","RTM molds","CF molds"],
    description: "航空复材模具专业厂家。", descriptionEn: "Aerospace composite mold specialist.",
    scaleTier: "L", brandPriority: 16 },
  { id: "md-haitian-cn", name: "海天集团模具事业部", nameEn: "Haitian Group — Mold Division", location: "浙江宁波", locationEn: "Ningbo, Zhejiang", province: "浙江", category: "mold",
    products: ["注塑模具","复材模具","SMC 模具"], productsEn: ["Injection molds","Composite molds","SMC molds"],
    description: "海天集团模具事业部，覆盖塑料与复材模具。", descriptionEn: "Haitian Group's mold division — plastic and composite molds.",
    scaleTier: "L", brandPriority: 18 },
  { id: "md-jiangsu-tiangong", name: "江苏天工模具有限公司", nameEn: "Jiangsu Tiangong Mold Co., Ltd.", location: "江苏丹阳", locationEn: "Danyang, Jiangsu", province: "江苏", category: "mold",
    products: ["复材模具","SMC 模具","风电叶片模具"], productsEn: ["Composite molds","SMC molds","Wind blade molds"],
    description: "国内复材模具知名厂家。", descriptionEn: "Domestic composite mold maker.",
    scaleTier: "M", brandPriority: 14 },
  { id: "md-double-one-jinan", name: "山东双一科技模具事业部", nameEn: "Shandong Shuangyi Technology — Mold Division", location: "山东威海", locationEn: "Weihai, Shandong", province: "山东", category: "mold",
    products: ["风电叶片模具","大型复材模具"], productsEn: ["Wind blade molds","Large composite molds"],
    description: "山东双一科技子事业部，国内最大风电叶片模具厂之一。", descriptionEn: "Shuangyi Tech subsidiary — top domestic wind blade mold maker.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "md-shanghai-baosteel", name: "宝钢金属模具有限公司", nameEn: "Baosteel Metal Mold Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "mold",
    products: ["精密模具","汽车模具","复材模具"], productsEn: ["Precision molds","Automotive molds","Composite molds"],
    description: "宝钢集团模具子公司。", descriptionEn: "Baosteel Group's mold subsidiary.",
    scaleTier: "L", brandPriority: 18 },

  // ════════════════════════════════════════════════════════════════════
  // 助剂 additive — NEW CATEGORY
  // ════════════════════════════════════════════════════════════════════
  { id: "ad-byk-cn", name: "毕克化学(上海)有限公司", nameEn: "BYK Chemie (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["分散剂","流平剂","消泡剂","润湿剂"], productsEn: ["Dispersants","Leveling agents","Defoamers","Wetting agents"],
    description: "ALTANA 集团旗下 BYK 在华业务，复材涂料涂层助剂全球龙头。", descriptionEn: "ALTANA's BYK in China — global leader in coating/composite additives.",
    scaleTier: "XL", brandPriority: 30 },
  { id: "ad-tego-evonik", name: "赢创德固赛(上海)投资有限公司", nameEn: "Evonik Degussa (Shanghai) Investment Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["TEGO 助剂","硅烷偶联剂","Aerosil 气相二氧化硅"], productsEn: ["TEGO additives","Silane couplers","Aerosil fumed silica"],
    description: "Evonik 集团在华，TEGO 助剂与硅烷偶联剂主要供应商。", descriptionEn: "Evonik China — TEGO additives and silane coupler major.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "ad-solvay-cn", name: "索尔维(上海)有限公司", nameEn: "Solvay (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["过氧化物固化剂","硫醇","特种助剂"], productsEn: ["Peroxide curing agents","Mercaptans","Specialty additives"],
    description: "Solvay 在华特种化学品，复材固化剂与助剂业务。", descriptionEn: "Solvay China — specialty chemicals, composite curing agents and additives.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "ad-dowsil-cn", name: "陶氏有机硅(上海)有限公司", nameEn: "DowSil (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["脱模剂","硅油","硅烷"], productsEn: ["Mold release","Silicone oil","Silanes"],
    description: "Dow 有机硅业务在华，复材脱模剂与硅烷主要供应商。", descriptionEn: "Dow Silicones China — composite release agents and silanes.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "ad-arkema-additive", name: "阿科玛过氧化物(上海)有限公司", nameEn: "Arkema Peroxides (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["LUPEROX 过氧化物","固化引发剂"], productsEn: ["LUPEROX peroxides","Curing initiators"],
    description: "Arkema 子公司，UPR/VE 树脂用过氧化物引发剂主要供应商。", descriptionEn: "Arkema subsidiary — peroxide initiators for UPR/VE resin.",
    scaleTier: "L", brandPriority: 22 },
  { id: "ad-cabot-cn", name: "卡博特(中国)投资有限公司", nameEn: "Cabot (China) Investment Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["炭黑","气相二氧化硅","导电填料"], productsEn: ["Carbon black","Fumed silica","Conductive fillers"],
    description: "Cabot 在华业务，复材用炭黑、二氧化硅、导电助剂供应商。", descriptionEn: "Cabot China — carbon black, fumed silica and conductive additives for composites.",
    scaleTier: "XL", brandPriority: 22 },
  { id: "ad-haminster", name: "海明斯德谦(广州)精细化工有限公司", nameEn: "Haminster Deqian (Guangzhou) Fine Chemical Co., Ltd.", location: "广东广州", locationEn: "Guangzhou, Guangdong", province: "广东", category: "additive",
    products: ["流变助剂","防沉剂","触变剂"], productsEn: ["Rheology additives","Anti-settling","Thixotropic agents"],
    description: "Lubrizol 集团 Hamilton 精细化学在华业务，复材流变助剂。", descriptionEn: "Lubrizol Hamilton in China — composite rheology additives.",
    scaleTier: "L", brandPriority: 18 },
  { id: "ad-aurora-hangzhou", name: "杭州欧若拉新材料有限公司", nameEn: "Hangzhou Aurora New Materials Co., Ltd.", location: "浙江杭州", locationEn: "Hangzhou, Zhejiang", province: "浙江", category: "additive",
    products: ["复材脱模剂","内脱模剂","半永久脱模剂"], productsEn: ["Mold release","Internal release","Semi-permanent release"],
    description: "国产复材脱模剂主要厂家。", descriptionEn: "Domestic composite mold release leader.",
    scaleTier: "M", brandPriority: 14 },
  { id: "ad-jiangsu-fangyuan", name: "江苏方圆化工有限公司", nameEn: "Jiangsu Fangyuan Chemical Co., Ltd.", location: "江苏南京", locationEn: "Nanjing, Jiangsu", province: "江苏", category: "additive",
    products: ["增稠剂","触变剂","UPR 助剂"], productsEn: ["Thickeners","Thixotropic","UPR additives"],
    description: "UPR/VE 树脂助剂中等规模供应商。", descriptionEn: "UPR/VE resin additives mid-scale supplier.",
    scaleTier: "M", brandPriority: 12 },
  { id: "ad-shandong-interlink", name: "山东英特力新材料有限公司", nameEn: "Shandong Interlink New Materials Co., Ltd.", location: "山东淄博", locationEn: "Zibo, Shandong", province: "山东", category: "additive",
    products: ["硅烷偶联剂","硅烷","表面处理剂"], productsEn: ["Silane couplers","Silanes","Surface treatments"],
    description: "国产硅烷偶联剂头部厂家之一。", descriptionEn: "Domestic silane coupler agent major.",
    scaleTier: "L", brandPriority: 18 },
  { id: "ad-zhejiang-lisen", name: "浙江力森化工有限公司", nameEn: "Zhejiang Lisen Chemical Co., Ltd.", location: "浙江绍兴", locationEn: "Shaoxing, Zhejiang", province: "浙江", category: "additive",
    products: ["分散剂","乳化剂","表面活性剂"], productsEn: ["Dispersants","Emulsifiers","Surfactants"],
    description: "复材分散剂、乳化剂中等规模供应商。", descriptionEn: "Mid-scale composite dispersant and emulsifier supplier.",
    scaleTier: "M", brandPriority: 12 },
  { id: "ad-beijing-tianqi", name: "北京天奇助剂有限公司", nameEn: "Beijing Tianqi Additives Co., Ltd.", location: "北京", locationEn: "Beijing", province: "北京", category: "additive",
    products: ["过氧化物","促进剂","复材引发剂"], productsEn: ["Peroxides","Accelerators","Initiators"],
    description: "国产过氧化物固化剂厂家。", descriptionEn: "Domestic peroxide curing agent maker.",
    scaleTier: "M", brandPriority: 12 },
  { id: "ad-shanghai-dexing", name: "上海德兴化工有限公司", nameEn: "Shanghai Dexing Chemical Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["硅烷偶联剂","钛酸酯","表面处理剂"], productsEn: ["Silane couplers","Titanate","Surface treatments"],
    description: "硅烷与钛酸酯偶联剂厂家。", descriptionEn: "Silane and titanate coupler maker.",
    scaleTier: "M", brandPriority: 12 },
  { id: "ad-fosrice-shanghai", name: "福斯瑞特种化学品(上海)有限公司", nameEn: "Forsec Specialty Chemicals (Shanghai) Co., Ltd.", location: "上海", locationEn: "Shanghai", province: "上海", category: "additive",
    products: ["脱模剂","清洗剂","半永久涂层"], productsEn: ["Release agents","Cleaners","Semi-permanent coatings"],
    description: "复材脱模与模具维护方案专业供应商。", descriptionEn: "Composite release and mold-maintenance specialist.",
    scaleTier: "M", brandPriority: 12 },
  { id: "ad-suzhou-luoxier", name: "苏州洛希尔新材料有限公司", nameEn: "Suzhou Loxir New Materials Co., Ltd.", location: "江苏苏州", locationEn: "Suzhou, Jiangsu", province: "江苏", category: "additive",
    products: ["阻燃剂","防腐助剂","UV 稳定剂"], productsEn: ["Flame retardants","Anti-corrosion","UV stabilizers"],
    description: "复材专用阻燃与功能助剂厂家。", descriptionEn: "Composite-grade flame retardant and functional additive supplier.",
    scaleTier: "M", brandPriority: 10 },
  { id: "ad-hebei-jingxin", name: "河北精信化工有限公司", nameEn: "Hebei Jingxin Chemical Co., Ltd.", location: "河北衡水", locationEn: "Hengshui, Hebei", province: "河北", category: "additive",
    products: ["UPR 引发剂","促进剂","抑制剂"], productsEn: ["UPR initiators","Accelerators","Inhibitors"],
    description: "UPR 树脂用引发剂细分供应商。", descriptionEn: "UPR resin initiator niche supplier.",
    scaleTier: "S", brandPriority: 8 },
  { id: "ad-anshan-titanium", name: "鞍钢钛白(辽宁)有限公司", nameEn: "Anshan Steel Titanium Dioxide (Liaoning) Co., Ltd.", location: "辽宁鞍山", locationEn: "Anshan, Liaoning", province: "辽宁", category: "additive",
    products: ["二氧化钛","钛白粉","填料"], productsEn: ["Titanium dioxide","TiO2 pigment","Fillers"],
    description: "鞍钢集团旗下钛白粉，复材白色颜料填料。", descriptionEn: "Ansteel Group's TiO2 — composite pigment and filler.",
    scaleTier: "L", brandPriority: 18 },
  { id: "ad-lomon-billions", name: "龙蟒佰利联集团股份有限公司", nameEn: "Lomon Billions Group Co., Ltd.", location: "河南焦作", locationEn: "Jiaozuo, Henan", province: "河南", category: "additive",
    products: ["金红石钛白粉","锐钛型钛白粉","海绵钛"], productsEn: ["Rutile TiO2","Anatase TiO2","Titanium sponge"],
    description: "国内最大钛白粉企业，上市公司。", descriptionEn: "Largest domestic TiO2 producer, listed.",
    scaleTier: "XL", brandPriority: 24 },

  // ════════════════════════════════════════════════════════════════════
  // 制品厂 manufacturer — wind blades, aerospace, automotive, marine, rail
  // ════════════════════════════════════════════════════════════════════
  { id: "mf-mingyang-blade", name: "明阳智能能源集团叶片事业部", nameEn: "Mingyang Smart Energy — Blade Division", location: "广东中山", locationEn: "Zhongshan, Guangdong", province: "广东", category: "manufacturer",
    products: ["陆上风电叶片","海上风电叶片","超大叶片"], productsEn: ["Onshore wind blades","Offshore wind blades","XXL blades"],
    description: "明阳智能集团下属叶片业务，海上风电大叶片国内引领者。", descriptionEn: "Mingyang Smart Energy's blade arm — domestic offshore XXL blade leader.",
    scaleTier: "XL", brandPriority: 28 },
  { id: "mf-dongfang-blade", name: "东方电气风电叶片有限公司", nameEn: "Dongfang Wind Blade Co., Ltd.", location: "四川天府新区", locationEn: "Tianfu New Area, Sichuan", province: "四川", category: "manufacturer",
    products: ["陆上风电叶片","海上风电叶片"], productsEn: ["Onshore wind blades","Offshore wind blades"],
    description: "东方电气集团子公司，国内风电叶片头部厂商。", descriptionEn: "Dongfang Electric subsidiary — domestic wind blade leader.",
    scaleTier: "XL", brandPriority: 25 },
  { id: "mf-haizhuang-blade", name: "重庆海装风电叶片工厂", nameEn: "Chongqing Haizhuang Wind Blade Plant", location: "重庆", locationEn: "Chongqing", province: "重庆", category: "manufacturer",
    products: ["陆上风电叶片","风机塔筒","风电零部件"], productsEn: ["Onshore wind blades","Wind tower","Wind components"],
    description: "中国船舶集团旗下海装风电叶片业务。", descriptionEn: "CSSC Haizhuang's wind blade arm.",
    scaleTier: "L", brandPriority: 20 },
  { id: "mf-xinjiang-jinfeng-blade", name: "金风科技风电叶片事业部", nameEn: "Goldwind — Wind Blade Division", location: "新疆乌鲁木齐", locationEn: "Urumqi, Xinjiang", province: "新疆", category: "manufacturer",
    products: ["风电叶片","直驱风机叶片"], productsEn: ["Wind blades","Direct-drive blades"],
    description: "金风科技集团叶片业务。", descriptionEn: "Goldwind Group's blade business.",
    scaleTier: "XL", brandPriority: 25 },
  { id: "mf-haerwind-blade", name: "哈电风能叶片厂", nameEn: "Harbin Electric Wind Blade Plant", location: "黑龙江哈尔滨", locationEn: "Harbin, Heilongjiang", province: "黑龙江", category: "manufacturer",
    products: ["风电叶片","风机零部件"], productsEn: ["Wind blades","Wind parts"],
    description: "哈尔滨电气集团下属风电叶片厂。", descriptionEn: "Harbin Electric Group's wind blade plant.",
    scaleTier: "L", brandPriority: 18 },
  { id: "mf-united-power", name: "国电联合动力技术有限公司", nameEn: "Guodian United Power Technology Co., Ltd.", location: "北京", locationEn: "Beijing", province: "北京", category: "manufacturer",
    products: ["风电整机及叶片","海上风电"], productsEn: ["Wind turbines + blades","Offshore wind"],
    description: "国家能源集团旗下风电整机及叶片厂商。", descriptionEn: "China Energy Group's wind OEM and blade maker.",
    scaleTier: "L", brandPriority: 18 },
  { id: "mf-shenfei-comac-cf", name: "沈飞复合材料有限公司", nameEn: "Shenfei Composite Materials Co., Ltd.", location: "辽宁沈阳", locationEn: "Shenyang, Liaoning", province: "辽宁", category: "manufacturer",
    products: ["航空复材结构件","机翼蒙皮","复合材料零部件"], productsEn: ["Aerospace composite structures","Wing skins","CF components"],
    description: "中航工业沈飞集团复材业务，国产军/民航复材主要厂商。", descriptionEn: "AVIC Shenfei's composite business — domestic military/civil aerospace CF major.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "mf-haf-cf", name: "哈飞复合材料技术有限公司", nameEn: "Hafei Composite Technology Co., Ltd.", location: "黑龙江哈尔滨", locationEn: "Harbin, Heilongjiang", province: "黑龙江", category: "manufacturer",
    products: ["直升机复材桨叶","机身复材","蒙皮"], productsEn: ["Helicopter rotor blades","Fuselage composites","Skins"],
    description: "中航工业哈尔滨飞机复材子公司。", descriptionEn: "AVIC Harbin Aircraft's composite subsidiary.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "mf-rail-changchun", name: "中车长春轨道客车股份有限公司复材事业部", nameEn: "CRRC Changchun Rail Vehicles — Composite Division", location: "吉林长春", locationEn: "Changchun, Jilin", province: "吉林", category: "manufacturer",
    products: ["轨道车辆复材车体","内饰件","车头罩"], productsEn: ["Rail vehicle composite bodies","Interior parts","Front nose"],
    description: "中车长客集团复材事业部，高铁与城轨车辆复材结构件。", descriptionEn: "CRRC Changchun's composite division — HSR and metro composite parts.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "mf-zhuzhou-rail-comp", name: "中车株洲电力机车有限公司复材事业部", nameEn: "CRRC Zhuzhou Electric Locomotive — Composite Division", location: "湖南株洲", locationEn: "Zhuzhou, Hunan", province: "湖南", category: "manufacturer",
    products: ["机车复材内饰","受电弓复材","转向架复材"], productsEn: ["Locomotive composite interior","Pantograph composites","Bogie composites"],
    description: "中车株洲电力机车集团复材事业部。", descriptionEn: "CRRC Zhuzhou Electric Locomotive's composite division.",
    scaleTier: "L", brandPriority: 20 },
  { id: "mf-haihong-yacht", name: "海宏游艇制造(青岛)有限公司", nameEn: "Haihong Yacht Manufacturing (Qingdao) Co., Ltd.", location: "山东青岛", locationEn: "Qingdao, Shandong", province: "山东", category: "manufacturer",
    products: ["玻璃钢游艇","钓鱼艇","巡逻艇"], productsEn: ["FRP yachts","Fishing boats","Patrol boats"],
    description: "青岛地区主要玻璃钢游艇制造企业。", descriptionEn: "Major FRP yacht builder in Qingdao.",
    scaleTier: "M", brandPriority: 14 },
  { id: "mf-haixing-yacht", name: "海星游艇集团有限公司", nameEn: "Haixing Yacht Group Co., Ltd.", location: "广东珠海", locationEn: "Zhuhai, Guangdong", province: "广东", category: "manufacturer",
    products: ["豪华游艇","商务游艇","定制船艇"], productsEn: ["Luxury yachts","Business yachts","Custom boats"],
    description: "珠海地区主要玻璃钢游艇集团。", descriptionEn: "Major FRP yacht group in Zhuhai.",
    scaleTier: "M", brandPriority: 14 },
  { id: "mf-zhejiang-huaxin", name: "浙江华信船业有限公司", nameEn: "Zhejiang Huaxin Shipping Co., Ltd.", location: "浙江温州", locationEn: "Wenzhou, Zhejiang", province: "浙江", category: "manufacturer",
    products: ["FRP 工作船","渔船","救生艇"], productsEn: ["FRP workboats","Fishing vessels","Lifeboats"],
    description: "温州 FRP 船艇制造企业。", descriptionEn: "Wenzhou FRP boat manufacturer.",
    scaleTier: "M", brandPriority: 10 },
  { id: "mf-aerospace-tianniao", name: "江苏天鸟高新技术股份有限公司", nameEn: "Jiangsu Tianbird High-Tech Co., Ltd.", location: "江苏宜兴", locationEn: "Yixing, Jiangsu", province: "江苏", category: "manufacturer",
    products: ["碳/碳预制体","碳纤维针刺织物","C/C 复合材料"], productsEn: ["Carbon/carbon preforms","Needle-punched CF","C/C composites"],
    description: "国内碳/碳复合材料预制体细分龙头，上市公司。", descriptionEn: "Listed domestic C/C composite preform leader.",
    scaleTier: "L", brandPriority: 22 },
  { id: "mf-zhenjiang-chuangmei", name: "镇江创美复合材料有限公司", nameEn: "Zhenjiang Chuangmei Composite Materials Co., Ltd.", location: "江苏镇江", locationEn: "Zhenjiang, Jiangsu", province: "江苏", category: "manufacturer",
    products: ["拉挤型材","建筑复材","格栅"], productsEn: ["Pultruded profiles","Construction composites","Grating"],
    description: "拉挤型材细分主要厂家。", descriptionEn: "Pultruded profile niche manufacturer.",
    scaleTier: "M", brandPriority: 12 },
  { id: "mf-shandong-shuangyi-new", name: "山东双一新材料股份有限公司", nameEn: "Shandong Shuangyi New Materials Co., Ltd.", location: "山东济宁", locationEn: "Jining, Shandong", province: "山东", category: "manufacturer",
    products: ["复材结构件","风电零部件","SMC/BMC 制品"], productsEn: ["Composite structures","Wind components","SMC/BMC parts"],
    description: "山东双一集团下属新材料公司。", descriptionEn: "Shandong Shuangyi Group's new materials subsidiary.",
    scaleTier: "L", brandPriority: 16 },

  // ════════════════════════════════════════════════════════════════════
  // 检测/工装 tooling — major foreign + missing
  // ════════════════════════════════════════════════════════════════════
  { id: "tl-olympus-cn", name: "奥林巴斯(中国)无损检测", nameEn: "Olympus (China) NDT Solutions", location: "北京", locationEn: "Beijing", province: "北京", category: "tooling",
    products: ["相控阵超声","涡流检测","X 射线设备"], productsEn: ["Phased-array UT","Eddy current","X-ray equipment"],
    description: "Evident（原 Olympus NDT）在华无损检测设备业务。", descriptionEn: "Evident (former Olympus NDT) — NDT equipment China business.",
    scaleTier: "XL", brandPriority: 26 },
  { id: "tl-waygate-ge", name: "Waygate(GE 检测科技)上海", nameEn: "Waygate Technologies (GE Inspection) Shanghai", location: "上海", locationEn: "Shanghai", province: "上海", category: "tooling",
    products: ["X 射线 CT","超声","内窥镜"], productsEn: ["X-ray CT","Ultrasound","Borescopes"],
    description: "Baker Hughes 旗下 Waygate（GE 检测科技）在华业务，X 射线 CT 行业龙头。", descriptionEn: "Baker Hughes Waygate (former GE Inspection) — X-ray CT leader.",
    scaleTier: "XL", brandPriority: 24 },
  { id: "tl-shenghua-ndt", name: "北京声华兴业科技有限公司", nameEn: "Beijing Shenghua Xingye Technology Co., Ltd.", location: "北京", locationEn: "Beijing", province: "北京", category: "tooling",
    products: ["国产无损检测仪","超声探伤","声发射检测"], productsEn: ["Domestic NDT instruments","UT flaw detector","AE testing"],
    description: "国产无损检测设备主要厂家。", descriptionEn: "Domestic NDT equipment major.",
    scaleTier: "M", brandPriority: 14 },
  { id: "tl-suzhou-shili", name: "苏州实力新材检测装备有限公司", nameEn: "Suzhou Shili New Material Testing Equipment Co., Ltd.", location: "江苏苏州", locationEn: "Suzhou, Jiangsu", province: "江苏", category: "tooling",
    products: ["复材力学测试","DMA 仪","TMA 仪"], productsEn: ["Composite mechanical testing","DMA","TMA"],
    description: "复材力学和热分析测试装备国产厂家。", descriptionEn: "Domestic composite mechanical/thermal test equipment maker.",
    scaleTier: "M", brandPriority: 12 },
];

async function main() {
  let inserted = 0;
  let skipped = 0;
  for (const r of ROWS) {
    const result = await db.execute(sql`
      INSERT INTO supplier_listings (
        id, name, name_en, location, location_en, province, category,
        products, products_en, description, description_en, established,
        scale_tier, brand_priority, verified
      ) VALUES (
        ${r.id}, ${r.name}, ${r.nameEn}, ${r.location}, ${r.locationEn}, ${r.province}, ${r.category},
        ${JSON.stringify(r.products)}::jsonb, ${JSON.stringify(r.productsEn)}::jsonb,
        ${r.description ?? null}, ${r.descriptionEn ?? null}, ${r.established ?? null},
        ${r.scaleTier}, ${r.brandPriority}, ${r.verified ?? true}
      )
      ON CONFLICT (id) DO NOTHING
      RETURNING id
    `);
    if (result.rows.length) inserted++;
    else skipped++;
  }
  const total = await db.execute(sql`SELECT count(*)::int FROM supplier_listings`);
  const byCategory = await db.execute(sql`SELECT category, count(*)::int FROM supplier_listings GROUP BY category ORDER BY count(*) DESC`);
  const byTier = await db.execute(sql`SELECT scale_tier, count(*)::int FROM supplier_listings GROUP BY scale_tier ORDER BY scale_tier`);
  console.log(`Inserted: ${inserted}, Skipped (already exists): ${skipped}, Total rows now: ${total.rows[0].count}`);
  console.log("By category:", byCategory.rows);
  console.log("By tier:", byTier.rows);
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
