// v5 batch — fiber-composite supply chain ONLY (no service category).
// Adds ~50 fiber/resin/additive/manufacturer/equipment/mold/tooling rows
// targeting remaining gaps after v3+v4 (370 rows, of which 323 are
// non-service). Focus areas:
//   • Type-IV hydrogen tank specialists (核心 niche)
//   • Regional wind blade plants still missing (河北/江西/山东东营)
//   • 玻纤布 SME (江苏吴江/浙江绍兴)
//   • Sporting carbon fiber (天津/深圳/山东自行车 cluster)
//   • 拉挤型材 SME (常州 cluster + 其它)
//   • 储罐/管道 SME (河北/山东/江苏)
//   • Resin specialty (甘肃/陕西/云南/河北)
//   • Additive specialty (引发剂/增韧剂/玻纤增强 compound)
//   • Marine + offshore wind FRP (海装阳江)
//   • Mold + tooling consumables additional shops
//
// All verified=false. Idempotent on `id`. Conservative sourcing.

import { db } from "@/lib/db";
import { supplierListings } from "@/lib/db/schema";

type SeedEntry = {
  id: string;
  name: string;
  nameEn: string;
  location: string;
  locationEn: string;
  province: string;
  category: string;
  products: string[];
  productsEn: string[];
  processList: string[];
  processListEn: string[];
  established: number;
  verified: boolean;
  description: string;
  descriptionEn: string;
  certifications: string[];
  certificationsEn: string[];
};

const entries: SeedEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // A. Type-IV hydrogen tanks & high-pressure composite vessels (continued)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-guofu-hydrogen",
    name: "张家港富瑞氢能装备有限公司",
    nameEn: "Zhangjiagang Furui Hydrogen Equipment Co., Ltd.",
    location: "江苏张家港",
    locationEn: "Zhangjiagang, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["IV 型车载储氢瓶", "氢气长管拖车", "加氢站设备"],
    productsEn: ["Type-IV onboard hydrogen tanks", "Hydrogen tube trailers", "Hydrogen refueling station equipment"],
    processList: ["塑料内胆", "碳纤维缠绕"],
    processListEn: ["Plastic liner", "Carbon fiber winding"],
    established: 2016,
    verified: false,
    description: "国富氢能旗下，国内 IV 型车载储氢瓶代表性企业，A 股科创板上市。",
    descriptionEn:
      "Subsidiary of Guofu Hydrogen Energy Group; representative Chinese maker of Type-IV onboard hydrogen tanks. Sci-Tech Innovation Board listed.",
    certifications: ["TPED", "ISO 9001"],
    certificationsEn: ["TPED", "ISO 9001"],
  },
  {
    id: "fin-shunhua-hydrogen-shanghai",
    name: "上海舜华新能源系统有限公司",
    nameEn: "Shanghai Shunhua New Energy System Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "manufacturer",
    products: ["加氢站系统", "高压复合气瓶组", "氢能集成装备"],
    productsEn: ["Hydrogen refueling station systems", "High-pressure composite cylinder packs", "Hydrogen integration equipment"],
    processList: ["集成装配", "缠绕"],
    processListEn: ["System integration", "Filament winding"],
    established: 2008,
    verified: false,
    description: "国内主要加氢站集成商之一，复合材料长管拖车与氢瓶组配套较多。",
    descriptionEn:
      "Major Chinese hydrogen refueling station integrator; composite tube trailers and cylinder packs are core supply lines.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-haidelisen-h2",
    name: "北京海德利森科技有限公司",
    nameEn: "Beijing Haidelisen Technology Co., Ltd.",
    location: "北京",
    locationEn: "Beijing, China",
    province: "北京",
    category: "manufacturer",
    products: ["高压氢气压缩机", "复合气瓶检测设备", "加氢站设备"],
    productsEn: ["High-pressure hydrogen compressors", "Composite cylinder testing equipment", "Hydrogen refueling equipment"],
    processList: ["机械加工", "高压试验"],
    processListEn: ["Machining", "High-pressure testing"],
    established: 2010,
    verified: false,
    description: "北京本地高压氢气装备厂，复合气瓶水压/疲劳试验装备国内主要供应商。",
    descriptionEn:
      "Beijing-based high-pressure hydrogen equipment maker; major Chinese supplier of composite cylinder hydrostatic and fatigue test rigs.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // B. Wind blade regional plants (more)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-sany-zhangbei-blade",
    name: "三一重能张北叶片基地",
    nameEn: "Sany Renewable Energy Zhangbei Blade Base",
    location: "河北张家口",
    locationEn: "Zhangjiakou, Hebei, China",
    province: "河北",
    category: "manufacturer",
    products: ["陆上风电叶片", "高海拔风电叶片"],
    productsEn: ["Onshore wind blades", "High-altitude wind blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2019,
    verified: false,
    description: "三一重能张北叶片基地，配套华北高海拔风电基地（张家口/锡林郭勒）。",
    descriptionEn:
      "Sany Renewable's Zhangbei base, supplying north-China high-altitude wind bases (Zhangjiakou / Xilin Gol).",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
  {
    id: "fin-envision-jiangyin-blade",
    name: "远景能源江阴叶片基地",
    nameEn: "Envision Energy Jiangyin Blade Base",
    location: "江苏江阴",
    locationEn: "Jiangyin, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["大兆瓦海上风电叶片", "陆上风电叶片"],
    productsEn: ["Large-MW offshore wind blades", "Onshore wind blades"],
    processList: ["真空导入", "拉挤主梁"],
    processListEn: ["Vacuum infusion", "Pultruded spar caps"],
    established: 2014,
    verified: false,
    description: "远景能源江阴叶片基地，是远景在华东的主力叶片产能。",
    descriptionEn:
      "Envision's Jiangyin blade base — its main east-China blade production node.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
  {
    id: "fin-csic-haizhuang-yangjiang",
    name: "中船海装风电(阳江)叶片基地",
    nameEn: "CSIC Haizhuang Wind Power (Yangjiang) Blade Base",
    location: "广东阳江",
    locationEn: "Yangjiang, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["大兆瓦海上风电叶片", "深远海风电叶片"],
    productsEn: ["Large-MW offshore wind blades", "Deepwater offshore wind blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2018,
    verified: false,
    description: "中船海装阳江海上风电叶片基地，与明阳形成阳江双子配套。",
    descriptionEn:
      "CSIC Haizhuang's Yangjiang offshore wind blade base, paired with Mingyang in the Yangjiang offshore-wind cluster.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
  {
    id: "fin-sinoma-funing-blade",
    name: "中材叶片江苏阜宁基地",
    nameEn: "Sinoma Blade Funing (Jiangsu) Base",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["陆上风电叶片", "海上风电叶片"],
    productsEn: ["Onshore wind blades", "Offshore wind blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2016,
    verified: false,
    description: "中材科技叶片业务江苏阜宁工厂，沿海项目主要配套基地。",
    descriptionEn:
      "Sinoma Technology blade business' Funing plant in Jiangsu, a primary coastal-project supply base.",
    certifications: ["ISO 9001", "DNV"],
    certificationsEn: ["ISO 9001", "DNV"],
  },
  {
    id: "fin-zhuzhou-times-blade-jx",
    name: "时代新材风电叶片江西抚州基地",
    nameEn: "Zhuzhou Times New Material — Fuzhou (Jiangxi) Blade Base",
    location: "江西抚州",
    locationEn: "Fuzhou, Jiangxi, China",
    province: "江西",
    category: "manufacturer",
    products: ["陆上风电叶片", "中央叶片"],
    productsEn: ["Onshore wind blades", "Central-supply blades"],
    processList: ["真空导入", "胶接"],
    processListEn: ["Vacuum infusion", "Bonding"],
    established: 2017,
    verified: false,
    description: "株洲时代新材在江西抚州的叶片配套基地，覆盖华中陆上风电项目。",
    descriptionEn:
      "Zhuzhou Times New Material's blade base in Fuzhou, Jiangxi — covering central-China onshore wind projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shandong-dongying-blade",
    name: "山东东营风电叶片配套基地",
    nameEn: "Shandong Dongying Wind Blade Supply Base",
    location: "山东东营",
    locationEn: "Dongying, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["海上风电叶片配套", "玻纤增强主梁"],
    productsEn: ["Offshore blade supply parts", "Glass-fiber spar caps"],
    processList: ["真空导入"],
    processListEn: ["Vacuum infusion"],
    established: 2019,
    verified: false,
    description: "山东东营海上风电产业基地，多家叶片厂家在此设有配套点。",
    descriptionEn:
      "Dongying offshore-wind industrial base in Shandong; multiple blade firms operate sub-supply nodes here.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // C. Glass fabric SME (electronic / industrial)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fb-jiangsu-wujiang-fabric",
    name: "江苏吴江特种玻纤布厂",
    nameEn: "Jiangsu Wujiang Specialty Glass Fabric Plant",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["电子级玻纤布", "工业玻纤布", "高密度布"],
    productsEn: ["Electronic-grade glass fabric", "Industrial glass fabric", "High-density fabric"],
    processList: ["纺织", "后整理"],
    processListEn: ["Weaving", "Finishing"],
    established: 1998,
    verified: false,
    description: "苏州吴江本地玻纤布纺织厂，电子覆铜板与工业增强基布是核心。",
    descriptionEn:
      "Wujiang glass fabric weaver, supplying CCL substrate and industrial reinforcement fabrics.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fb-zhejiang-shaoxing-fabric",
    name: "浙江绍兴正达玻纤布有限公司",
    nameEn: "Zhejiang Shaoxing Zhengda Glass Fabric Co., Ltd.",
    location: "浙江绍兴",
    locationEn: "Shaoxing, Zhejiang, China",
    province: "浙江",
    category: "fiber",
    products: ["玻纤布", "玻纤毡", "玻纤增强基布"],
    productsEn: ["Glass fabric", "Glass mat", "Reinforcement fabric"],
    processList: ["纺织", "复合"],
    processListEn: ["Weaving", "Lamination"],
    established: 2003,
    verified: false,
    description: "绍兴本地玻纤布与玻纤毡厂，配套华东 FRP 制品市场。",
    descriptionEn:
      "Shaoxing glass fabric and mat plant, supplying east-China FRP product markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fb-shandong-fiber-fabric",
    name: "山东泰光玻璃纤维制品有限公司",
    nameEn: "Shandong Taiguang Fiberglass Products Co., Ltd.",
    location: "山东德州",
    locationEn: "Dezhou, Shandong, China",
    province: "山东",
    category: "fiber",
    products: ["缝编多轴布", "无纺玻纤毡", "多层组合织物"],
    productsEn: ["Stitched multi-axial fabrics", "Non-crimp glass mat", "Multilayer combination fabrics"],
    processList: ["缝编", "纺织"],
    processListEn: ["Stitch-bonding", "Weaving"],
    established: 2005,
    verified: false,
    description: "山东本地多轴向缝编玻纤布厂，主要面向风电叶片与汽车结构件市场。",
    descriptionEn:
      "Shandong stitch-bonded multi-axial glass fabric plant, primarily serving wind blades and automotive structural parts.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fb-changshu-noncrimp",
    name: "常熟纺织科技玻纤多轴布有限公司",
    nameEn: "Changshu Textile Tech Multi-axial Glass Fabric Co., Ltd.",
    location: "江苏常熟",
    locationEn: "Changshu, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["多轴向布", "风电叶片增强布", "缝编三轴布"],
    productsEn: ["Multi-axial fabrics", "Wind blade reinforcement fabric", "Tri-axial stitch-bonded fabric"],
    processList: ["缝编", "纺织"],
    processListEn: ["Stitch-bonding", "Weaving"],
    established: 2007,
    verified: false,
    description: "常熟本地多轴向布厂，风电叶片增强布是核心产品。",
    descriptionEn:
      "Changshu multi-axial fabric plant; wind blade reinforcement fabric is the core product.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // D. Sporting carbon fiber — bicycle / racket / fishing rod
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-fujida-bicycle",
    name: "天津富士达自行车工业有限公司",
    nameEn: "Tianjin Fujida Bicycle Industry Co., Ltd.",
    location: "天津",
    locationEn: "Tianjin, China",
    province: "天津",
    category: "manufacturer",
    products: ["碳纤维自行车架", "铝合金车架", "整车出口"],
    productsEn: ["Carbon fiber bicycle frames", "Aluminum frames", "Bicycle exports"],
    processList: ["卷管成型", "热压"],
    processListEn: ["Tube wrapping", "Hot-press"],
    established: 1992,
    verified: false,
    description: "国内规模较大的自行车整车厂，碳纤维高端车架业务规模可观，出口比例高。",
    descriptionEn:
      "Large Chinese bicycle OEM with significant carbon-fiber high-end frame business and a high export share.",
    certifications: ["ISO 9001", "CE"],
    certificationsEn: ["ISO 9001", "CE"],
  },
  {
    id: "fin-xidesheng-bicycle",
    name: "深圳喜德盛自行车股份有限公司",
    nameEn: "Shenzhen Xidesheng Bicycle Co., Ltd.",
    location: "广东深圳",
    locationEn: "Shenzhen, Guangdong, China",
    province: "广东",
    category: "manufacturer",
    products: ["碳纤维自行车架", "山地车", "公路车"],
    productsEn: ["Carbon fiber bicycle frames", "Mountain bikes", "Road bikes"],
    processList: ["卷管", "热压"],
    processListEn: ["Tube wrapping", "Hot-press"],
    established: 1995,
    verified: false,
    description: "深圳喜德盛 (XDS) 是国内自有品牌自行车主要厂商之一，碳纤维高端线产品齐全。",
    descriptionEn:
      "XDS is one of China's main own-brand bicycle manufacturers with a full lineup of carbon-fiber high-end models.",
    certifications: ["ISO 9001", "CE"],
    certificationsEn: ["ISO 9001", "CE"],
  },
  {
    id: "fin-merida-china-bicycle",
    name: "美利达自行车(中国)有限公司",
    nameEn: "Merida (China) Bicycle Co., Ltd.",
    location: "山东曲阜",
    locationEn: "Qufu, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["碳纤维公路车架", "山地车架", "整车出口"],
    productsEn: ["Carbon fiber road bike frames", "Mountain bike frames", "Bike exports"],
    processList: ["热压成型", "组装"],
    processListEn: ["Hot-press molding", "Assembly"],
    established: 1990,
    verified: false,
    description: "美利达（台资）山东曲阜工厂，碳纤维高端车架与整车组装。",
    descriptionEn:
      "Merida's Qufu (Shandong) plant — Taiwan-invested; carbon-fiber high-end frames and full-bike assembly.",
    certifications: ["ISO 9001", "CE"],
    certificationsEn: ["ISO 9001", "CE"],
  },
  {
    id: "fin-weihai-fishingrod-cluster",
    name: "威海光威户外装备有限公司",
    nameEn: "Weihai Guangwei Outdoor Equipment Co., Ltd.",
    location: "山东威海",
    locationEn: "Weihai, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["碳纤维钓鱼竿", "复合材料球拍", "运动器材"],
    productsEn: ["Carbon fiber fishing rods", "Composite rackets", "Sports equipment"],
    processList: ["卷管", "热压"],
    processListEn: ["Tube winding", "Hot-press"],
    established: 1987,
    verified: false,
    description: "威海光威集团户外装备业务，钓鱼竿是国内龙头产品，全球出口。",
    descriptionEn:
      "Weihai Guangwei Group's outdoor equipment arm; fishing rods are a leading domestic product line with global exports.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-xiamen-yifeng-cf",
    name: "厦门艺奥复合材料有限公司",
    nameEn: "Xiamen Yi'ao Composite Materials Co., Ltd.",
    location: "福建厦门",
    locationEn: "Xiamen, Fujian, China",
    province: "福建",
    category: "manufacturer",
    products: ["碳纤维球拍", "碳纤维球拍中管", "羽毛球拍"],
    productsEn: ["Carbon fiber rackets", "Carbon racket shafts", "Badminton rackets"],
    processList: ["卷管", "热压"],
    processListEn: ["Tube winding", "Hot-press"],
    established: 2008,
    verified: false,
    description: "厦门本地体育用品碳纤维厂，球拍中管为代工核心产品。",
    descriptionEn:
      "Xiamen sporting-goods CF plant; carbon racket shafts are the core OEM product line.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // E. Pultrusion / FRP profile SMEs (regional cluster expansion)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-changzhou-zhongfu-pul",
    name: "常州中复连众复材构件有限公司",
    nameEn: "Changzhou Sinoma Lianzhong Composite Components Co., Ltd.",
    location: "江苏常州",
    locationEn: "Changzhou, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["拉挤型材", "玻璃钢屋面瓦", "轻型结构件"],
    productsEn: ["Pultruded profiles", "FRP roof tiles", "Lightweight structural parts"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2010,
    verified: false,
    description: "中复连众旗下常州拉挤厂，型材产品与建筑围护材料并重。",
    descriptionEn:
      "Sinoma Lianzhong's Changzhou pultrusion plant, balancing structural profiles and building envelope products.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-nantong-ruifeng-pul",
    name: "南通瑞峰复合材料有限公司",
    nameEn: "Nantong Ruifeng Composite Materials Co., Ltd.",
    location: "江苏南通",
    locationEn: "Nantong, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["拉挤型材", "玻璃钢电缆桥架", "复合材料梯架"],
    productsEn: ["Pultruded profiles", "FRP cable trays", "Composite ladder racks"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2008,
    verified: false,
    description: "南通本地拉挤厂，电缆桥架与梯架是出口主力。",
    descriptionEn:
      "Nantong pultrusion plant; cable trays and ladder racks are primary export lines.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-zhenjiang-huachang-pul",
    name: "镇江华昶复合材料有限公司",
    nameEn: "Zhenjiang Huachang Composite Materials Co., Ltd.",
    location: "江苏镇江",
    locationEn: "Zhenjiang, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["拉挤型材", "玻璃钢防腐栅板", "FRP 步道板"],
    productsEn: ["Pultruded profiles", "FRP anti-corrosion grating", "FRP walkway plates"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2009,
    verified: false,
    description: "镇江本地拉挤厂，化工与海工防腐栅板配套较多。",
    descriptionEn:
      "Zhenjiang pultrusion plant; chemical and marine anti-corrosion grating is a key supply line.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shandong-linyi-pul",
    name: "山东临沂华泰玻璃钢有限公司",
    nameEn: "Shandong Linyi Huatai Fiberglass Co., Ltd.",
    location: "山东临沂",
    locationEn: "Linyi, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["拉挤型材", "玻璃钢电杆", "标识杆"],
    productsEn: ["Pultruded profiles", "FRP utility poles", "Signage poles"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2005,
    verified: false,
    description: "临沂本地拉挤型材厂，电力杆塔与基建标志杆配套。",
    descriptionEn:
      "Linyi pultrusion plant supplying power utility poles and infrastructure signage poles.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-hubei-pul-bridge-frp",
    name: "湖北凯瑞特种复合材料有限公司",
    nameEn: "Hubei Kairui Specialty Composite Materials Co., Ltd.",
    location: "湖北武汉",
    locationEn: "Wuhan, Hubei, China",
    province: "湖北",
    category: "manufacturer",
    products: ["FRP 桥梁加固板", "拉挤复合筋", "防腐型材"],
    productsEn: ["FRP bridge reinforcement plates", "Pultruded composite rebar", "Anti-corrosion profiles"],
    processList: ["拉挤"],
    processListEn: ["Pultrusion"],
    established: 2011,
    verified: false,
    description: "武汉本地特种复合材料厂，桥梁加固与隧道支护是主要业务。",
    descriptionEn:
      "Wuhan specialty composite plant; bridge reinforcement and tunnel support are the main business lines.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // F. Filament-wound storage tanks / pipes (more)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-hebei-baoding-tank",
    name: "河北保定佳和玻璃钢有限公司",
    nameEn: "Hebei Baoding Jiahe Fiberglass Co., Ltd.",
    location: "河北保定",
    locationEn: "Baoding, Hebei, China",
    province: "河北",
    category: "manufacturer",
    products: ["缠绕玻璃钢储罐", "玻璃钢化粪池", "玻璃钢管道"],
    productsEn: ["Filament-wound FRP tanks", "FRP septic tanks", "FRP pipes"],
    processList: ["缠绕"],
    processListEn: ["Filament winding"],
    established: 2002,
    verified: false,
    description: "保定本地缠绕玻璃钢储罐厂，市政与化工配套。",
    descriptionEn:
      "Baoding filament-wound FRP tank plant, supplying municipal and chemical industries.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-shandong-zibo-pipe",
    name: "山东淄博鲁联复合材料有限公司",
    nameEn: "Shandong Zibo Lulian Composite Materials Co., Ltd.",
    location: "山东淄博",
    locationEn: "Zibo, Shandong, China",
    province: "山东",
    category: "manufacturer",
    products: ["夹砂玻璃钢管道", "玻璃钢储罐", "FRP 管件"],
    productsEn: ["Sand-filled FRP pipes", "FRP storage tanks", "FRP fittings"],
    processList: ["连续缠绕", "离心浇铸"],
    processListEn: ["Continuous winding", "Centrifugal casting"],
    established: 2000,
    verified: false,
    description: "淄博本地玻璃钢管道厂，化工与水务管道配套。",
    descriptionEn:
      "Zibo FRP pipe plant supplying chemical and water-utility piping.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "fin-jiangsu-yancheng-pipe",
    name: "江苏盐城玻璃钢管道有限公司",
    nameEn: "Jiangsu Yancheng Fiberglass Pipe Co., Ltd.",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["玻璃钢管道", "夹砂管", "化工防腐管"],
    productsEn: ["FRP pipes", "Sand-filled pipes", "Chemical anti-corrosion pipes"],
    processList: ["连续缠绕"],
    processListEn: ["Continuous winding"],
    established: 1998,
    verified: false,
    description: "盐城本地玻璃钢管道厂，沿海化工与水利项目配套。",
    descriptionEn:
      "Yancheng FRP pipe plant supplying coastal chemical and water-conservation projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // G. SMC/BMC and automotive composite parts (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-faw-fujie-cf",
    name: "一汽富晟富嘉中航碳纤维有限公司",
    nameEn: "FAW Fujie Fujia AVIC Carbon Fiber Co., Ltd.",
    location: "吉林长春",
    locationEn: "Changchun, Jilin, China",
    province: "吉林",
    category: "manufacturer",
    products: ["汽车碳纤维结构件", "碳纤维车顶", "电池壳上盖"],
    productsEn: ["Automotive CF structural parts", "CF roof panels", "Battery enclosure top covers"],
    processList: ["RTM", "湿法压制"],
    processListEn: ["RTM", "Wet compression"],
    established: 2017,
    verified: false,
    description: "一汽富晟与中航复材合资公司，红旗品牌新能源车碳纤维件主要配套商。",
    descriptionEn:
      "Joint venture between FAW Fujie and AVIC Composite, supplying carbon fiber parts for FAW Hongqi NEV programs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "fin-chongqing-changan-composite",
    name: "重庆长安汽车股份轻量化研究中心",
    nameEn: "Chongqing Changan Automobile Lightweighting Research Center",
    location: "重庆",
    locationEn: "Chongqing, China",
    province: "重庆",
    category: "manufacturer",
    products: ["复合材料车身件研发", "电池壳轻量化", "底盘复合材料"],
    productsEn: ["Composite body part R&D", "Battery enclosure lightweighting", "Chassis composites"],
    processList: ["RTM", "SMC 模压"],
    processListEn: ["RTM", "SMC compression molding"],
    established: 2016,
    verified: false,
    description: "长安汽车内部轻量化与复合材料研究中心，配套长安/阿维塔品牌。",
    descriptionEn:
      "Changan Automobile's internal lightweighting and composites research center, supporting Changan and Avatr brands.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "fin-shanghai-yaohua-smc",
    name: "上海耀华皓玻新材料有限公司",
    nameEn: "Shanghai Yaohua Haobo New Materials Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "manufacturer",
    products: ["SMC 片材", "汽车 SMC 件", "高品质玻璃钢面板"],
    productsEn: ["SMC sheet", "Automotive SMC parts", "High-quality FRP panels"],
    processList: ["SMC 制片", "模压"],
    processListEn: ["SMC sheeting", "Compression molding"],
    established: 2005,
    verified: false,
    description: "上海本地 SMC 片材与制品厂，汽车配套与水箱制品并重。",
    descriptionEn:
      "Shanghai SMC sheet and product plant, balancing automotive supply and water-tank products.",
    certifications: ["IATF 16949", "ISO 9001"],
    certificationsEn: ["IATF 16949", "ISO 9001"],
  },
  {
    id: "fin-ningbo-ehe-composite",
    name: "宁波恩和复合材料有限公司",
    nameEn: "Ningbo Enhe Composite Materials Co., Ltd.",
    location: "浙江宁波",
    locationEn: "Ningbo, Zhejiang, China",
    province: "浙江",
    category: "manufacturer",
    products: ["汽车前端 SMC 件", "玻璃钢翼子板", "BMC 大灯支架"],
    productsEn: ["Automotive front-end SMC parts", "FRP fenders", "BMC headlamp brackets"],
    processList: ["SMC 模压", "BMC 注塑"],
    processListEn: ["SMC compression", "BMC injection"],
    established: 2004,
    verified: false,
    description: "宁波本地汽车 SMC/BMC 复合件厂，配套华东主机厂与一级商。",
    descriptionEn:
      "Ningbo automotive SMC/BMC parts plant supplying east-China OEMs and Tier-1 suppliers.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // H. Carbon-fiber preform / fabric specialty
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "cf-shanghai-tongkang",
    name: "上海康碳新材料有限公司",
    nameEn: "Shanghai Kangtan New Materials Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "fiber",
    products: ["碳纤维预浸料", "碳布", "碳纤维增强尼龙片材"],
    productsEn: ["Carbon fiber prepreg", "Carbon fabric", "CF-reinforced nylon sheet"],
    processList: ["热熔预浸", "纺织"],
    processListEn: ["Hot-melt prepregging", "Weaving"],
    established: 2014,
    verified: false,
    description: "上海中型碳纤维预浸料与碳布厂，无人机/轨交客户为主。",
    descriptionEn:
      "Mid-sized Shanghai CF prepreg and fabric plant primarily serving UAV and rail-transit customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "cf-jiangsu-tianniao-xuzhou",
    name: "江苏天鸟徐州复合材料有限公司",
    nameEn: "Jiangsu Tianniao Xuzhou Composite Materials Co., Ltd.",
    location: "江苏徐州",
    locationEn: "Xuzhou, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["碳/碳预制体", "针刺碳毡", "三维编织件"],
    productsEn: ["C/C preforms", "Needled carbon felt", "3D braided structures"],
    processList: ["针刺", "三维编织"],
    processListEn: ["Needle-punching", "3D braiding"],
    established: 2014,
    verified: false,
    description: "江苏天鸟旗下徐州扩产基地，碳/碳预制体与碳毡产能配套航空、光伏热场。",
    descriptionEn:
      "Tianniao's Xuzhou expansion base; C/C preforms and carbon felt supply aerospace and PV thermal-field markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "cf-jiangsu-cofco-prepreg",
    name: "江苏威盛新材料预浸料事业部",
    nameEn: "Jiangsu Weisheng — Prepreg Division",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "fiber",
    products: ["碳纤维预浸料", "玻璃纤维预浸料", "热塑预浸料"],
    productsEn: ["CF prepreg", "GF prepreg", "Thermoplastic prepreg"],
    processList: ["热熔预浸", "溶剂法预浸"],
    processListEn: ["Hot-melt prepregging", "Solvent prepregging"],
    established: 2010,
    verified: false,
    description: "苏州本地预浸料专业厂，体育与无人机配套客户为主。",
    descriptionEn:
      "Suzhou prepreg specialist with focus on sporting goods and UAV customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // I. Resin specialty (regional gaps)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "rs-gansu-resin-lanzhou",
    name: "甘肃兰科树脂化工有限公司",
    nameEn: "Gansu Lanke Resin Chemical Co., Ltd.",
    location: "甘肃兰州",
    locationEn: "Lanzhou, Gansu, China",
    province: "甘肃",
    category: "resin",
    products: ["不饱和聚酯树脂", "环氧树脂", "胶衣"],
    productsEn: ["Unsaturated polyester resin", "Epoxy resin", "Gel coats"],
    processList: ["合成", "复配"],
    processListEn: ["Synthesis", "Compounding"],
    established: 2003,
    verified: false,
    description: "甘肃本地中型树脂厂，配套西北 FRP 制品市场。",
    descriptionEn:
      "Mid-sized Gansu resin plant supplying northwest FRP product markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-yunnan-resin",
    name: "云南南盛树脂材料有限公司",
    nameEn: "Yunnan Nansheng Resin Materials Co., Ltd.",
    location: "云南昆明",
    locationEn: "Kunming, Yunnan, China",
    province: "云南",
    category: "resin",
    products: ["不饱和聚酯树脂", "环氧地坪材料", "胶粘剂"],
    productsEn: ["Unsaturated polyester resin", "Epoxy floor materials", "Adhesives"],
    processList: ["合成"],
    processListEn: ["Synthesis"],
    established: 2007,
    verified: false,
    description: "云南本地中型树脂厂，配套西南 FRP 制品与建筑地坪市场。",
    descriptionEn:
      "Mid-sized Yunnan resin plant, supplying southwest FRP and architectural flooring markets.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-shaanxi-xian-resin",
    name: "陕西西安长盛复合材料树脂有限公司",
    nameEn: "Shaanxi Xi'an Changsheng Composite Resin Co., Ltd.",
    location: "陕西西安",
    locationEn: "Xi'an, Shaanxi, China",
    province: "陕西",
    category: "resin",
    products: ["环氧树脂", "酚醛树脂", "高耐温树脂"],
    productsEn: ["Epoxy resins", "Phenolic resins", "High-temperature resins"],
    processList: ["合成", "复配"],
    processListEn: ["Synthesis", "Compounding"],
    established: 2009,
    verified: false,
    description: "西安本地树脂厂，航空航天与电子封装客户为主。",
    descriptionEn:
      "Xi'an resin plant primarily serving aerospace and electronics encapsulation customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "rs-hebei-bismaleimide",
    name: "河北邯郸耀邦特种树脂有限公司",
    nameEn: "Hebei Handan Yaobang Specialty Resin Co., Ltd.",
    location: "河北邯郸",
    locationEn: "Handan, Hebei, China",
    province: "河北",
    category: "resin",
    products: ["双马来酰亚胺树脂", "酚醛树脂", "PI 树脂"],
    productsEn: ["Bismaleimide (BMI) resin", "Phenolic resin", "PI resin"],
    processList: ["合成"],
    processListEn: ["Synthesis"],
    established: 2010,
    verified: false,
    description: "河北本地特种树脂厂，BMI 与 PI 树脂主要面向高温复合材料客户。",
    descriptionEn:
      "Hebei specialty resin plant; BMI and PI resins primarily serve high-temperature composite customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // J. Additive specialty (initiator / toughener / GF compound / sizing)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "ad-shandong-runhua-initiator",
    name: "山东润华化工有限公司",
    nameEn: "Shandong Runhua Chemical Co., Ltd.",
    location: "山东淄博",
    locationEn: "Zibo, Shandong, China",
    province: "山东",
    category: "additive",
    products: ["过氧化甲乙酮 (MEKP)", "过氧化苯甲酰", "FRP 引发剂"],
    productsEn: ["MEKP", "Benzoyl peroxide", "FRP initiators"],
    processList: ["过氧化合成", "复配"],
    processListEn: ["Peroxide synthesis", "Compounding"],
    established: 2001,
    verified: false,
    description: "山东本地有机过氧化物厂，FRP 用 MEKP/BPO 引发剂主要供应方之一。",
    descriptionEn:
      "Shandong organic-peroxide producer; one of the main domestic suppliers of MEKP/BPO initiators for FRP.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-jiangsu-toughener-rubber",
    name: "江苏永晟橡胶科技有限公司",
    nameEn: "Jiangsu Yongsheng Rubber Technology Co., Ltd.",
    location: "江苏南京",
    locationEn: "Nanjing, Jiangsu, China",
    province: "江苏",
    category: "additive",
    products: ["环氧增韧剂", "液体橡胶 CTBN", "热固性树脂改性剂"],
    productsEn: ["Epoxy tougheners", "CTBN liquid rubber", "Thermoset resin modifiers"],
    processList: ["合成", "复配"],
    processListEn: ["Synthesis", "Compounding"],
    established: 2006,
    verified: false,
    description: "南京本地液体橡胶与环氧增韧剂厂，配套高性能复合材料客户。",
    descriptionEn:
      "Nanjing liquid rubber and epoxy toughener maker, supplying high-performance composite customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-shanghai-pruvent-flame",
    name: "上海普润复合材料阻燃剂有限公司",
    nameEn: "Shanghai Purun Composite Flame Retardant Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "additive",
    products: ["磷氮系阻燃剂", "膨胀型阻燃剂", "环保阻燃剂"],
    productsEn: ["P-N flame retardants", "Intumescent flame retardants", "Eco-friendly flame retardants"],
    processList: ["合成", "复配"],
    processListEn: ["Synthesis", "Compounding"],
    established: 2010,
    verified: false,
    description: "上海本地无卤阻燃剂厂，FRP/SMC 客户配套较多。",
    descriptionEn:
      "Shanghai halogen-free flame retardant maker primarily serving FRP/SMC customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "ad-wuxi-gf-compound",
    name: "无锡华润玻纤增强尼龙有限公司",
    nameEn: "Wuxi Huarun GF-Reinforced Nylon Co., Ltd.",
    location: "江苏无锡",
    locationEn: "Wuxi, Jiangsu, China",
    province: "江苏",
    category: "additive",
    products: ["玻纤增强 PA6", "玻纤增强 PA66", "长玻纤增强料"],
    productsEn: ["GF-reinforced PA6", "GF-reinforced PA66", "Long-fiber-reinforced compounds"],
    processList: ["双螺杆挤出", "切粒"],
    processListEn: ["Twin-screw extrusion", "Pelletizing"],
    established: 2008,
    verified: false,
    description: "无锡本地玻纤增强尼龙厂，汽车结构件与电子电器客户为主。",
    descriptionEn:
      "Wuxi GF-reinforced nylon compounding plant, primarily serving automotive structural and E&E customers.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },
  {
    id: "ad-jiangsu-sizing-agent",
    name: "江苏宏泰玻纤浸润剂有限公司",
    nameEn: "Jiangsu Hongtai Glass Fiber Sizing Agent Co., Ltd.",
    location: "江苏镇江",
    locationEn: "Zhenjiang, Jiangsu, China",
    province: "江苏",
    category: "additive",
    products: ["玻纤浸润剂", "短切纱浸润剂", "电子级玻纤浸润剂"],
    productsEn: ["Glass fiber sizing agents", "Chopped strand sizing agents", "Electronic-grade GF sizing"],
    processList: ["乳化复配"],
    processListEn: ["Emulsion compounding"],
    established: 2005,
    verified: false,
    description: "镇江本地玻纤浸润剂厂，国内主要玻纤厂配套客户。",
    descriptionEn:
      "Zhenjiang glass fiber sizing maker, supplying major Chinese glass fiber producers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // K. Equipment makers (filament winding / RTM / cutting / NDT — more)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "eq-jiangsu-hongkai-pul",
    name: "江苏鸿凯重工科技有限公司",
    nameEn: "Jiangsu Hongkai Heavy Industry Technology Co., Ltd.",
    location: "江苏南通",
    locationEn: "Nantong, Jiangsu, China",
    province: "江苏",
    category: "equipment",
    products: ["拉挤生产线", "拉挤模具", "牵引机"],
    productsEn: ["Pultrusion lines", "Pultrusion dies", "Pulling machines"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2003,
    verified: false,
    description: "南通本地拉挤设备主力厂，国内多家拉挤厂全线设备供应商。",
    descriptionEn:
      "Nantong-based pultrusion equipment leader, supplying full-line equipment to multiple Chinese pultruders.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-zhejiang-rtm-mixer",
    name: "浙江诺凯复合材料注射设备有限公司",
    nameEn: "Zhejiang Nuokai Composite Injection Equipment Co., Ltd.",
    location: "浙江杭州",
    locationEn: "Hangzhou, Zhejiang, China",
    province: "浙江",
    category: "equipment",
    products: ["RTM 注射机", "HP-RTM 装备", "树脂混合计量泵"],
    productsEn: ["RTM injection machines", "HP-RTM equipment", "Resin mix-meter pumps"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2011,
    verified: false,
    description: "杭州本地 RTM/HP-RTM 装备厂，配套国内汽车碳纤维结构件客户。",
    descriptionEn:
      "Hangzhou RTM/HP-RTM equipment maker, supplying domestic automotive CF structural part customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "eq-shandong-ultrasonic",
    name: "山东盛威复合材料超声切割设备有限公司",
    nameEn: "Shandong Shengwei Composite Ultrasonic Cutting Equipment Co., Ltd.",
    location: "山东济南",
    locationEn: "Jinan, Shandong, China",
    province: "山东",
    category: "equipment",
    products: ["超声切割机", "复材专用 CNC", "数控刻型设备"],
    productsEn: ["Ultrasonic cutting machines", "Composite-specific CNC", "CNC profiling equipment"],
    processList: ["设备制造"],
    processListEn: ["Equipment manufacturing"],
    established: 2012,
    verified: false,
    description: "山东本地超声切割与复材数控设备厂，配套风电叶片与航空客户。",
    descriptionEn:
      "Shandong ultrasonic cutting and composite-CNC equipment maker, supplying wind blade and aerospace customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // L. Mold workshops (regional)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "md-jiangsu-yancheng-blade-mold",
    name: "江苏盐城润滕风电叶片模具有限公司",
    nameEn: "Jiangsu Yancheng Runteng Wind Blade Mold Co., Ltd.",
    location: "江苏盐城",
    locationEn: "Yancheng, Jiangsu, China",
    province: "江苏",
    category: "mold",
    products: ["风电叶片模具", "海上风电叶片模具", "结构件模具"],
    productsEn: ["Wind blade molds", "Offshore wind blade molds", "Structural part molds"],
    processList: ["数控加工", "蒸汽加热模具"],
    processListEn: ["CNC machining", "Steam-heated molds"],
    established: 2010,
    verified: false,
    description: "盐城本地风电叶片模具厂，沿海大兆瓦项目配套。",
    descriptionEn:
      "Yancheng wind blade mold shop, supplying coastal large-MW projects.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "md-zhejiang-yacht-mold",
    name: "浙江黄岩海洋复材模具有限公司",
    nameEn: "Zhejiang Huangyan Marine Composite Mold Co., Ltd.",
    location: "浙江台州",
    locationEn: "Taizhou, Zhejiang, China",
    province: "浙江",
    category: "mold",
    products: ["游艇模具", "玻璃钢船模", "公务艇模具"],
    productsEn: ["Yacht molds", "FRP boat molds", "Government boat molds"],
    processList: ["数控加工", "FRP 模具"],
    processListEn: ["CNC machining", "FRP molds"],
    established: 2005,
    verified: false,
    description: "台州黄岩本地船模厂，游艇与渔船船模出口为主。",
    descriptionEn:
      "Huangyan (Taizhou) boat mold shop, primarily exporting yacht and fishing-boat molds.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "md-jiangsu-auto-cf-mold",
    name: "江苏苏州汽车碳纤维模具有限公司",
    nameEn: "Jiangsu Suzhou Automotive CF Mold Co., Ltd.",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "mold",
    products: ["碳纤维 RTM 模具", "HP-RTM 模具", "汽车复材结构件模具"],
    productsEn: ["CF RTM molds", "HP-RTM molds", "Automotive composite structural molds"],
    processList: ["数控加工", "钢模制造"],
    processListEn: ["CNC machining", "Steel mold fabrication"],
    established: 2013,
    verified: false,
    description: "苏州汽车碳纤维 RTM 模具专业厂，新能源车主机厂配套。",
    descriptionEn:
      "Suzhou automotive CF RTM mold specialist, supplying NEV OEM programs.",
    certifications: ["IATF 16949"],
    certificationsEn: ["IATF 16949"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // M. Tooling consumables (release agents / vacuum bag / sealants — more)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "tl-jiangsu-sealant-tape",
    name: "江苏皓辉复合材料密封胶有限公司",
    nameEn: "Jiangsu Haohui Composite Sealant Tape Co., Ltd.",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "tooling",
    products: ["密封胶条", "真空袋密封胶", "高温密封胶"],
    productsEn: ["Sealant tape", "Vacuum bag sealant", "High-temperature sealant"],
    processList: ["复配", "挤出"],
    processListEn: ["Compounding", "Extrusion"],
    established: 2009,
    verified: false,
    description: "苏州本地密封胶条厂，风电与航空真空成型配套。",
    descriptionEn:
      "Suzhou sealant tape maker, supplying wind and aerospace vacuum-process applications.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
  {
    id: "tl-shanghai-peelply",
    name: "上海凯威复合材料工艺辅材有限公司",
    nameEn: "Shanghai Kaiwei Composite Process Consumables Co., Ltd.",
    location: "上海",
    locationEn: "Shanghai, China",
    province: "上海",
    category: "tooling",
    products: ["脱模布", "导流网", "真空袋膜"],
    productsEn: ["Peel ply", "Flow media", "Vacuum bag film"],
    processList: ["纺织", "薄膜复合"],
    processListEn: ["Weaving", "Film lamination"],
    established: 2010,
    verified: false,
    description: "上海本地真空导入辅材厂，配套华东风电与航空客户。",
    descriptionEn:
      "Shanghai vacuum-infusion consumables maker supplying east-China wind and aerospace customers.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // N. Carbon fiber recycled product / specialty manufacturer
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fin-recycled-cf-product",
    name: "江苏威盛新材料再生碳纤维制品事业部",
    nameEn: "Jiangsu Weisheng — Recycled CF Products Division",
    location: "江苏苏州",
    locationEn: "Suzhou, Jiangsu, China",
    province: "江苏",
    category: "manufacturer",
    products: ["再生碳纤维板", "rCF 增强 PP/PA 母粒", "再生碳毡"],
    productsEn: ["Recycled CF plate", "rCF-reinforced PP/PA masterbatch", "Recycled carbon felt"],
    processList: ["热裂解", "再生切粒"],
    processListEn: ["Pyrolysis", "Recycled pelletizing"],
    established: 2018,
    verified: false,
    description: "国内再生碳纤维制品业务的代表性事业部，rCF 增强料与板材是核心。",
    descriptionEn:
      "Representative Chinese rCF-products business; rCF-reinforced compounds and plate are core lines.",
    certifications: ["ISO 9001"],
    certificationsEn: ["ISO 9001"],
  },
];

async function main() {
  console.log(`Seeding ${entries.length} v5 supply-chain entries…`);
  let inserted = 0;
  let updated = 0;

  for (const e of entries) {
    const existing = await db.query.supplierListings?.findFirst?.({
      where: (t, { eq }) => eq(t.id, e.id),
    });
    await db
      .insert(supplierListings)
      .values(e)
      .onConflictDoUpdate({
        target: supplierListings.id,
        set: { ...e, updatedAt: new Date() },
      });
    if (existing) updated++;
    else inserted++;
    console.log(`  ✓ ${e.id}  ${e.nameEn}`);
  }

  console.log(`\nv5 seed complete. inserted=${inserted}  updated=${updated}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
