// Pultrusion-focused query pools for one-shot bulk ingest.
// Designed to be broader than the daily cron's rotating pool so we can
// harvest a large chunk of pultrusion-related content in a single run.

export const PULTRUSION_PAPER_QUERIES = [
  // Core process
  "pultrusion process FRP",
  "pultrusion die design composite",
  "thermal gradient pultrusion",
  "pultrusion curing kinetics",
  "pultrusion pulling force",
  "pultrusion fiber volume fraction",
  "pultrusion void defect",
  "pultrusion roving tension",
  "pultrusion pull speed optimization",
  "pultrusion resin impregnation",
  "pultrusion process simulation",
  "pultrusion die heating",
  // Fiber systems
  "carbon fiber pultruded unidirectional",
  "glass fiber pultrusion E-glass",
  "basalt fiber pultruded profile",
  "aramid fiber pultrusion hybrid",
  // Resin variants
  "thermoplastic pultrusion composite",
  "UV pultrusion photo-initiated",
  "vinyl ester pultrusion corrosion",
  "polyurethane pultrusion profile",
  "epoxy pultrusion high-performance",
  // Products & applications
  "pultruded GFRP rebar concrete",
  "pultruded window frame thermal bridge",
  "pultruded cable tray structural",
  "pultruded grating flexural",
  "pultruded I-beam structural",
  "pultruded wind blade spar cap",
  "pultruded utility pole",
  "pultruded bridge deck GFRP",
  "pultruded sandwich panel",
  "pultruded solar module frame",
  "pultruded hybrid steel FRP",
  // Characterization
  "pultrusion fiber matrix interface",
  "pultrusion fatigue behavior",
  "pultrusion creep long-term",
  "pultrusion shear strength interlaminar",
  "pultruded bolt hole bearing",
  "pultrusion fire flame retardant",
];

// ───── Expansion batch: window/door · automotive HP-RTM · profile apps ─────
export const EXPANSION_PAPER_QUERIES = [
  // 门窗拉挤 - window & door profiles
  "pultruded window frame thermal break",
  "pultruded door frame composite",
  "FRP window profile energy efficient",
  "GFRP window frame passive house",
  "pultruded sliding door composite",
  "fiberglass window mullion thermal",
  // 汽车 HP-RTM
  "HP-RTM automotive carbon fiber structural",
  "HP-RTM B-pillar CFRP",
  "HP-RTM battery enclosure electric vehicle",
  "HP-RTM roof panel CFRP automotive",
  "automotive CFRP HP-RTM mass production",
  "high-pressure resin transfer molding epoxy fast-cure",
  "HP-RTM composite car body panel",
  "HP-RTM preform automotive",
  "HP-RTM mold seal injection",
  "HP-RTM process parameter optimization",
  // 拉挤型材扩展应用
  "pultruded railway composite sleeper",
  "pultruded electrical power cross-arm",
  "pultruded fiber optic cable tray",
  "pultruded aerospace composite beam",
  "pultruded marine walkway offshore",
  "pultruded building structural reinforcement",
  "pultruded chemical industry platform grating",
  "pultruded HVAC duct composite",
  "pultruded antenna mast tower",
  "pultruded boat hull composite",
  "pultruded bridge pedestrian FRP",
  "pultruded EV charging station structural",
];

// Patent-pool expansion — Chinese + English, focused.
export const EXPANSION_PATENT_QUERIES = [
  // 门窗拉挤
  "拉挤 门窗 型材",
  "玻璃钢 门窗",
  "pultruded window frame composite",
  "pultruded door frame structural",
  "thermal break pultruded window",
  "断桥 拉挤 窗框",
  "pultruded sliding door FRP",
  "pultruded curtain wall profile",
  // 汽车 HP-RTM
  "HP-RTM automotive CFRP",
  "HP-RTM B-pillar carbon fiber",
  "HP-RTM battery enclosure electric",
  "汽车 高压 RTM 碳纤维",
  "汽车 HP-RTM 结构件",
  "HP-RTM injection apparatus automotive",
  "HP-RTM fast cure epoxy automotive",
  "HP-RTM mold automotive structural",
  "HP-RTM preform carbon fiber automotive",
  "高压 RTM 汽车 模具",
  "高压 RTM 电池箱",
  "HP-RTM roof panel vehicle",
  // 拉挤型材应用
  "pultruded railway sleeper composite",
  "pultruded power transmission cross-arm",
  "pultruded aerospace structural beam",
  "pultruded HVAC tubular duct",
  "pultruded handrail offshore platform",
  "拉挤型材 建筑加固",
  "拉挤型材 桥梁",
  "拉挤型材 轨道交通",
  "拉挤型材 5G 基站",
  "pultruded infrastructure profile",
  "pultruded utility pole composite",
  "pultruded boat hull",
  "拉挤 车厢 地板",
  "pultruded floor panel vehicle",
];

// ───── Thermoplastic pultrusion wave ─────
export const THERMOPLASTIC_PAPER_QUERIES = [
  "thermoplastic pultrusion composite",
  "in-situ thermoplastic pultrusion polymerization",
  "thermoplastic unidirectional tape pultrusion",
  "reactive thermoplastic pultrusion caprolactam",
  "PA pultrusion continuous fiber",
  "PP polypropylene pultrusion composite",
  "PEEK pultrusion continuous fiber",
  "PPS pultrusion thermoplastic",
  "PEI thermoplastic pultrusion",
  "PA6 anionic polymerization pultrusion",
  "thermoplastic pultruded rebar recyclable",
  "thermoplastic composite pultrusion welding",
  "continuous fiber thermoplastic profile consolidation",
  "thermoplastic pultruded profile recyclability",
  "thermoplastic pultruded structural beam",
  "thermoplastic pultrusion process modeling",
  "thermoplastic pultrusion die design",
  "thermoplastic matrix pultrusion interface",
  "thermoplastic pultruded composite mechanical",
  "thermoplastic pultruded wind blade spar",
];

export const THERMOPLASTIC_PATENT_QUERIES = [
  "thermoplastic pultrusion apparatus",
  "in-situ thermoplastic pultrusion",
  "reactive pultrusion caprolactam",
  "PA6 pultrusion process",
  "polypropylene pultrusion composite",
  "PEEK pultruded profile",
  "thermoplastic pultrusion die heating",
  "thermoplastic pultruded rebar process",
  "热塑拉挤",
  "热塑性 拉挤 型材",
  "连续纤维 热塑 拉挤",
  "聚酰胺 拉挤",
  "聚丙烯 拉挤",
  "聚醚醚酮 拉挤",
  "可回收 拉挤",
  "thermoplastic pultruded tape UD",
  "reactive thermoplastic rebar pultrusion",
  "thermoplastic pultruded wind blade component",
  "thermoplastic pultruded automotive profile",
  "thermoplastic pultruded structural member",
];

export const PULTRUSION_PATENT_QUERIES = [
  "pultrusion die apparatus",
  "pultrusion pulling mechanism",
  "pultruded profile structure",
  "pultrusion resin bath",
  "pultrusion impregnation chamber",
  "pultrusion preform guide",
  "pultrusion heating zone",
  "pultrusion die coating",
  "pultrusion curing oven",
  "thermoplastic pultrusion line",
  "UV curing pultrusion",
  "hybrid pultrusion reinforcement",
  "pultruded rebar manufacture",
  "pultruded window frame process",
  "pultrusion cable tray mold",
  "pultruded grating continuous",
  "pultruded wind blade spar mold",
  "pultruded utility pole structure",
  "pultrusion fiber tension control",
  "pultrusion quality inspection",
  "pultrusion solar frame composite",
  "pultrusion bridge deck panel",
  "pultrusion tubular profile",
  "pultrusion cutting device",
  "carbon fiber pultrusion apparatus",
  "glass fiber pultrusion equipment",
];

// Priority queries for Google-Patents bulk ingest: pultrusion + RTM,
// glass & carbon fiber emphasis. Mix of English + Chinese for CNIPA coverage.
export const GP_PATENT_QUERIES = [
  // 拉挤 + 玻纤
  "pultrusion glass fiber die",
  "pultrusion E-glass profile",
  "玻璃纤维 拉挤 模具",
  "glass fiber pultrusion rebar concrete",
  "pultruded glass fiber window frame",
  "pultruded glass fiber grating",
  "玻璃钢 拉挤 型材",
  "拉挤 玻纤 工艺",
  // 拉挤 + 碳纤
  "pultrusion carbon fiber unidirectional",
  "pultruded carbon fiber spar cap wind",
  "碳纤维 拉挤 预浸料",
  "pultruded carbon fiber rebar",
  "carbon fiber pultrusion prepreg",
  "carbon fiber pultruded tube",
  // 拉挤-工艺/设备
  "pultrusion die thermal zone",
  "pultrusion resin injection chamber",
  "pultrusion pulling clamp",
  "pultrusion preform guide plate",
  "UV pultrusion photo-initiated",
  "thermoplastic pultrusion consolidation",
  "拉挤 树脂槽",
  "拉挤 预成型",
  "拉挤 牵引 装置",
  // 拉挤-应用
  "pultruded cable tray composite",
  "pultruded solar module frame",
  "pultruded bridge deck panel",
  "pultruded utility pole composite",
  "拉挤 电缆桥架",
  "拉挤 光伏边框",
  // RTM + 玻纤
  "resin transfer molding glass fiber",
  "RTM glass fiber preform mold",
  "RTM glass fiber composite",
  "VARTM glass fiber infusion",
  "玻璃纤维 RTM 成型",
  "玻纤 树脂传递模塑",
  // RTM + 碳纤
  "resin transfer molding carbon fiber",
  "RTM carbon fiber preform",
  "HP-RTM carbon fiber automotive",
  "RTM carbon fiber mold composite",
  "碳纤维 RTM",
  "碳纤维 高压 RTM",
  // RTM-工艺/设备
  "resin transfer molding mold apparatus",
  "RTM injection port flow",
  "RTM tooling composite",
  "LRTM light resin transfer molding",
  "VARTM vacuum resin infusion",
  "RTM preform binder",
  "树脂传递模塑 模具",
  "RTM 预成型 注胶",
];
